### ISSUE TITLE
nuget.org "Project Site" Url

### ISSUE THREAD

**Issue by tinohager** [MapsterMapper/Mapster#114]
The nuget.org url does not link to this project https://www.nuget.org/packages/Mapster/

**Comment by chaowlert** [comment]
Updated

**Comment by ManfredLange** [comment]
[NuGet](https://www.nuget.org/packages/Mapster/) still links to https://github.com/chaowlert/Mapster instead of https://github.com/MapsterMapper/Mapster

What am I missing?

**Comment by tinohager** [comment]
yes is always wrong
