### ISSUE TITLE
Mapping Iqueryable objects which is having foreign keys relation

### ISSUE THREAD

**Issue by AbhinavSharma1987** [MapsterMapper/Mapster#115]
Hi chaowlert,

I have a situation where I have 2 domain class where class1 is referring class2. On then other side the I have 2 entity dbcontext class which is having foreign key relation in between.

I want to map the Iqueryable of entity class (Parent) to Iqueryable of domain class1 (Parent class).

Could you please suggest me If I can achieve using Mapster.

Thanks,
Abhinav

**Comment by chaowlert** [comment]
Could you pls provide example of entity classes and domain classes?

**Comment by chaowlert** [comment]
Close as no response
