### ISSUE TITLE
Converting Linq expression from one Type to another type

### ISSUE THREAD

**Issue by AbhinavSharma1987** [MapsterMapper/Mapster#116]
Hi,

I do want to convert the expression System.Linq.Expressions.Expression<Func<Source, bool>> to System.Linq.Expressions.Expression<Func<Destination, bool>> Expression.

Could you please provide me the help to achieve so.

Thanks,
Abhinav

**Comment by chaowlert** [comment]
Mapster doesn't provide function to convert expression. Pls tell me more about your business scenario. I think what you're trying to do is incorrect way of using Mapster.

**Comment by chaowlert** [comment]
Close as no response
