### ISSUE TITLE
Enum to class mapping with 3.1.0

### ISSUE THREAD

**Issue by raphibolliger** [MapsterMapper/Mapster#118]
In one of my projects i use Mapster Version 2.6.1. There is an other project with Mapster Version 3.1.0
With the new version of Mapster I'm not able to map a **enum** to a **class**. I've looked through all the milestones but i could not find any changes to enum mapping as in version 2.6.1.

My enum and class definitions are following:

```c#
public enum CustomerType
{
    Company, Private
}

public class EnumViewModel
{
    public int Value { get; set; }
    public string Text { get; set; }
}
```
I'd like to map my CustomerType enum to the EnumViewModel class with the following definition:

```c#
TypeAdapterConfig<CustomerType, EnumViewModel>.NewConfig()
    .Map(dest => dest.Text, src => src.GetDisplayName())
    .Map(dest => dest.Value, src => (int)src);
```

Then i use it as follows:
```c#
var customer = await _customerRepository.GetAsync(id);
var enumViewModel = customer.CustomerType.Adapt<EnumViewModel>();
```
Wit Mapster Version 3.1.0 i always get a
`System.InvalidCastException: "Invalid cast from 'CustomerType' to 'EnumViewModel'`
With Mapster Version 2.6.1 all works fine.

Is there anybody with the same issues? Or is it necessary to add a setting value for the new version of Mapster to map enum to class?

**Comment by chaowlert** [comment]
I cannot recall what cause the issue. For now, pls use MapWith instead.

            TypeAdapterConfig<CustomerType, EnumViewModel>.NewConfig()
                .MapWith(src => new EnumViewModel {Text = src.GetDisplayName(), Value = (int) src});
