### ISSUE TITLE
Cannot use .Adapt in Hangfire

### ISSUE THREAD

**Issue by jbjumbojb** [MapsterMapper/Mapster#121]
Cannot use .Adapt in Hangfire

```
BackgrouJob.Enqueun(()=>Task1(obj));

public void Task1(MyType obj)
{
     var dest = obt.Adapt<MyType2>();
}
```
then the process is terminating due to StackOverflowException.

**Comment by chaowlert** [comment]
Pls try using `PreserveReference` (https://github.com/MapsterMapper/Mapster/wiki/Object-references#preserve-reference-preventing-circular-reference-stackoverflow)
