### ISSUE TITLE
Inline mappings

### ISSUE THREAD

**Issue by siberianguy** [MapsterMapper/Mapster#122]
We have [this conversation](https://github.com/AutoMapper/AutoMapper/issues/2317) about inline mappings in AutoMapper. I'm considering changing the library if AutoMapper doesn't allow to do that, so I'm curious what is your stance on this?

**Comment by chaowlert** [comment]
We do provide inline mapping in fast manner. Compilation will run once on first hit, subsequent mapping should be super fast.

```
//inline setting here
var config = TypeAdapterConfig.Default.Fork(forked => forked.ForType<Poco, Dto>().Ignore(dto => dto.Id));

//pass config to mapping
var dest = poco.Adapt<Dto>(config);
```

see more here https://github.com/chaowlert/Mapster/wiki/Config-location#keep-together-with-mapping

**Comment by chaowlert** [comment]
PS by default, if your mapping is simple, you don't need to have any config. https://github.com/chaowlert/Mapster/wiki/Data-types#mappable-objects
