### ISSUE TITLE
Mapping JArray to Poco Array

### ISSUE THREAD

**Issue by johnhamm** [MapsterMapper/Mapster#126]
I am switching from Automapper to Mapster, but I can't seem to figure out how to map a JArray to a POCO Array.

My code:

```
public class NameAge {
            public string Name { get; set; }
            public int Age { get; set; }
        }
...
var jsonArr = @"[ { ""Name"":""John"", ""Age"": 25 }, {""Name"":""Cathy"", ""Age"":20 } ]";
var jarr = JArray.Parse(jsonArr);
var arr = jarr.Adapt<NameAge[]>();
```

The array is successfully created with a correct length of 2, but none of the properties are mapped over.  I get the same result with:

`var list = jarr.Adapt<List<NameAge>>();`

**Comment by chaowlert** [comment]
Hi, I just created [Mapster.JsonNet](https://www.nuget.org/packages/Mapster.JsonNet/1.0.0). Hope this package help.
