### ISSUE TITLE
Ignore source members

### ISSUE THREAD

**Issue by DavidNorena** [MapsterMapper/Mapster#130]
Hi awesome work, I spend like 2 hours "mastering" this lib and it's really awesome, but the only thing I miss from AutoMapper (Sorry for mention it here) its ignore ForSourceMember,

Mapster has the ignore method, I like the one that you pass and array of names,

**.ignore(array of member names to ignore)**

But it only works for destination members, but not for source's ones :( too bad, so my real question, its, how can you ignore the mapping from source members, this is because Im my bussiness layer I need to ignore the mapping of some properties, but Im working with DTOs and I dont have access to entities and neither its properties....

Thank you very much !

**Comment by chaowlert** [comment]
2 ways, [annotation](https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members#ignore-by-attribute) (`AdaptIgnore`), and [rule based ignore](https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members#rule-based-ignore) (`config.IgnoreMember((member, side) => member.Name == "foo" && side == MemberSide.Source`).

**Comment by chaowlert** [comment]
PS. Ignore method also accept string, you can write `Ignore(nameof(Poco.foo))`.

**Comment by DavidNorena** [comment]
After reading I came up with the rule based ignore solution too.. but isn't working, can you please tell me what Im doing wrong 

Thanks for your quick response.
[Mapping.zip](https://github.com/MapsterMapper/Mapster/files/1454591/Mapping.zip)

**Comment by DavidNorena** [comment]
```
// Copyright (c) 2017 David Noreña. All rights reserved.

using System;
using System.Linq;
using System.Reflection;
using Mapster;
using Shouldly;
using Xunit;
using Xunit.Abstractions;

namespace DabitcoExt.Tests.Data.Mapping
{
  public class MapsterTest
  {
    private readonly ITestOutputHelper output;
    
    public MapsterTest(ITestOutputHelper output)
    {
      this.output = output;
    }

    [Fact]
    public void ModelToEntityIgnoreTest()
    {

      TypeAdapterConfig<Models.CityModel, Entities.CityEntity>
        .NewConfig()
        .Map(dest => dest.Name, src => src.CityName)
        .Map(dest => dest.StateID, src => src.StateCode)
        .IgnoreMember((member, side) => {
          output.WriteLine($"Member:{member.Name} Side:{side}");
          return member.Name == "CityName" && side == MemberSide.Source;
        });

      var model = new Models.CityModel
      {
        ID = 1,
        CityName = "Bogota",
        StateCode = 2
      };

      var entity = model.Adapt<Entities.CityEntity>();
      entity.ID.ShouldBe(model.ID);
      entity.Name.ShouldNotBe(model.CityName);
      entity.StateID.ShouldBe(model.StateCode);
    }
  }
}

```
Correct me if I'm wrong, but I think it's a bug, its giving me weird source member names:

Standard Output Messages:
 Member:ID Side:Destination
 Member:ID Side:Source
 Member:Name Side:Destination
 Member:StateID Side:Destination
 Member:<ID>k__BackingField Side:Destination
 Member:<Name>k__BackingField Side:Destination
 Member:<StateID>k__BackingField Side:Destination

**Comment by chaowlert** [comment]
Hi @DavidNorena,

It is because there is `.Map(dest => dest.Name, src => src.CityName)` setting, pls remove this line. In fact, if name is not the same, you also don't need `IgnoreMember` command.

**Comment by DavidNorena** [comment]
Im working on a Field Level Entity Permissions.

I need this because First I need to configure the mapping ... and then somewhere in application life, I need to ignore some properties, based on user permissions, both from source members and for destination members more or less like this:

There is a City Entity like the following:

```
City {
  Id,
  Name,
  StateId,
  AuditProps
}
```

And a Model or Dto CityModel like this:

```
CityModel 
{
  ID,
  CityName,
  StateCode
}
```

The names in the Dto not always be the same as the entity.

And in the business layer I work only with Dtos, I don't need to know anything about entity properties.

Its the layer work to Adapt the Model to Entity and then sendit to entity framework, but also, control field level permissions based on the current logged user.

So if:

User has permissions to SELECT entity City but only Id and Name properties.

I select the entity from entity framework, but I need to ignore some properties when converting to Model or Dto based on previous permissions.

User has permissions to UPDATE entity City but only Name:

Then when Adpating from Model to Entity I need to ignore again some properties, 

Permissions are based on entity properties -> so I dont need to have a lot of them If I have multiple Dtos.

That's why when:
* Adapting from entity to model I need to ignore SOURCE MEMBERS.
* Adapting from model to entity I need to ignore DESTINATION MEMBERS.

Thanks for your great help, I hope you understand what I'm trying to achieve, or send me a Light to do it other way, or what Im doing wrong !

**Comment by chaowlert** [comment]
im not entirely understand. but you mentioned about permission, then i think you need to have [multiple configs](https://github.com/MapsterMapper/Mapster/wiki/Config-instance) for each role, and pass the config to `Adapt` method.

Another way is using [IgnoreIf](https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members#ignore-conditionally) to ignore property at runtime. But you might also need to [pass user role at runtime](https://github.com/MapsterMapper/Mapster/wiki/Setting-values#passing-run-time-value).

**Comment by DavidNorena** [comment]
Thanks man, I'm testing IgnoreIf too, but there's not way to ignore source members ... only destination members with it .... 

With dynamically mapping I mean, you configure in some place in you app the mapping related to Dto and Entity, but, in runtime you fork that configuration, and ignore using parameters in runtime and ignore some properties when mapping ! But still IgnoreMemeber from source doesn't work ... its the only issue I have

**Comment by DavidNorena** [comment]
Thanks for your time, and your help !
