### ISSUE TITLE
Exception when using MapContext in ProjectToType mapping with LINQ to Entities

### ISSUE THREAD

**Issue by philippjenni** [MapsterMapper/Mapster#131]
Hi,

I become the follow Exception

"An exception of type 'System.NotSupportedException' occurred in EntityFramework.SqlServer.dll but was not handled in user code

Additional information: LINQ to Entities does not recognize the method 'System.Object get_Item(System.String)' method, and this method cannot be translated into a store expression."

when i use MapContext in a mapping an translate the query with ProjectToType.

My Mapping is the Follow:

```
            TypeAdapterConfig<Verwaltungseinheit, ConfigVerwaltungseinheit3UpperCaseDto>.NewConfig()
                .Map(dto => dto.Id, data => data.Id)
                .Map(dto => dto.BezeichnungZeile1Value, data => data.Bezeichnung.ToUpper())
                .Map(dto => dto.BezeichnungZeile2Value, data => data.Ort.ToUpper())
                // defaultLanguageIsoCode wird als Parameter bei der Projektion übergeben
                .Map(dto => dto.LanguageIsoCode, data => MapContext.Current.Parameters["defaultLanguageIsoCode"])
                .Map(dto => dto.TeamsFilter, data => data.Id)
                // Bezeichnung nicht abfüllen, da der Wert über den BezeichnungValue Wert erzeugt wird.
                .Ignore(dto => dto.Bezeichnung)
                // Content Filter ignorieren da nur ID's in der Datenbank vorhanden sind, aber Namen für die App Verwendet werden. -> Mandantenübergreifender Content !!!
                .Ignore(dto => dto.ContentFilter);
```

Here my Converter Method:

```
   public static IList<ConfigVerwaltungseinheit3UpperCaseDto> ConvertToConfigVerwaltungseinheit3UpperCaseDto(IQueryable<Verwaltungseinheit> query, string defaultLanguageIsoCode)
        {
            using (var scope = new MapContextScope())
            {
                scope.Context.Parameters.Add("defaultLanguageIsoCode", defaultLanguageIsoCode);
                return query.ProjectToType<ConfigVerwaltungseinheit3UpperCaseDto>().ToList();
            }
        }
```

Do you know how to fix it?

**Comment by chaowlert** [comment]
I don't think EF works with `MapContext`. I think you should query first and `Adapt` to target type.

```
query.ToList()
    .BuildAdapter()
    .AddParameters("defaultLanguageIsoCode", defaultLanguageIsoCode)
    .AdaptToType<List<ConfigVerwaltungseinheit3UpperCaseDto>>();
```

**Comment by philippjenni** [comment]
I have an other mapping who i need the value from the MapContext to Filter data dynamic in the query.
The same query works in NHibernate fine but i don't know the difference between EF Linq and NH Linq queries.

I think it should be possible to pass values from the context to the query with MapContext

**Comment by chaowlert** [comment]
Yes, in theory, EF should be able to get value from MapContext. Based on your error provided, my guess is EF doesn't know how to access dictionary. Could you access from a static method?

    public static object GetMapContextData(string key) => MapContext.Current.Parameters[key];

then in your config

    .Map(dto => dto.LanguageIsoCode, data => GetMapContextData("defaultLanguageIsoCode")

PS. I didnt test. Just wild guess.

**Comment by philippjenni** [comment]
No.. Same Issue 

Additional information: LINQ to Entities does not recognize the method 'System.String GetMapContextData(System.String)' method, and this method cannot be translated into a store expression.

It tries to translate the method in an sql expression.

**Comment by chaowlert** [comment]
Then rather than static method, could you change to static property and hard code dictionary key?

**Comment by philippjenni** [comment]
I have tried with

`     public static string GetMapContextData()
        {
            return () => "de";
        }`

This returns the same error

**Comment by chaowlert** [comment]
I mean changing from method to property also

    public static object CurrentLang => MapContext.Current.Parameters[key];

**Comment by philippjenni** [comment]
As Property it works fine. Thanks
