### ISSUE TITLE
Mapping derived classes not working

### ISSUE THREAD

**Issue by Sascha-L** [MapsterMapper/Mapster#132]
Hi,

I have the following classes:

```
public class TestClass
 {
     public List<BaseClass> MyProperty  { get; set; } 
}
public class BaseClass {}
public class ClassA: BaseClass {} 
public class ClassB: BaseClass {}
```

If I run the following code:

```
var testClass = new TestClass(); 
testClass.MyProperty.Add(new ClassA()); testClass.MyProperty.Add(new ClassB());  
var mappedClass = testClass.Adapt<TestClass,TestClass>();
```

the new mappedClass instance has only two items of type BaseClass in "MyProperty" instead of new instances of ClassA and ClassB. How do I configure Mapster to don't map ClassA and ClassB to BaseClass ?

**Comment by chaowlert** [comment]
pls check here https://github.com/MapsterMapper/Mapster/wiki/Config-inheritance#include-derived-types

**Comment by Sascha-L** [comment]
Thanks, I already checked that, but can't find there a solution for this issue.

I don't know what is inside the MyProperty collection at design time. That's why the property is declared as "List<BaseClass>". At runtime the collection contains subclasses of BaseClass.

So it is neccessary to write the following code to map "TestClass" to "TestClass" with the same property declaration of "MyProperty"?

TypeAdapterConfig<Vehicle, VehicleDto>.NewConfig()
    .Include<ClassA, ClassA>()
   .Include<ClassB, ClassB>()
;

**Comment by Sascha-L** [comment]
Ok, I'm surprised that the above code really works. But why is this ugly code neccessary? It's a default behavior of many classes every one is using so it should be work automatically :-)

Also I need to dynamically fill the Include list with types at runtime. How is this possible? I have a lot of subsclasses and it is not good code to hardcode all types manually in the `Include<T,T>` methods. I need something like `Include(Type, Type)`

**Comment by chaowlert** [comment]
Yeah, the purpose of `Include` method is to map from type A to type B. In your case, it might be a bit weird.

Try this if you want something dynamic

    TypeAdapterConfig<TestClass, TestClass>.NewConfig()
        .Map(dest => dest.MyProperty, src => src.Adapt(src.GetType(), src.GetType()))

**Comment by Sascha-L** [comment]
Thank you so much for your help :-)

Your last code sample doesn't work, do you have a working one? I don't get it :-(

**Comment by chaowlert** [comment]
Yeah sorry, above code is wrong, plus I forgot that the property is list. Try this

```
TypeAdapterConfig<TestClass, TestClass>.NewConfig()
    .Map(dest => dest.MyProperty, src => src.MyProperty.Select(item => item.Adapt(item.GetType(), item.GetType()).ToList())
```

Basically, for `Adapt` method you can pass source type and destination type, and logic for mapping will be created once at runtime.

**Comment by Sascha-L** [comment]
Thank you so much! :-)
