### ISSUE TITLE
CompileException on mapping IEnumerable when compiled using .NET native toolchain

### ISSUE THREAD

**Issue by mobilemotion** [MapsterMapper/Mapster#134]
We recently switched from Mapster 2.6.1 to 3.1.8 and now observe the following exception when mapping `IEnumerable<T>` types:
`Mapster.CompileException` with inner exception `System.InvalidOperationEcxeption: Sequence contains no elements`

I was able to reproduce it with all versions >= 3.0.4, using the following snippet in a sample UWP App:

```
public class Test
{
    public void Run()
    {
        IEnumerable<Item1> list1 = new List<Item1> {new Item1 {Text = "someteststring"}};
        var list2 = TypeAdapter.Adapt<IEnumerable<Item2>>(list1);
    }
}

public class Item1
{
    public string Text { get; set; }
}

public class Item2
{
    public string Text { get; set; }
}
```

However, the exception is only thrown when activating the **Compile with .NET Native tool chain** in the build options - everything works as expected when compiled without the native tool chain, or when using Mapster 2.x (in this case, even the native tool chain option can be used!)

By the way, using `List<T>` or `IList<T>` instead of `IEnumerable<T>` seems to work as well.

Can someone confirm this behavior? Is there a workaround other than replacing all occurences of `IEnumerable` with different collection types?

**Comment by chaowlert** [comment]
Sorry for closing this. This issue might be outdated and no more valid.
