### ISSUE TITLE
Why 'Only first level member access on destination allowed'?

### ISSUE THREAD

**Issue by rulrok** [MapsterMapper/Mapster#136]
I'm trying to create the following mapping configuration

```cs
TypeAdapterConfig<TemplateAccordionSettingJson, ICustomPageCollapsableElement>
                .NewConfig()
                .Map(dest => dest.CustomPageSettingCreateDto.AccordionDisplayOnPage, src => src.DisplayOnPage)
                .Map(dest => dest.CustomPageSettingCreateDto.AccordionExpand, src => src.Expanded)
                .Map(dest => dest.CustomPageSettingCreateDto.AccordionPosition, src => src.Order);
```
But I get the exception from this line of the code:

https://github.com/MapsterMapper/Mapster/blob/845efa42913b68e25e5c23b97823f34802890a36/src/Mapster/Utils/ReflectionUtils.cs#L148

Why is it explicitly not possible?

Thanks 😄

**Comment by chaowlert** [comment]
I planned to add it in future release. For now pls use this

```
TypeAdapterConfig<TemplateAccordionSettingJson, ICustomPageCollapsableElement>
                .NewConfig()
                .Map(dest => dest.CustomPageSettingCreateDto, 
                     src => new CustomPageSettingCreateDto
                     {
                         AccordionDisplayPage = src.DisplayOnPage,
                         AccordionExpand = src.Expanded,
                         AccordionPosition = src.Order
                     });
```

**Comment by kirodge** [comment]
I thought that `source.Adapt(destination)` would map `source.FooBar` to `destination.Foo.Bar` (creating `Foo` if required in the process) without any configuration.

Could you please point that out on the wiki -  that currently only first level access on the destination is supported?  

Thanks!

**Comment by chaowlert** [comment]
4.0 now support multi-level member
