### ISSUE TITLE
copy or clone an object doesn't work for private member of base class

### ISSUE THREAD

**Issue by xbrossard** [MapsterMapper/Mapster#137]
I try to copy an object into another object of the same type; the private field of base class doesn't work, even if i use EnableNonPublicMember(true), IncludeMember with AccessModifier.Private or use AdaptMember attribute.

the source code is:

    namespace ClassLibrary2
    {
        public enum TypeVoie
    {
        rue,
        avenue,
        route,
        împasse
    }

    public class Ville
    {
        string nom;
        string codePostal;
        bool capital;

        public  Ville(string nom, string codePostal,bool capital)
        {
            this.nom = nom;
            this.codePostal = codePostal;
            this.capital = capital;
        }

        public  string  id()
        {
            return nom + codePostal + capital.ToString();
        }
    }
            
    /// <summary>
    /// classe composé
    /// </summary>
    public class Adresse
    {
        int noRue;
        string nomRue;
        TypeVoie typeVoie;
        Ville ville;
        Personne habitant;

        public Personne Habitant { get => habitant; set => habitant = value; }

        public  string  id()
        {
            return noRue.ToString() + nomRue + typeVoie.ToString() + ville.id();
        }

        public  Adresse(int rue, string nom,TypeVoie voie, Ville ville)
        {
            noRue = rue;
            nomRue = nom;
            typeVoie = voie;
            this.ville = ville;
        }

        public  Adresse()
        {
        }
    }

    /// <summary>
    /// classe de base composant
    /// </summary>
    public class Personne
    {
        /// <summary>
        /// l'attribut ne marche pas
        /// </summary>
        [AdaptMember]
        private string nom { get; set; }

        public string prenom { get; set; }

        Dictionary<string, Adresse> adresses = new Dictionary<string, Adresse>();

        public Dictionary<string, Adresse> Adresses { get => adresses; set => adresses = value; }

        public  Personne(string nom, string prenom, Adresse adresse)
        {
            this.nom = nom;
            this.prenom = prenom;
            if (adresse!=null)
            {
                adresses.Add(adresse.id(), adresse);
                adresse.Habitant = this;
            }
        }

        public  Personne()
        {
        }
    }

    /// <summary>
    /// classe composant
    /// </summary>
    public class Patient: Personne
    {
        string noSS;

        public  Patient(string nom, string prenom, Adresse adresse, string noSS):base(nom,prenom,adresse)
        {
            this.noSS = noSS;
        }

        public string NoSS { get => noSS; set => noSS = value; }
    }

    /// <summary>
    /// classe pour le test de code .NET standard 2.0
    /// </summary>
    public class ClassTestCopyStandard2
    {
        /// <summary>
        /// test de copy d'objet: récupération des informations d'un objet par linq to object, modification par ajout d'élément, puis recopie sur l'initial
        /// </summary>
        public void testCopyMapster()
        {
            Ville paris = new Ville("Paris", "78000", true);
            Ville lyon = new Ville("Lyon", "69000", false);

            Adresse adresse1 = new Adresse(10, "rue de la paix", TypeVoie.rue, paris);
            Adresse adresse2 = new Adresse(69, "rue marietton", TypeVoie.rue, lyon);

            Patient patient1 = new Patient("pattyn", "stéphane", adresse1,"22372727320");

            Patient patient2 = new Patient(null, null, null,null);

            //  premier test: copie de l'objet source dans destination -> les champs privés ne sont pas copiés -> modifier la copie de manière globale par EnableNonPublicMember(true) -> marche pas!
            //  deuxième test: après ajout d'un lien depuis adresse vers personne, exception lancé: "cannot instantiate Adress/Personne" -> ajout d'un constructeur sans parametre
            //  troisième test: après ajout des constructeurs vides, plante stackoverflow car référence cyclique -> ajout d'un PreserveReference

            //  la version globale ne marche pas...
            TypeAdapterConfig.GlobalSettings.Default.EnableNonPublicMembers(true);

            //  ca ne marche pas non plus...
            TypeAdapterConfig.GlobalSettings.Default.IncludeMember((member, side) => member.AccessModifier == AccessModifier.Internal
                                     || member.AccessModifier == AccessModifier.ProtectedInternal || member.AccessModifier == AccessModifier.Private );

            //TypeAdapterConfig.GlobalSettings.NewConfig(typeof(Patient), typeof(Patient));

            //  version dynamique
            TypeAdapterConfig.GlobalSettings.NewConfig(typeof(Personne), typeof(Personne)).EnableNonPublicMembers(true).PreserveReference(true);

            //  version générique
            //TypeAdapterConfig<Personne, Personne>.NewConfig().PreserveReference(true).EnableNonPublicMembers(true);

            patient2 = patient1.Adapt(patient2);
        }
`

patient2.nom always set to null

**Comment by xbrossard** [comment]
I have found a beginning of solution, replacing the GetFieldsAndProperties method like this:

        public static IEnumerable<IMemberModelEx> GetFieldsAndProperties(this Type type, bool allowNoSetter = true, BindingFlags accessorFlags = BindingFlags.Public)
        {
            var bindingFlags = BindingFlags.Instance | BindingFlags.DeclaredOnly | accessorFlags;

            IEnumerable<IMemberModelEx> returnValues = null;
            Type currentType = type;

            while (currentType!=null)
            {
                var properties = currentType.GetProperties(bindingFlags)
                    .Where(x => allowNoSetter || x.CanWrite)
                    .Select(CreateModel);

                if (returnValues == null)
                    returnValues = properties;
                else
                    returnValues = returnValues.Concat(properties);

                var fields = currentType.GetFields(bindingFlags)
                    .Where(x => allowNoSetter || !x.IsInitOnly)
                    .Select(CreateModel);

                if (returnValues == null)
                    returnValues = fields;
                else
                    returnValues = returnValues.Concat(fields);

                currentType = currentType.BaseType;
            }
            return returnValues;
        }

I try to get field and property of all base class and it works! but i don't know the impact of this change on other part of the component. Apparently, the option EnableNonPublicMembers doesn't work anymore if you specify different value for base class and derived class; the derived class overwrite the base class setting

**Comment by chaowlert** [comment]
Sorry, after very long consideration, I think I will not support using private fields in sub-class.
