### ISSUE TITLE
Passing run-time value with Adapt (not AdaptToType)

### ISSUE THREAD

**Issue by Laban1** [MapsterMapper/Mapster#140]
Hello,

We use your excellent mapper in a project for mapping between models (EF) and view models.  

In order to handle timezones, we use NodaTime and its LocalDateTime type in the view-models and regular DateTime in the models (to store via EF to SQL as UTC).   We get the timezone of a given client in the HTTP request and use this information to convert from LocalDateTime to UTC DateTime.

Here is an example of a mapping for this: 
```
TypeAdapterConfig<DesignSalesJobVm, DesignSalesJob>
    .NewConfig()
    .Map(dest => dest.FolderExpectedDate, src => ((LocalDateTime)src.FolderExpectedDate).ToUtc((string)MapContext.Current.Parameters[AimmConstants.TIMEZONE]));

TypeAdapterConfig<DesignSalesJob, DesignSalesJobVm>
    .NewConfig()
    .Map(dest => dest.FolderExpectedDate, src => ((DateTime)src.FolderExpectedDate).ToLocalDateTime((string)MapContext.Current.Parameters[AimmConstants.TIMEZONE]));

```

Retrieving data (converting from Model to View Model) works fine, e.g.:

```
// return designSalesJob.Adapt<DesignSalesJobVm>(); // Without runtime parameters, this is what we used.
return designSalesJob.BuildAdapter()
    .AddParameters(AimmConstants.TIMEZONE, RequestData.TimeZone)
    .AdaptToType<DesignSalesJobVm>();
```

However, when writing data (converting from View Model to Model), there is an issue:

```
var designSalesJob = context.DesignSalesJobs.Find(designSalesJobVm.DesignSalesJobId);

//designSalesJob = designSalesJobVm.Adapt(designSalesJob); // Works fine, it not using runtime parameters
designSalesJob = designSalesJobVm.BuildAdapter()
    .AddParameters(AimmConstants.TIMEZONE, RequestData.TimeZone)
    .AdaptToType<DesignSalesJob>();

context.Entry(designSalesJob).OriginalValues["RowVersion"] = designSalesJobVm.RowVersion; // <--- Problem here: "Member 'OriginalValues' cannot be called for the entity of type 'DesignSalesJob' because the entity does not exist in the context."
context.SaveChanges();
return WebApiResult<object>.New(null, designSalesJob.GetVersionJson());
```

The problem is that AdaptToType creates a new object instead of updating the existing object like Adapt does, which does not work with EF (the new object is not part of the context).

Can an overload be added to make Adapt work with run-time parameters?  Any other suggested solution?

Thanks!

**Comment by chaowlert** [comment]
Hi,

1. To copy to existing object, you can use, `AdaptTo`
2. If you use EF6, you can use [EF6 plugin](https://github.com/MapsterMapper/Mapster/wiki/EF6). To map to data context object.

**Comment by Laban1** [comment]
Hi,

Thanks for your response.

Due to time-constraints, I had to take a different approach and not use Mapster with run-time values for now (I could not find AdaptTo anywhere in the documentation, so did not know this functionality was already implemented).  I will likely re-visit this later again and try AdaptTo then (and perhaps the EF6 plugin).
