### ISSUE TITLE
Mapster issue 3.1.8

### ISSUE THREAD

**Issue by Gautam-1979** [MapsterMapper/Mapster#143]
The below mapping was working before 3.1.8
.Map(dest => dest.Texts, src => from i in src.Texts
                                                 where i.TextValue != null || src.IncludeNullValue == true
                                                 select new TextModel()
                                                 {
                                                     TextId = i.TextId, Value = i.TextValue
                                                 });

But now it is giving an error.
Getting the error
variable '' of type '' referenced from scope '', but it is not defined

**Comment by chaowlert** [comment]
Sorry for taking very long time to reply, I did unit test as you describe, but it works fine. Could you provide reproducible test?
