### ISSUE TITLE
How to get class library assembly reference in .NET Core project?

### ISSUE THREAD

**Issue by gecko-8** [MapsterMapper/Mapster#144]
I have an ASP.NET Core project (netcoreapp2.0) that references models in a class library project (netstandard2.0). I'm trying to use Mapster to map objects stored in the class library. The documentation says to call the Scan method from Startup.cs using the code:

    TypeAdapterConfig.GlobalSettings.Scan(assembly1, assembly2, assemblyN)

Where I'm having issues is how to best get the assembly reference for the class library to pass to the Scan method. I know how to use Assembly.GetEntryAssembly() to get the current assembly but not the referenced class library.

Any help would be appreciated,
Jason

**Comment by chaowlert** [comment]
You can use `Assembly.Load`.
