### ISSUE TITLE
Missing Dependency Injection Sample

### ISSUE THREAD

**Issue by fairking** [MapsterMapper/Mapster#146]
Hi everyone. I have found that it is quite hard to inject services into Mapster.
Have done some small sample just to show my solution (https://github.com/denis-pujdak-adm-it/MapsterSample).

If anyone has some better ideas please reply.

Thanks.

**Comment by makubexD** [comment]
Hi @denis-pujdak-adm-it , 
I think this implementation could help you. Take a look at this.

https://github.com/DevWithLin/CommonX

Best Regards

**Comment by denis-pujdak-adm-it** [comment]
Sorry @makubexD. It is not what I am looking for.

**Comment by chaowlert** [comment]
There is new plugin for dependency injection https://github.com/MapsterMapper/Mapster/wiki/Dependency-Injection

And you could see sample in sample project https://github.com/MapsterMapper/Mapster/tree/master/src/Sample.AspNetCore
