### ISSUE TITLE
Mapping to existing collection

### ISSUE THREAD

**Issue by Thorgard** [MapsterMapper/Mapster#150]
When mapping collections how does Mapster behave?

Does it assign new collection all the time?

I'm looking for similar behaviour to https://github.com/AutoMapper/AutoMapper.Collection

**Comment by chaowlert** [comment]
Yes, default behavior, Mapster will create new list every time. Mapster doesn't support mapping by id of item in collection.

If your purpose is to map from DTO to Data Domain class (and if you use EF6), I have plugin for this (https://github.com/MapsterMapper/Mapster/wiki/EF6).

**Comment by Thorgard** [comment]
@chaowlert I use EF Core. The problem is that when I map my DTO to my entity class updates don't work correctly because every time new collection is assigned instead of updating the existing one. I will see if I can port your plugin to EF Core and check if this helps.

**Comment by chaowlert** [comment]
EF doesn't care about new collection, EF tracks object by object references. The way plugin works is, it will find objects from DbContext every time we refer to Entity objects.

Plugin will translate

```csharp
var poco = dto.BuildAdapter()
              .CreateEntityFromContext(dbContext)
              .AdaptToType<Domain>();
```

into

```csharp
var entity = dbContext.Set<Domain>().Find(poco.Id);
poco.Adapt(entity);  // copy primitive & complex types only
var ref1 = dbContext.Set<RefDomain>().Find(poco.Ref.Id) ?? new RefDomain();
entity.Ref = poco.Ref.Adapt(ref1);  // copy primitive & complex types only
foreach (var nav in poco.Children) {
    var child = dbContext.Set<ChildDomain>().Find(nav.Id) ?? new ChildDomain();
    nav.Adapt(child);
    entity.Children.Add(child);
}
```

Plugin checks entity type and find Id column from EF meta data. I already used this plugins in production. It should work fine with object with multiple references and children. However I don't have chance to update to .NET Core & EF Core. It would be good if you can port plugin into EF Core.

**Comment by Thorgard** [comment]
What is Mapster.EF6.db for? 

https://github.com/MapsterMapper/Mapster.EF6/blob/5e9dd4c9f39316755f2c6725474517f3add928a5/src/Mapster.EF6/TypeAdapterBuilderExtensions.cs#L31-L33

**Comment by Thorgard** [comment]
@chaowlert so what `CreateEntityFromContext` actually does is just `return set.Find(src.id) ?? new T();`. `CreateEntityFromContext` would seem redundant if it's just it.

**Comment by chaowlert** [comment]
From your example, `CreateEntityFromContext` will generate 2 instantiate methods, `createOrder` and `createProduct`.

```
Order createOrder(OrderDTO src) {
    var db = (DbContext)MapContext.Current.Parameters[DB_KEY];
    var set = db.Set<Order>();
    return set.Find(src.Id) ?? new Order();
}

Product createProduct(ProductDTO src) {
    var db = (DbContext)MapContext.Current.Parameters[DB_KEY];
    var set = db.Set<Product>();
    return set.Find(src.Id) ?? new Product();
}
```

And Mapster will generate `orderDto.Adapt(order)` into something like

```
var order = createOrder(orderDto);
order.Id = orderDto.Id;
...
var list = new List<Product>();
foreach (var prodDto in orderDto.Products) {
    var prod = createProduct(prodDto);
    prod.Id = prodDto.Id;
    ...
    list.Add(prod);
}
order.Products = list;
```

**Comment by Thorgard** [comment]
I ported your plugin to EF Core but it works only with updates and inserts, it doesn't detect that items are deleted from the collection.

```csharp
public static TypeAdapterBuilder<TSource> CreateEntityFromContext<TSource>(this TypeAdapterBuilder<TSource> builder, DbContext context)
{
    const string dbKey = "Mapster.EFCore.db";
    return builder
        .AddParameters(dbKey, context)
        .ForkConfig(config =>
        {
            foreach (var entityType in context.Model.GetEntityTypes())
            {
                var type = entityType.ClrType;
                var keys = entityType.FindPrimaryKey().Properties.Select(p => p.Name).ToArray();
                var settings = config.When((srcType, destType, mapType) => destType == type);
                settings.Settings.ConstructUsingFactory = arg =>
                {
                    //var db = (DbContext)MapContext.Current.Parameters[DB_KEY];
                    //var set = db.Set<T>();
                    //return set.Find(src.id) ?? new T();
                    var src = Expression.Parameter(arg.SourceType);
                    var db = Expression.Variable(typeof(DbContext), "db");
                    var set = Expression.Variable(typeof(DbSet<>).MakeGenericType(arg.DestinationType), "set");

                    var current = typeof(MapContext).GetProperty(nameof(MapContext.Current), BindingFlags.Static | BindingFlags.Public);
                    var indexer = typeof(Dictionary<string, object>).GetProperties().First(item => item.GetIndexParameters().Length > 0);
                    var dbAssign = Expression.Assign(
                        db,
                        Expression.Convert(
                            Expression.Property(
                                Expression.Property(
                                    Expression.Property(null, current),
                                    nameof(MapContext.Parameters)),
                                indexer,
                                Expression.Constant(dbKey)),
                            typeof(DbContext)));

                    var setMethod = (from method in typeof(DbContext).GetMethods()
                                     where method.Name == nameof(DbContext.Set) &&
                                           method.IsGenericMethod
                                     select method).First().MakeGenericMethod(arg.DestinationType);
                    var setAssign = Expression.Assign(set, Expression.Call(db, setMethod));

                    var getters = keys.Select(key => arg.DestinationType.GetProperty(key))
                        .Select(prop => new PropertyModel(prop))
                        .Select(model => arg.Settings.ValueAccessingStrategies
                            .Select(s => s(src, model, arg))
                            .FirstOrDefault(exp => exp != null))
                        .Where(exp => exp != null)
                        .Select(exp => Expression.Convert(exp, typeof(object)))
                        .ToArray();
                    if (getters.Length != keys.Length)
                        throw new InvalidOperationException($"Cannot get key for sourceType={arg.SourceType.Name}, destinationType={arg.DestinationType.Name}");
                    var ret = Expression.Coalesce(
                        Expression.Call(set, nameof(DbContext.Find), null, Expression.NewArrayInit(typeof(object), getters)),
                        Expression.New(arg.DestinationType));
                    return Expression.Lambda(
                        Expression.Block(new[] { db, set }, dbAssign, setAssign, ret),
                        src);
                };
            }
        }, context.GetType().FullName);
}
```

**Comment by chaowlert** [comment]
I have no information now. But I do not need have code to delete the items not in list. I will try to dig what I had done this weekend.

**Comment by chaowlert** [comment]
For fluent configuration, you can configure with `WillCascadeOnDelete` (https://msdn.microsoft.com/en-us/data/jj591620.aspx#CascadeDelete).

For zero configuration, if your child object's primary key is composite key, and one of the key is navigation property to the parent. When you remove item from parent, child object will automatically remove.

For example

```
public class Order {
    public string Id { get; set; }
    ...
    public ICollection<OrderItem> Items { get; set; }
}
public class OrderItem {
    [Key, Column(Order = 0)]
    public string OrderId { get; set; }

    [Key, Column(Order = 1)]
    public string ItemId { get; set; }

    public Order Order { get; set; }
    ...
}
```

PS. I never try fluent config, I used composite keys for child items.

**Comment by chaowlert** [comment]
You also need to load object (with children) once, to make original entities loaded into context. Therefore, when you save change, EF will know which object needed to remove.

```
db.DomainPoco.Include("Children").Where(item => item.Id == dto.Id).FirstOrDefault();
var poco = dto.BuildAdapter()
              .CreateEntityFromContext(db)
              .AdaptToType<DomainPoco>();
```

**Comment by Thorgard** [comment]
@chaowlert the problem is `db.DomainPoco.Include` returns `IQueryable` and I would have to use what `Include` gives me. I think `Include` should be a part of the extension `CreateEntityFromContext`

**Comment by chaowlert** [comment]
> Invoking `Include` alone without using the result it gives has no effect and `CreateEntityFromContext` gives you entity with empty child collections.

By invoking `db.DomainPoco.Include("Children").Where(item => item.Id == dto.Id).FirstOrDefault()`, there is side effect. EF will load domain together with children into local store. And next time, when we use `Find`. We will get domain object together with children.

> I think Include should be a part of the extension CreateEntityFromContext

This is not easy, we need to deal with recursive, mapping, ignore, and should be a lot more issues. I don't think we should go to that point yet.

My recommendation, if you would like to use async, and would like to using result from `Include`, you can use this command.

```
var poco = await db.DomainPoco.Include("Children").Where(item => item.Id == dto.Id).FirstOrDefaultAsync();
dto.BuildAdapter()
              .CreateEntityFromContext(db)
              .AdaptTo(poco);
```

**Comment by Thorgard** [comment]
@chaowlert pretty hackish, I didn't know about that side effect. Does it work with EF Core too? I will try and let you know.

**Comment by OsamaAbuSitta** [comment]
> Yes, default behavior, Mapster will create new list every time. Mapster doesn't support mapping by id of item in collection.
> 
> If your purpose is to map from DTO to Data Domain class (and if you use EF6), I have plugin for this (https://github.com/MapsterMapper/Mapster/wiki/EF6).

this link does't work
