### ISSUE TITLE
TypeAdapterConfig is ignored in a derived class

### ISSUE THREAD

**Issue by shawty** [MapsterMapper/Mapster#154]
For anyone reading this after it was closed, this is NOT A BUG, see the reply's below... it was me not reading the doc's properly :-)

-----------------------------------------------------------------
I'm trying to use Mapster in the following scenario, but the mappings that I create in the classes derived from my base class, seem to get ignored.

My base class is a generic class used to get a database model and map it to a view model.

This class is defined as follows:

    public class GenericCrud<viewT, dbT> where dbT : DbEntityBase
    {
      internal readonly DataContext _db;

      public GenericCrud(DataContext db)
      {
        _db = db;

        // Mapster Configuration
        // The following two rules will serilize a string array to a token delimited string and back again
        TypeAdapterConfig<string, string[]>.NewConfig().MapWith(str => str.Split(',', StringSplitOptions.None));
        TypeAdapterConfig<string[], string>.NewConfig().MapWith(str => String.Join(',', str));

        // The following two rules will serilize an IEnumerable<int> to a token delimited string and back again
        TypeAdapterConfig<string, int[]>.NewConfig().MapWith(str => str.ConvertToIntArray()); // Use string extension method
        TypeAdapterConfig<int[], string>.NewConfig().MapWith(ienum => String.Join(',', ienum));

        // The following 2 rules, are there to prevent the encrypted password being read from the DB, while still
        // allowing it to be written, something we're prevented from doing if we use the attribute method of protecting it
        // from DB to VM no password will be passed, from VM to DB password will only be adapted if it's not null
        // IF RULES ARE DEFINED HERE FOR THE DERIVED TYPE THEY WORK
        TypeAdapterConfig<DbUser, User>.NewConfig().Ignore(o => o.Password);
        TypeAdapterConfig<User, DbUser>.NewConfig().IgnoreNullValues(true);
  
        ApplyCustomMappings();
      }

      public virtual void ApplyCustomMappings()
      {
        // Empty, designed to be overidden in the derived class should that class
        // need extra rules.
        // IF RULES ARE DEFINED HERE FOR THE DERIVED TYPE THEY WORK
      }

      // Generic crud methods follow here EG:
      internal IEnumerable<viewT> FetchEnumerableUsingPredicate(Expression<Func<dbT, bool>> predicate)
      {
        return _db.Set<dbT>().Where(predicate).ProjectToType<viewT>();
      }

      ....
    }

The base class is used by derived classes in the following manner:

    public class Users : GenericCrud<User, DbUser>
    {
      public Users(DataContext db) : base(db)
      {
      }

      public override void ApplyCustomMappings()
      {
        // IF RULES ARE DEFINED HERE FOR THE DERIVED TYPE THEY DO NOT WORK
        // THIS FUNCTION DOES GET CALLED FROM THE BASE AS EXPECTED HOWEVER
        // EG: The after mapping below, never get's called, but it does if I move it to the base
        TypeAdapterConfig<DbUser, User>.NewConfig()
              .AfterMapping((src, dest) => {
                dest.CultureDisplayName = GetCultureFromLanguageTag(src.CultureLanguageTag).DisplayName;
              });
      }

      public IEnumerable<User> GetAllUsers()
      {
        // Custom function
        return FetchEnumerableUsingPredicate(u => u.Roles.Contains("user"));
      }

      public User GetSingleLocalAdmin(int id)
      {
        // Custom function
        return FetchSinlgeUsingPredicate(u => u.Id == id && u.Roles.Contains("localadmin"));
      }

      public User Authenticate(AuthRequest authRequest)
      {
        // Custom function
        //.........
        return existingDbUser.Adapt<User>();
      }

      // Function used by the after mapping handler
      public CultureInfo GetCultureFromLanguageTag(string languageTag)
      {
        CultureInfo result = CultureInfo.GetCultures(CultureTypes.AllCultures).FirstOrDefault(c => c.IetfLanguageTag == languageTag);
        if (result == null)
        {
          throw new InvalidUserCultureException(languageTag);
        }
        return result;
       }
    }

As you can see I have an overridden function in the derived class, that is called from the constructor of the base class, when I do the '...:base(db)' call in the derived class.

Any mappings in the actual base constructor are obeyed, as are any created in the base members virtual function, the ones created in the overridden function however, are set up as the function is called into, but when an operation is then performed that uses mapster, the rule defined in the virtual override is ignored.

On top of that, previous to trying with a virtual, I tried just putting the maps specific to the derived class, directly into the derived classes ctor, after the call to the base ctor had been performed.  The result in this first case was also the same, the mappings defined in the derived class where ignored.

My question is, is this intentional, or is it a bug?

If it's intentional, do you have any advice on how I might achieve a scenario where I can define global maps that apply to every mapping type in the generic class, and maps specific to the derived types in the implementations of the derived classes.

Regards
Shawty

**Comment by chaowlert** [comment]
If you use `TypeAdapterConfig<DbUser, User>.NewConfig()` the setting will reset every time (https://github.com/MapsterMapper/Mapster/wiki/Configuration#setting-per-type-pair).

Please use `TypeAdapterConfig<DbUser, User>.ForType()`.

**Comment by shawty** [comment]
ah' gotcha.

So what your saying is that where I have the ignore bit in the base class ctor, that's effectively overwriting what's in the virtual function?

Ok, will try that, and let you know.

**Comment by shawty** [comment]
HI, so yep that was what I was doing wrong, thanks for the pointer. :-)

what I've done is removed the 2 rules I had in the base that where specific to the mapping, and put them all as one rule in the derived class now as those 3 rules are only need when going from DbUser->User and User->DbUser, and those interactions are only ever needed in the Users Service anyway.

I'm also going to look at retro fitting my Add/Update "Transformers" that I had in originally, because I think that Mapster can replace the functionality used there too.

Once again, thanks.

I see your still needing help with the DataReader, I see it every time I come here, and one of these days, I will find time to take a look at it :-)

You can close this issue if you wish too..

Cheers
Shawty
