### ISSUE TITLE
Benchmark with FastExpressionCompiler

### ISSUE THREAD

**Issue by dadhi** [MapsterMapper/Mapster#155]
Hello there,

I see from the [docs](https://github.com/MapsterMapper/Mapster/wiki/FastExpressionCompiler) that you'd suggest using FEC for performance improvements. Could you add the results with FEC to benchmark in the [home page](https://user-images.githubusercontent.com/5763993/45261206-11ca6080-b427-11e8-8ada-c9766148d810.png)?

**Comment by chaowlert** [comment]
Hi @dadhi, sorry for slow response.

First of all, thank you for your library!
Both FastExpressionCompiler and DryIoc, I'm fan of both libs.

For test result, class mapping with only primitives are quite fast (around 4x faster).
But class mapping with multiple children classes are a bit slower (not significant).
Overall mapping with mixed usages result in 1.3x faster.

I already updated README.md to show the result.

Thank you!

**Comment by dadhi** [comment]
Thanks for updating, 

I what version of FEC are you using?
Can I look into benchmarking code?

My ego expected faster results :)

**Comment by chaowlert** [comment]
I just push code to repo. I'm using v1.10.1.
My benchmark might not reflect best performance of FEC.
However, 1.3x - 4x is already huge gain.

**Comment by dadhi** [comment]
Ok, thanks for info :)

It would be interesting to use upcoming FEC 2.0 and LightExpression package.
