### ISSUE TITLE
Cannot convert immutable type, please consider using 'MapWith' method to create mapping

### ISSUE THREAD

**Issue by jjueche** [MapsterMapper/Mapster#156]
Hi,

I have this classes:

public class PointF
    {
        public float X { get; }
        public float Y { get; }
    }
public class RectangleF
    {
        public float Height { get; }
        public float Width { get; }
        public float X { get; }
        public float Y { get; }
        public float Left { get; }
        public float Right { get; }
        public float Top { get; }
        public float Bottom { get; }
        public PointF Location { get; }
    }
public class MapView
    {
        public string Name { get; set; }
        public RectangleF Viewport { get; set; }
    }
public class User
   {
       public int Id { get; set; }
       `public List<MapView> MapViews { get; set; }`
    }
public class MyUser
   {
       public int Id { get; set; }
       `public List<MapView> MapViews { get; set; }`
       public string myValue { get; set; }
    }

I have a list of Users with some objects in it:
`List<User> lstUser;`
And trying to map the list:
`var lstUserMapped = lstUser.Adapt<List<MyUser>>();`
 I am getting the error mesage "Cannot convert immutable type, please consider using 'MapWith' method to create mapping"

I tried this config settings:
TypeAdapterConfig.GlobalSettings.Default.PreserveReference(true);
TypeAdapterConfig.GlobalSettings.AllowImplicitDestinationInheritance = true;
TypeAdapterConfig<Geotab.Drawing.PointF, Clases.PointF>.NewConfig().PreserveReference(true);
TypeAdapterConfig<Geotab.Drawing.RectangleF, Clases.RectangleF>.NewConfig().PreserveReference(true);
            TypeAdapterConfig<Geotab.Checkmate.Settings.MapView, Clases.MapView>.NewConfig().PreserveReference(true);

What is wrong?

**Comment by jjueche** [comment]
the line: var lstUserMapped = lstUser.Adapt<List>(); is really var lstUserMapped = lstUser.Adapt<List<MyUser>>();

**Comment by chaowlert** [comment]
It seemed `PointF` & `RectangleF` have only getter, no setter.
