### ISSUE TITLE
Is it possible to map ExpandoObject or DynamicObject?

### ISSUE THREAD

**Issue by andre-f-paggi** [MapsterMapper/Mapster#158]
Is it possible to map ExpandoObject or DynamicObject?

**Comment by chaowlert** [comment]
not test yet, but ExpandoObject is dictionary. Mapster supports mapping dictionary with object.

**Comment by chaowlert** [comment]
tested. ExpandoObject works with Mapster.

**Comment by gmbeas** [comment]
how use? any example?
