### ISSUE TITLE
Any way to stop all mapping except some ?

### ISSUE THREAD

**Issue by 0Lucifer0** [MapsterMapper/Mapster#159]
Is there any way to return null for every mapping except 
if the srcType.Name == destType.Name+"Map" 
or List of srcType.Name ==  list of destType.Name+"Map"

**Comment by chaowlert** [comment]
I'm not fully understand, if you would like to map `Poco` to `PocoMap` and all others return null. This kind of mapping doesn't support fluently by Mapster (therefore no documentation). But you can do by following setting.

            var settings = TypeAdapterConfig.GlobalSettings
                .When((srcType, destType, mapType) => srcType.Name != destType.Name + "Map");
            settings.Settings.ConverterFactory = arg =>
            {
                var p1 = Expression.Parameter(arg.SourceType);
                var p2 = Expression.Parameter(arg.DestinationType);
                return Expression.Lambda(Expression.Constant(null), p1, p2);
            };

If you would like to map `Poco.Name` to `Dto.NameMap`, you can use [Naming Convention](https://github.com/MapsterMapper/Mapster/wiki/Naming-convention#prefix--replace)

```
TypeAdapterConfig<Poco, Dto>.NewConfig()
    .NameMatchingStrategy(NameMatchingStrategy.ConvertSourceMemberName(name => name + "Map"));
```

**Comment by 0Lucifer0** [comment]
I basicly want to do dto mapping but only this. Anything else should return null. I don’t want someone to use mapster to map something else. Will see to use those. Thank you

**Comment by chaowlert** [comment]
if you want to allow only explicit list of mapping, you could also using this https://github.com/MapsterMapper/Mapster/wiki/Config-validation-&-compilation#explicit-mapping

**Comment by 0Lucifer0** [comment]
Ok thank you will look at this. It seems to cover my use case
