### ISSUE TITLE
Mapping Collections Issue

### ISSUE THREAD

**Issue by joselicht90** [MapsterMapper/Mapster#162]
Hi, my name is José, i've been working with automapper and i wan't to replace it with mapster. I've encounter a problem. I'm trying to map a collection to another, we have base classes for entitys and dto. I have a List<BaseEntity> and List<BaseDto>. I can get the concrete type of both, like List<Person> and List<PersonDto>, but when i try to do TypeAdapter.Adapt(listEntity, listTypeOrigin, listTypeDestiny) i get an error: The delegate 'System.Func<System.Collections.Generic.List<Person>,System.Collections.Generic.List<PersonDto>>' has some invalid arguments.

Any idea why this happen?

**Comment by chaowlert** [comment]
Could you please provide reproducible code?

**Comment by chaowlert** [comment]
close due to no response
