### ISSUE TITLE
Null int[] values are not getting mapped

### ISSUE THREAD

**Issue by smandli** [MapsterMapper/Mapster#164]
Even though the mapping doesn't include IgnoreNullValues(true), and the mapping in TypeAdapterConfig.GlobalSetting rules has IgnoreNullValues as NULL, when the source int[] property is NULL, it doesn't overwrite the destination property.

**Comment by chaowlert** [comment]
Hi this can reproduce, I will create the fixed shortly. Thank you for the bugs.

**Comment by chaowlert** [comment]
Just create the fix ver 3.3.1, pls retest.

**Comment by smandli** [comment]
It works now. Thanks!
