### ISSUE TITLE
Add Mapster to awesome-dotnet

### ISSUE THREAD

**Issue by xsoheilalizadeh** [MapsterMapper/Mapster#168]
Good job, I've added our mapper to [dotnet-awesome](https://github.com/quozd/awesome-dotnet) with this [PR](https://github.com/quozd/awesome-dotnet/pull/757)

**Comment by chaowlert** [comment]
thank you!

**Comment by devSoheilAlizadeh** [comment]
Congratulate it has merged 🥳 
Please prepare a table for feature comparison against other mappers and fix them step by step.
