### ISSUE TITLE
Shallow Map/Adapt

### ISSUE THREAD

**Issue by KitsKlip** [MapsterMapper/Mapster#171]
Is there a way to Adapt source but without mapping navigation properties?
Example:
`class Department
{
   int Id{get;set}
   string Name{get;set;}
}

class Project
{
   int Id{get;set}
   string Name{get;set;}
   int DepartmentId {get;set;}
   Department Department {get;set;}
}`

What  Iwould like is to have something like:
`var result = projectEntity.ShallowAdapt<Project>();`

where the result would be:
`result.Department is null and result.Department & result.Name has the correct values`

Is this already possible?

**Comment by chaowlert** [comment]
please see https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members.

If you have attribute on navigation properties, then you can use `IgnoreAttributes`.
Otherwise, you can use `IgnoreMember`, and ignore type from certain namespace.

**Comment by KitsKlip** [comment]
No, that is not what we nee. We want to do a proper (deep) map sometimes and other times a shallow. And we are trying to use it in a generic way. So we ideally want to say adapter.Adapt and adapter.ShallowAdapt in other case. Without having to specify config (Attributes wont't work as it will make the effect permanent)

But thanks for the response

**Comment by chaowlert** [comment]
Then you should use 2 config. One for shallow, the other for deep.

https://github.com/MapsterMapper/Mapster/wiki/Config-instance
