### ISSUE TITLE
Reverse mapping

### ISSUE THREAD

**Issue by bettimms** [MapsterMapper/Mapster#173]
How to do reverse mapping when registering the mapping. Does it have such concept like AutoMapper?!

**Comment by chaowlert** [comment]
Net yet, I plan to work on this feature in next release.

**Comment by Alirezanet** [comment]
this is the only reason i didn't switched to mapster yet so +1

**Comment by chaowlert** [comment]
released

**Comment by 1483523635** [comment]
where I can found in the wiki? how to use this?

**Comment by chaowlert** [comment]
https://github.com/MapsterMapper/Mapster/wiki/Two-ways

**Comment by 1483523635** [comment]
Thanks

**Comment by Gildedter** [comment]
> https://github.com/MapsterMapper/Mapster/wiki/Two-ways

Is this configurable with `ICodeGenerationRegister`? For source generation
