### ISSUE TITLE
Posibility to merge Ignore mapping rules?

### ISSUE THREAD

**Issue by bdaniel7** [MapsterMapper/Mapster#175]
Is there a way to combine (Or add) new Ignore mapping rules?
Like config.IgnoreNullValues(true)
&& config.IgnoreIf (src == DateTime.MinValue)

There are situations when DateTime properties are initialized with default, like DateTime.MinValue, which is not a valid SQL DateTime value.

**Comment by chaowlert** [comment]
No, Mapster can't ignore default value. I think we should make DTO nullable, if it was integer then we cannot know user input 0 or not input.
