### ISSUE TITLE
Ignore all complex data.

### ISSUE THREAD

**Issue by Tolitech** [MapsterMapper/Mapster#177]
Hello.

Is there a clean way to ignore collections of complex objects and complex objects keeping only primitive data, enums, string, for all objects?

As my constructors are all "protected", I get errors in complex mappings.
In this case, I would like to do something more elegant than:
`var validTypes = new Type [] {typeof (int), typeof (string), ..........}; TypeAdapterConfig.GlobalSettings.Default.IgnoreMember ((member, side) =>! ValidTypes.Contains (member.Type));`

The error is:
InvalidOperationException: Can not instantiate type: Entity

Thanks.

**Comment by chaowlert** [comment]
Mapster cannot create object if you not provide public constructor.

If your DTO has setters, you should provide 1 public empty constructor. Mapster will create object and set all properties. 

If your DTO has no setter, you should provide exactly 1 public constructor, which parameters match all properties. And Mapster will inject values to that constructor.

**Comment by Tolitech** [comment]
Hello.
Thanks for the answer.

Yes, I know that a public constructor is needed in this case.
However, in DDD it is a good practice to only exist the constructor that will popularize the object and by the necessity of EF, we use a protected constructor (default).

Seeing this scenario above, I use the following code that works great:

```
public TestEntity(TestCommandInput input)
{
   input.Adapt(this);
   Validate();
}

```
However, as comented, complex objects and collections of complex objects return error because they have no public constructors.

What I really wanted was a clean way of being able to ignore all members of complex objects and collections of complex objects.

That is, when giving the command:
`input.Adapt(this);`

it popular only int, decimal, string, DateTime, ....

The only way I found so far would be to indicate all types and running the code below:
```
var validTypes = new Type[] { typeof(int), typeof(string) };
TypeAdapterConfig.GlobalSettings.Default.IgnoreMember((member, side) => !validTypes.Contains(member.Type));
```

I just wondered if there was any other cleaner way.


Thank you.

**Comment by chaowlert** [comment]
Oh sorry, I got your question. I plan to add MaxDepth in next release, this will also support mapping to complex properties.

For now, I can think of using namespace for example

`TypeAdapterConfig.GlobalSettings.Default.IgnoreMember((member, side) => member.Type.Namespace.StartsWith("System"));
`
or

`TypeAdapterConfig.GlobalSettings.Default.IgnoreMember((member, side) => !member.Type.Namespace.StartsWith("Your.Model.Namespace"));`

**Comment by Tolitech** [comment]
Great idea.
Thanks.
