### ISSUE TITLE
Doubt about performance and thanks.

### ISSUE THREAD

**Issue by Tolitech** [MapsterMapper/Mapster#179]
First of all, congratulations on the excellent project.
It worked perfectly for me in every detail.

In my DDD project it will be used in two important moments.
Upon receiving a command input it should populate an entity object. It worked perfectly by ignoring the collections and complex objects with the following code:

```
TypeAdapterConfig.GlobalSettings.When((srcType, destType, mapType) => mapType != MapType.Projection).IgnoreMember((member, side) => !member.Type.Namespace.StartsWith("System"));

TypeAdapterConfig.GlobalSettings.When((srcType, destType, mapType) => mapType != MapType.Projection).IgnoreMember((member, side) => member.Type.Namespace.StartsWith("System.Collection"));
```

The second step would be when using EF Core, to hydrate the command outputs.
It worked beautifully, avoiding that I do the manual mapping and mainly using the query correctly, without bringing all the columns. Great!

Code:
```
return await _context.Entity.AsNoTracking()
		.OrderBy(x => x.Column)
                .Include(x => x.Entities)
                .ProjectToType<EntityCommandOutput>()
                // .Select(EntitySpec.CommandOutput) NO MORE!
                .ToListAsync();
```

Currently I am rebuilding my code generator (https://www.codegenerator.com.br/ for .NET Core, Angular, PWA, Mobile projects) and trying to encode the best possible solution in all layers (for performance, security, maintenance, etc).

Today I use the specification pattern, it works very well in this process, but with Mapster I will save on generated lines of code and facilitate code maintenance (with ProjectToType).

The question is about performance.
I found in the documentation about FastExpressionCompiler.
Why exactly is it a library and is not by default embedded in the code?

Thanks again and congratulations for the project.

**Comment by chaowlert** [comment]
Quote from `FastExpressionCompiler`

> Expression.Compile creates a DynamicMethod and associates it with an anonymous assembly to run it in a sand-boxed environment. This makes it safe for a dynamic method to be emitted and executed by partially trusted code but adds some run-time overhead.

My understanding is FEC, uses IL emitting API to create dynamic method.

I didn't make `FastExpressionCompiler` as default compiler because
1. I don't want to have dependency.
2. Expression.Compile is already fast enough.
3. FEC might have bugs.

PS. I saw your codegenerator project. Nice work & well craft! So thank you for selecting Mapster.
