### ISSUE TITLE
Multiple source types

### ISSUE THREAD

**Issue by nhaberl** [MapsterMapper/Mapster#180]
Is there support to map from many source types? 
Let's say when having multiple data objects to put into one business object

**Comment by chaowlert** [comment]
Can you give example?

I can think of mapping twice or use AfterMapping.

    var dto = new Dto();
    src1.Adapt(dto);
    src2.Adapt(dto);

**Comment by nhaberl** [comment]
```
TypeAdapterConfig<TSource1, TSource2, TDestination>
        .NewConfig()
        .Ignore(dest => dest.Age)
        .Map(dest => dest.FullName, src1 => string.Format("{0} {1}", src1.FirstName, src1.LastName))
        .Map(dest => dest.Gender, src2 => string.Format("{0} {1}", src2.MaleOrFemale))
```

and reagrding Adapt() you would have to switch the objects

TDestination destObject = new TDestination();
destObject.Adapt(srcObject1, srcObject2, ...);

It's just an idea because I often would use thios when working with MicroORMs and you have a couple of lookup tables or map several business objects into 1 dto for example.

**Comment by chaowlert** [comment]
Interesting idea.

But before jump to new feature, how about using Tuple?

    TypeAdapterConfig<Tuple<TSource1, TSource2>, TDestination>
        .NewConfig()
        .Ignore(dest => dest.Age)
        .Map(dest => dest.FullName, src => string.Format("{0} {1}", src.Item1.FirstName, src.Item1.LastName))
        .Map(dest => dest.Gender, src => src.Item2.MaleOrFemale));

Then on mapping

    Tuple.Create(src1, src2).Adapt<TDestination>();

**Comment by aminelss** [comment]
@chaowlert your code works but we must map all fields manually
are there other solution?
ty

**Comment by chaowlert** [comment]
Mapster 5.0 now support multiple sources https://github.com/MapsterMapper/Mapster/wiki/Custom-mapping#multiple-sources

**Comment by PatrickBateman91** [comment]
@chaowlert How do you call Adapt method with two sources?
