### ISSUE TITLE
System.ArgumentException: 'Allow only member access (eg. obj => obj.Child.Name) Parameter name: lambda'

### ISSUE THREAD

**Issue by zavada-sergey** [MapsterMapper/Mapster#182]
I have two models: Position and PositionDTO.
```c#
    public class Position
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public uint RowVersion { get; set; }
    }

    public class PositionDTO
    {
        public string HashId { get; set; }
        public string Name { get; set; }
        public uint RowVersion { get; set; }
    }
```
When I try to configure TypeAdapterConfig I get the following exception

> System.ArgumentException: 'Allow only member access (eg. obj => obj.Child.Name) Parameter name: lambda'

Here is my source code

```c#
internal class Program
{
        private static void Main(string[] args)
        {
            var configuration = new HashIdConfiguration();

            TypeAdapterConfig<Position, PositionDTO>
                .NewConfig()
                .Map(x => x.HashId, c => configuration.EncryptLong(c.Id))
                .TwoWays()
                .Map(x => configuration.DecryptLong(x.HashId), c => c.Id);

            var model = new Position { Id = 1, Name = "Test", RowVersion = 10 };

            var dto = model.Adapt<PositionDTO>();
            var position = dto.Adapt<Position>();

            Console.ReadKey();
        }
}
```
How can I fix this?

**Comment by chaowlert** [comment]
Mapster doesn't know how to set configuration.DecryptLong(x.HashId). First parameter must always be property access, not method call.

You need to split config.

    TypeAdapterConfig<Position, PositionDTO>
                .NewConfig()
                .Map(x => x.HashId, c => configuration.EncryptLong(c.Id));

    TypeAdapterConfig<PositionDTO, Position>
                .NewConfig()
                .Map(c => c.Id, x => configuration.DecryptLong(x.HashId));
