### ISSUE TITLE
How to map DbDataReader to IEnumerable<T>

### ISSUE THREAD

**Issue by samchenws** [MapsterMapper/Mapster#183]
hello,i want to map DbDataReader to  IEnumerable<T>
like Mapper.Map<IDataReader, IEnumerable<T>>(reader);
Is there a similar method?

**Comment by chaowlert** [comment]
No support for data reader. For data access, I would recommend Dapper.

**Comment by samchenws** [comment]
> No support for data reader. For data access, I would recommend Dapper.

oh,support datatable?

**Comment by samchenws** [comment]
> No support for data reader. For data access, I would recommend Dapper.

I Use Sql in EFCore，So I Want to map  DbDataReader to IEnumerable or map  datatable to IEnumerable

**Comment by chaowlert** [comment]
Sorry, Mapster also not support DataTable. However, I would like to understand more. Why not you use EF to convert to class directly. Why you need to use DataReader & DataTable before converting to class?

**Comment by samchenws** [comment]
thanks
