### ISSUE TITLE
Large datasource slow performance

### ISSUE THREAD

**Issue by joselicht90** [MapsterMapper/Mapster#185]
Hi there guys, i'm having some performance issues. I have this configuration:

TypeAdapterConfig<ConstanciaDeRetencion, DetalleCabeceraLiquidacionDTO>
            .NewConfig()
            .IgnoreNonMapped(true)
            .Map(dest => dest.AaConstancia, src => src.AAConstancia)
            .Map(dest => dest.OConstancia, src => src.OConstancia);

I'm trying to map a IList<ConstanciaDeRetencion> to IList<DetalleCabeceraLiquidacionDTO>.
The sourcer has 5777 elements. The performance is way behind automapper on this particular mapping. On Global settings i set PreserveReference to True. Is there any config that could help me improve this? The source entity has some large map of properties but i dont know if that can affect this, cause i use ignore non mapped.

**Comment by chaowlert** [comment]
`PreserveReference` would kill performance. I suggest you to use [Mapster Debugger](https://github.com/MapsterMapper/Mapster/wiki/Debugging) to see how code is generated. If you don't need to track object reference, you can turn off `PreserveReference` on specific type pair by

```
TypeAdapterConfig<ConstanciaDeRetencion, DetalleCabeceraLiquidacionDTO>
    .NewConfig()
    .PreserveReference(false)
    .IgnoreNonMapped(true)
    .Map(dest => dest.AaConstancia, src => src.AAConstancia)
    .Map(dest => dest.OConstancia, src => src.OConstancia);
```

For performance problem, do you also turn on `PreserveReference` on AutoMapper? If yes, please help sharing your data models, so I can inspect why mapping is slow in your case.

**Comment by chaowlert** [comment]
One more thing, please also try using this setting

```
TypeAdapterConfig<string, string>
    .NewConfig()
    .PreserveReference(false);
```

Next release, I will omit reference checking for string.

**Comment by joselicht90** [comment]
I tried withouth preserve reference and it improved a bit but still way slower than automapper. Like 20sec vs 7 sec. What i did was change the fluent mapping of ConstanciaDeRetencion, so it has only what i need in this scenario and perfomance improved a lot. I'll share data model later so you can see them.

**Comment by joselicht90** [comment]
Here it is, the class diagram involving ConstanciaDeRetencion
[https://imgur.com/DKg6JFV](url)

**Comment by chaowlert** [comment]
I cannot reproduce your case. My test is running fine, it took 0 sec for 10,000 records for both `PreserveReference` turn on or off.

Here is code generation for no `PreserveReference`.

```csharp
return p1 == null ? null : new DetalleCabeceraLiquidacionDTO()
    {
        AaConstancia = p1.AAConstancia,
        OConstancia = p1.OConstancia
    };
```

And here with `PreserveReference`.

```csharp
    if (p1 == null)
    {
        return null;
    }
    MapContextScope scope = new MapContextScope();
    
    try
    {
        object cache;
        
        Dictionary<object, object> references = scope.Context.References;
        
        if (references.TryGetValue(p1, out cache))
        {
            return (DetalleCabeceraLiquidacionDTO)cache;
        }
        DetalleCabeceraLiquidacionDTO result = new DetalleCabeceraLiquidacionDTO();
        references[(object)p1] = (object)result;
        
        result.AaConstancia = p1.AAConstancia;
        result.OConstancia = p1.OConstancia;
        return result;
    }
    finally
    {
        scope.Dispose();
    }
```
Everything looked normal to me, I think problem might be related to data access, because mapping wouldn't take like 7 or 20 seconds.

Could you please separate issue first?, try loading data to list, then make mapping.
