### ISSUE TITLE
ShouldMapMember.IgnoreAdaptIgnore does not work as it should

### ISSUE THREAD

**Issue by gimadrislamov** [MapsterMapper/Mapster#186]
Because he return (bool?)false instead of (bool?)true when checking condition model.HasCustomAttribute(typeof(AdaptIgnoreAttribute))

**Comment by chaowlert** [comment]
Sorry could you give more info. What is actual, what is expected, and how to reproduce.

**Comment by gimadrislamov** [comment]
I have some models with properties marked by AdaptIgnoreAttribute. In some cases i need map all properties and try ignore AdaptIgnoreAttribute with ShouldMapMember.IgnoreAdaptIgnore in configuration:
`TypeAdapterConfig<Model1, Model2>.NewConfig().Settings
.ShouldMapMember.Add(ShouldMapMember.IgnoreAdaptIgnore);`
but this config continues ignore properties marked by AdaptIgnoreAttribute.

in Mapster repo i found ShouldMapMember.IgnoreAdaptIgnore 
`public static readonly Func<IMemberModel, MemberSide, bool?> IgnoreAdaptIgnore = (model, _) => model.HasCustomAttribute(typeof(AdaptIgnoreAttribute)) ? (bool?)false : null;
`
and change my config to 
`TypeAdapterConfig<Model1, Model2>.NewConfig().Settings
.ShouldMapMember.Add(IgnoreAdaptIgnore);

IgnoreAdaptIgnore = (model, _) => model.HasCustomAttribute(typeof(AdaptIgnoreAttribute)) ? (bool?)true : null;`

in this implementation all properties mapped as expected

**Comment by chaowlert** [comment]
Sorry, if name is mislead. `ShouldMapMember.IgnoreAdaptIgnore` is only for ignore attribute. 

You can also include attribute by using `TypeAdapterConfig<Model1, Model2>.NewConfig().IncludeAttribute(typeof(AdaptIgnoreAttribute))`.

**Comment by gimadrislamov** [comment]
Yes, i'm use ShouldMapMember.IgnoreAdaptIgnore for ignoring AdaptIgnoreAttribute for custom configuration, but this setting does't working and ignored properties doesn't mapped

**Comment by chaowlert** [comment]
Sorry, I'm not get what you describe. Mapster use `ShouldMapMember.IgnoreAdaptIgnore` internally to ignore `AdaptIgnoreAttribute` and it works correctly as I also used it in production.

By default, Mapster will always ignore `AdaptIgnoreAttribute`. If you would like to include attribute for some mapping and ignore attribute on the other mapping. I suggest you to create your own attribute to make it less confuse. And you can ignore that attribute by `config.IgnoreAttributes(typeof(YourAttribute))`.

**Comment by gimadrislamov** [comment]
OK, i'm understood this explanation. I think ignorring AdaptIgnoreAttribute by Mapster standard method would be nice. Because creation own attribute for setup his ignorring not obvious
