### ISSUE TITLE
config.Apply() requires list of registers to be in order if using .Inherits<>

### ISSUE THREAD

**Issue by mattbrailsford** [MapsterMapper/Mapster#187]
I'm using a DI container so I have all my `IRegister` implementations registered with the container. On load, I then request all the implementations from the container and call:

    TypeAdapterConfig.GlobalSettings.Apply(registers); 
    TypeAdapterConfig.GlobalSettings.Compile();

The list of registers appear to be returned from the DI container in alphabetical order.

The issue I have is that I have an entity base class and so I have a `EntityRegister` which contains mappings for the base class, then I also have derived class registers too where I have code like the following using `.Inherits<>`

    config.NewConfig<ICurrency, CurrencyBasicDto>()
         .Inherits<IEntity, EntityBasicDto>();

The problem is, because the DI returns the registers in alphabetical order, the `EntityRegister` is "applied" after the `CurrencyRegister` and so the base class mappings aren't being applied.

The only way I can currently get this to work at all is to use `TypeAdapterConfig.GlobalSettings.AllowImplicitDestinationInheritance = true;` which I'd prefer to be more explicit.

Is it possible to have it such that when applying registers it is able to work out these cross references without needing for them to be loaded in order?

**Comment by chaowlert** [comment]
This is not really `Mapster` topic. It is how you manage your dependencies. Some DI libraries support assigning order of injected list. Or you can define your dependency in your register class.

```
class CurrencyRegister : IRegister {
    EntityRegister _entityRegister;
    public CurrencyRegister(EntityRegister entityRegister) {
        _entityRegister = entityRegister
    }

    public void Register(TypeAdapterConfig config) {
        config.Apply(_entityRegister);
        config.NewConfig<ICurrency, CurrencyBasicDto>()
            .Inherits<IEntity, EntityBasicDto>();
    }
}
```

**Comment by mattbrailsford** [comment]
Ahh, cool. That makes sense.

In the later example, is there no issue with multiple derived entity registers all calling apply with the same base entity register?

**Comment by chaowlert** [comment]
> Ahh, cool. That makes sense.
> 
> In the later example, is there no issue with multiple derived entity registers all calling apply with the same base entity register?

You can add your own flag to ensure call is applied only once, however setting multiple times should not be problems. 

`config.NewConfig<IEntity, EntityBasicDto>()` will reset setting for `IEntity` & `EntityBasicDto` type pair. So if there are multiple calls to this setting, it just set and clean and set again.
