### ISSUE TITLE
Projection does not support circular reference.

### ISSUE THREAD

**Issue by Tolitech** [MapsterMapper/Mapster#189]
In a simple scenario using **EF Core** and **many to many**, how can you use **ProjectToType** without getting InvalidOperationException: Projection does not support circular reference.

Example:
UserEntity
RoleEntity

For **EF Core**, you must have:
UserInRoleEntity (Role and User references)

When running:

```
return await _context.User.AsNoTracking ()
     .Where (x => x.UserId == userId)
     .Include (x => x.UsersInRoles)
                     .ThenInclude (x => x.Role)
     .ProjectToType <UserQueryResult> ()
     .SingleOrDefaultAsync ();

```
the exception is thrown.

Thanks.

**Comment by Tolitech** [comment]
ok, I got it with some extra changes and settings:

My **UserQueryResult** and **RoleQueryResult** now have `ICollection<RoleQueryResult>` and `ICollection<UserQueryResult>` respectively instead of `ICollection<UserInRoleQueryResult>`.

and it was necessary to include the following extra codes:

```
TypeAdapterConfig <UserEntity, UserQueryResult>
                 .NewConfig ()
                 .Map (dest => dest.Roles, src => src.UsersInRoles);

```
and

```
             TypeAdapterConfig <RoleEntity, RoleQueryResult>
                 .NewConfig ()
                 .Map (dest => dest.Users, src => src.UsersInRoles);
```

Is there another way without having to make the above changes?

**Comment by Tolitech** [comment]
However, regarding the above code, how can I map a list of UserInRole (with Role and User) to a Role list?
How to access the Role object inside UserInRole?

```
TypeAdapterConfig <UserEntity, UserQueryResult>
                 .NewConfig ()
                 .Map (dest => dest.Roles, src => src.UsersInRoles.{Role});
```

**Comment by chaowlert** [comment]
> However, regarding the above code, how can I map a list of UserInRole (with Role and User) to a Role list?
> How to access the Role object inside UserInRole?
> 
> ```
> TypeAdapterConfig <UserEntity, UserQueryResult>
>                  .NewConfig ()
>                  .Map (dest => dest.Roles, src => src.UsersInRoles.{Role});
> ```

```
TypeAdapterConfig<UserEntity, UserQueryResult>
                 .NewConfig()
                 .Map(dest => dest.Roles, src => src.UsersInRoles.Select(it => it.Role));
```

**Comment by chaowlert** [comment]
For circular reference in projection, it is not possible as it's also not possible in linq query.

There are 3 ways to solve circular references in projection problem.
1. Don't make circular references in your DTO models.
2. Use [MaxDepth](https://github.com/MapsterMapper/Mapster/wiki/Object-references#maxdepth)
3. Dump everything to object, then `Adapt` using [PreserveReference](https://github.com/MapsterMapper/Mapster/wiki/Object-references#preserve-reference-preventing-circular-reference-stackoverflow).

**Comment by Tolitech** [comment]
Thank you, @chaowlert.
My DTOs (QueryResult) really have no circular reference.

Anyway, I prefer the first solution by removing the object (UserInRole) and holding only the User -> Role instead of the User -> UserInRole -> Role required by EF Core.

It's working here.

Thank you.
