### ISSUE TITLE
Suggestion: Unflattening could work for readonly properties

### ISSUE THREAD

**Issue by satano** [MapsterMapper/Mapster#192]
[Unflattening](https://github.com/MapsterMapper/Mapster/issues/163) is a really great feature. Thanks for it. 👍 

It would be even greater, if it could work with readonly properties. We have these classes:

``` csharp
public class ContractingParty
{
    public string Name { get; set; }
    public string Company { get; set; }
}

public class Invoice
{
    public long Id { get; set; }
    public string DocumentNumber { get; set; }
    public ContractingParty Supplier { get; set; }
}

public class InvoiceDto
{
    public long Id { get; set; }
    public string DocumentNumber { get; set; }
    public string SupplierName { get; set; }
    public string SupplierCompany { get; set; }
}
```

If we `Adapt` from `InvoiceDto` to `Invoice`, everything works. Mapster creates a new instance of `ContractingParty` for `Supplier` property and fill its values.

But we would like to have `Supplier` property readonly to make sure, it is never null. And Mapster could just fill its properties without creating a new instance:

``` csharp
public class Invoice
{
    public long Id { get; set; }
    public string DocumentNumber { get; } = new ContractingParty();
    public ContractingParty Supplier { get; } = new ContractingParty();
}
```

Its probably not so easy, because I think that Mapster is just skipping readonly properties and so some effort should be made to consider them when unflattening is on. So I am writing this here really just as a suggestion. _(Mayby I will try to look at it myself later.)_

**Comment by chaowlert** [comment]
I can see use case for this. But for now how about just make setter internal or protected?

**Comment by satano** [comment]
Hmmm. I did not realize I can do this and Mapster will still work. Good tip for simple workaround. Thanks.

**Comment by chaowlert** [comment]
Mapster 5.0 now support readonly prop https://github.com/MapsterMapper/Mapster/wiki/Mapping-readonly-prop
