### ISSUE TITLE
[Error] Coalesce used with type that cannot be null

### ISSUE THREAD

**Issue by andreujuanc** [MapsterMapper/Mapster#195]
Hello, 

I've been searching for an alternative to AutoMapper and found this library which works very good and has a bunch of nice features. 

The only issue that I have (for now ;)) is the following:

``` C#
    class Program
    {
        class MyClassA 
        {
            public MyStruct MyStruct { get; set; }
        }
        class MyClassB
        {
            public MyStruct MyStruct { get; set; }
        }

        struct MyStruct
        {
            public MyStruct(string prop) : this()
            {
                Property = prop;
            }

            public string Property { get; set; }
        }
        static void Main(string[] args)
        {
            var a = new MyClassA();
            var b = new MyClassB();

            a.MyStruct = new MyStruct("A");

            a.Adapt(b);
        }
    }
```

Adapt throws

>  InvalidOperationException: Coalesce used with type that cannot be null

Maybe I'm just tired today, but shouldn't be structs configured properly out of the box? If not, what's the best way to globally ignore the assignment of the actual struct, and maybe continue with it's values (if that's even possible).

Cheers

**Comment by chaowlert** [comment]
It supposed to handle. I will try soon.

**Comment by chaowlert** [comment]
Thank you for bug report. This happen only mapping to existing struct. It fixed in 4.1.

**Comment by andreujuanc** [comment]
Happy it helped. Sorry did not PR the fix. Haven't mess with the source code too much yet.
Thanks a lot for the fix. :)

**Comment by andreujuanc** [comment]
Updated my project and works perfectly! Thanks!!
