### ISSUE TITLE
error CS0009: Metadata file `Mapster.dll` does not contain valid metadata

### ISSUE THREAD

**Issue by nielsenko** [MapsterMapper/Mapster#197]
When trying to use code gen, I get the following error, when processing the template
```
Running generator 'TextTemplatingFileGenerator' on file '/.../MyMapper.tt'...
error CS0009: Metadata file `.../bin/Debug/netstandard2.0/Mapster.dll' does not contain valid metadata
```
I can see the `Mapster.dll` is copied fine to the target dir, so it is not because it is missing.

Do you have an idea what can be the issue?

I'm using Visual Studio Professional 2019 for Mac (Preview) - Version 8.2 Preview (8.2 build 872).

**Comment by nielsenko** [comment]
If I remove the "Mapster.dll" from the template, ie. remove the lines
```
<#@ Assembly Name="$(TargetDir)/Mapster.dll" #>
...
<#@ import namespace="Mapster" #30 
```
Then I can get past the error, but then obviously I cannot invoke any Mapster code.

**Comment by chaowlert** [comment]
I never got this problem. Please try reset project dependencies, clean & rebuild.

**Comment by chaowlert** [comment]
Closing, this issue should not related to Mapster.
