### ISSUE TITLE
Property set to `null` with Mapster v4 (and later)

### ISSUE THREAD

**Issue by ramondeklein** [MapsterMapper/Mapster#199]
We have a problem where Mapster touches the `Client` property of the destination object, despite that there is no mapping for it. This is the source object:
```
    public class RdpConnectionInputModel : ClientModelBase
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string RemoteHostname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RdpType { get; set; }
        public int RemotePort { get; set; }
        public bool IsAdmin { get; set; }
        public bool Synchronize { get; set; }
        public PermissionsDto Permissions { get; set; }
        public Guid ClientId { get; set; }
        public string ClientName { get; set; }
        public Guid HardwareId { get; set; }

        public string ClientDisplayName => ClientName ?? HardwareId.ToString();
    }
```
The destination object is an EF class that looks like this:
```
    [Table("SVC_RdpConnections")]
    public class DbSvcRdpConnections
    {
        public Guid Id { get; set; }
        [ForeignKey(nameof(Client_Ref))] public virtual DbRimClient Client { get; set; }
        public Guid? Client_Ref { get; set; }
        [ForeignKey(nameof(System_Ref))] public virtual DbSecSystem System { get; set; }
        public Guid? System_Ref { get; set; }
        [ForeignKey(nameof(Company_Ref))]
        public virtual DbSecCompany Company { get; set; }
        public Guid? Company_Ref { get; set; }
        public CompanyFlags CompanyFlags { get; set; }
        [Required, StringLength(100)] public string Name { get; set; }
        [StringLength(250)] public string Comment { get; set; }
        [StringLength(50)] public string RemoteHostname { get; set; }
        public int RemotePort { get; set; }
        [StringLength(50)] public string Username { get; set; }
        [StringLength(50)] public string Password { get; set; }
        public DesktopConnection RdpType { get; set; }
        public string EncryptedPassword { get; set; }
        public bool IsAdmin { get; set; }
        public bool Synchronize { get; set; }
        public DateTime? LastSynchronized { get; set; }
    }
```
The mapping is configured like this:
```
            config.ForType<RdpConnectionInputModel, DbSvcRdpConnections>()
                .Map(i => i.Client_Ref, i => i.ClientId)
                .Map(i => i.RdpType, i => (DesktopConnection)i.RdpType)
                .Map(i => i.EncryptedPassword, i => i.Password, i => i.Password != null)
                .AfterMapping((src, dest) =>
                {
                    dest.CompanyFlags = DefaultMappingProfile.PermissionsToCompanyFlagsConverter.Convert(src.Permissions);
                    dest.Comment = CommentFormatter.Format(dest.Comment);
                });
```
When the user updates the record in the user interface, then we fetch the existing entity from the database (`DbSvcRdpConnections`). The `Client` property holds a proxy object that is used for lazy loading. The database entity is updated by calling the following method:
```
   config.GetMapToTargetFunction<RdpConnectionInputModel, DbSvcRdpConnections>().Invoke(inputRdpEntity, dbRdpEntity);
```
With Mapster v3.2 it would leave the `Client` property alone, but with Mapster v4.0 (and later) it resets the `Client` property to `null`. Because this property is now dirty, it also resets the `Client_Ref` to `null` when I try to access the entity's state.

I have tried to create a reproducable scenario in a seperate project, but I didn't succeed. Is there some specific functionality for EF objects or am I missing something else. I couldn't find a commit between v3.2 and v4.0 that might be related. But Mapster is rather complex code, so I probably overlooked something. Do you know what could cause this issue? We now use a workaround to fix the Mapster version v3.2, but I would rather use v4.1...

**Comment by chaowlert** [comment]
There is [unflattening](https://github.com/MapsterMapper/Mapster/wiki/Two-ways#unflattening) feature, but you need to turn on, and it should create new object rather than setting to null. I just test with my unit test, `Client` should not be null even unflattening turn on or off.

Try [debugging](https://github.com/MapsterMapper/Mapster/wiki/Debugging#get-mapping-script) using `src.BuildAdapter().CreateMapToTargetExpression<DbSvcRdpConnections>().ToScript()` to see how Mapster generate code. It might show you some hint.

**Comment by ramondeklein** [comment]
Thanks for your prompt response. I will look into this issue again on Thursday when I am back at work.
