### ISSUE TITLE
Question: exist easy way for ignoring null value when custom mapping is used?

### ISSUE THREAD

**Issue by Burgyn** [MapsterMapper/Mapster#201]
Hi,
We have three levels of classes depth. Something like:
```CSharp
public class Invoice
{
    public string Code { get; set; }

    public Supplier Supplier { get; set; }
}

public class Supplier
{
    public string Name { get; set; }

    public Address Address { get; set; }
}

public class Address
{
    public string City { get; set; }
}
```

and we want adapt into flattened class `InvoiceFlat`:
```CSharp
public class InvoiceFlat
{
    public string Code { get; set; }
    public string SupplierName { get; set; }
    public string SupplierCity { get; set; }
}
```

We use configuration for non-standard mapping of `invoice.Supplier.Address.City` to `invoiceFlat.SupplierCity` 

```CSharp
TypeAdapterConfig<Invoice, InvoiceFlat>
                .NewConfig()
                .IgnoreIf((src, dest) => src.Supplier == null || src.Supplier.Address == null, dest => dest.SupplierCity)
                .Map(dest => dest.SupplierCity, src => src.Supplier.Address.City);
```

`.IgnoreIf((src, dest) => src.Supplier == null || src.Supplier.Address == null, dest => dest.SupplierCity)` is used because `Supplier` and `Supplier.Address` can be `null` in source.

## Question is:

Are there more elegant solutions for skipping `null` value properties when using this type of mapping? Without `IgnoreIf` because there is a lot of code in many places for.

Thanks.

**Comment by chaowlert** [comment]
There is no method to handle both Map and Ignore in one step.
How about using `AfterMapping`?

    TypeAdapterConfig<Invoice, InvoiceFlat>
                .NewConfig()
                .AfterMapping((src, dest) => {
                    if (src.Supplier?.Address != null)
                        dest.SupplierCity = src.Supplier.Address.City;
                });

**Comment by Burgyn** [comment]
Hi,
thanks. I'll try it out.
