### ISSUE TITLE
Question: Is mapping configuration same for <dest, src> and <List<dest>, List<src>> ?

### ISSUE THREAD

**Issue by sekulicb** [MapsterMapper/Mapster#208]
Hi. Let's say I have TypeAdapterConfig set for POCO and DTO.

TypeAdapterConfig<POCO, DTO>
                .NewConfig()
                .IgnoreNullValues(true)
                .Map(dest => dest.Property, src => src.Property>())
                .Map( etc....)

Now, in some cases I need to map exactly same types but instead working with single instances, I need to map from collection to collection. 

TypeAdapterConfig<List< POCO >, List< DTO >>
                .NewConfig()
                .IgnoreNullValues(true)
                .Map( etc....)

Will TypeAdapterConfig reuse mapping config already set for single values and apply it for each item or I need to have both mapping configurations defined ?

**Comment by chaowlert** [comment]
You need only mapping between Poco & Dto

**Comment by sekulicb** [comment]
Cool. Thank you for prompt response
