### ISSUE TITLE
Suggestion: include property for auto-flattening

### ISSUE THREAD

**Issue by gbjbaanb** [MapsterMapper/Mapster#210]
Some of my objects I'm mapping go from a flat POCO to a DTO that contains a sub-object. eg

class DTOSub {
  string Extras;
}
class DTO {
  string Name;
  DTOSub Details;
}

classs POCO {
  string Name;
  string Extras;
}

and quite often I'd like to map the DTO to POCO without specifying flattening and twoways and other configuration. Is it possible to have something like an .Include(DTOSub) method to tell Mapster to treat the DTO+DTOSub as one class without having to decorate the sub-objects name in the POCO class, or configure flattening and/or twoways.

**Comment by chaowlert** [comment]
Mapster 5.0 now support DTO+DTOSub map to POCO https://github.com/MapsterMapper/Mapster/wiki/Custom-mapping#multiple-sources
