### ISSUE TITLE
Exception when Map string to datetime with ignore null true.

### ISSUE THREAD

**Issue by allanegidio** [MapsterMapper/Mapster#211]
Hi
When i map my string null to a DateTime? nullable with IgnoreNullValues(true) i receive Exception. 
`{"String '' was not recognized as a valid DateTime."}`
Exists any other way?
Thanks

**Comment by chaowlert** [comment]
Hi I tested with my test case it pass successfully both normal Map and Map to target object. Can you provide unit test?

        public class DestClass
        {
            public DateTime? Date { get; set; }
        }

        public class SourceClass
        {
            public string Date { get; set; }
        }

        [TestMethod]
        public void Map()
        {
            TypeAdapterConfig.GlobalSettings.NewConfig<SourceClass, DestClass>()
                .IgnoreNullValues(true)
                .Compile();

            var source = new SourceClass();
            var dest = source.Adapt<DestClass>();

            Assert.IsNull(dest.Date);
        }

**Comment by allanegidio** [comment]
Hello
The error occurs when I get an empty string.
I created a way to not receive this empty string and now everything is ok.
Maybe I confused the concept of empty string being different from null string.
Thanks for the answer
