### ISSUE TITLE
How to ignore all non existing members in mapster?

### ISSUE THREAD

**Issue by idotnetdev** [MapsterMapper/Mapster#212]
Hi,
I have two class want to mapping.
My base class is this:
```
public class MyModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string StatusId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
    }
```

and View model is:
```
public class MyModelViewModel
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string StatusId { get; set; }
        public string FullName { get; set; }
    }
```

I want to map any members that has same name automatically map to other such as (Id, StatusId) and ignore all non existing member on MyModelViewModel such as (CreatedBy, CreatedOn).
When I use IgnoreNonMapped(true) that ignores all members that not mapped manually by .Map().

This is my config and on the result all members except FullName is null.
`
Mapster.TypeAdapterConfig<MyModel, MyModelViewModel>
                .NewConfig()
                .Map(dest => dest.FullName, x => x.Name + " " + x.Family)
                .IgnoreNonMapped(true);
`.

Can you add IgnoreAllNonExisting method to the source?
That is exist on Automapper with [this link](https://github.com/AutoMapper/AutoMapper/issues/1386).

**Comment by chaowlert** [comment]
Hi sorry, I don't quite understand. 

If you mean, you wouldn't like to map other props except id, statusId, and mapping from `Map` function, you need no config. Mapster will ignore those unmapped props.
