### ISSUE TITLE
same type erro

### ISSUE THREAD

**Issue by bao2314483** [MapsterMapper/Mapster#213]
Error while compiling
source=NetTopologySuite.Geometries.Point
destination=NetTopologySuite.Geometries.Point
type=Map

nuget Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite

NetTopologySuite.Geometries.Point=>NetTopologySuite.Geometries.Point

.Map(dest => dest.MapCoordinates, src => NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326).CreatePoint(new Coordinate(src.MapCoordinates.Lng, src.MapCoordinates.Lat)));

why?

**Comment by chaowlert** [comment]
Data type is not support. If data type is not primitive, Mapster will presume type is POCO. And if type is not POCO, there will be error while mapping.

This can be fixed by custom mapping. https://github.com/MapsterMapper/Mapster/wiki/Custom-conversion-logic

```
TypeAdapterConfig<Point,Point>.NewConfig()
   .MapWith(point => point);
```

**Comment by bao2314483** [comment]
thanks
