### ISSUE TITLE
object Circular reference

### ISSUE THREAD

**Issue by bao2314483** [MapsterMapper/Mapster#214]
`
public class BusGoodsSourceResult
    {
        public List<BusGoodsSourceOfferResult> Offer { get; set; }
    }
public class BusGoodsSourceOfferResult
    {
        public BusGoodsSourceResult GoodsSource { get; set; }
    }
`
Circular reference error

How to deal with

**Comment by chaowlert** [comment]
https://github.com/MapsterMapper/Mapster/wiki/Object-references
