### ISSUE TITLE
object property is null

### ISSUE THREAD

**Issue by bao2314483** [MapsterMapper/Mapster#215]
TypeAdapterConfig<OrderPayments, OrderPaymentsResult>.NewConfig()
                .Map(dest => dest.OrderNo, src => src.TranOrder == null ? "" : src.TranOrder.OrderNo);

How to set global null handling?
automapper Default support

I want to go through the global settings
TypeAdapterConfig<OrderPayments, OrderPaymentsResult>.NewConfig()
                .Map(dest => dest.OrderNo, src =>src.TranOrder.OrderNo);

**Comment by chaowlert** [comment]
null propagation is not support. Your config is ok

```
TypeAdapterConfig<OrderPayments, OrderPaymentsResult>.NewConfig()
    .Map(dest => dest.OrderNo, src => src.TranOrder == null ? "" : src.TranOrder.OrderNo);
```

**Comment by chaowlert** [comment]
Mapster 5.0 now support auto null propagation https://github.com/MapsterMapper/Mapster/wiki/Custom-mapping#null-propagation
