### ISSUE TITLE
MapToTargetWith is Ignored or not working in certain cases

### ISSUE THREAD

**Issue by bud4buddies** [MapsterMapper/Mapster#222]
When using MapToTargetWith for a custom type, I am getting expected results only when an instance is supplied to Adapt and rest of the time it is getting ignored. Attached code illustrate the pass & fail situations

static void Main()
{

TypeAdapterConfig<int, intCode>.NewConfig().MapToTargetWith((x, y) => y.Value == x ? y : new intCode(x))

TypeAdapterConfig<Foo, Bar>.NewConfig()

 TypeAdapterConfig.GlobalSettings.Compile();

 var from= new Foo { Key = 100 };

var passed = TypeAdapter.Adapt<Foo, Bar>(from, new Bar()); // working as expected.

var failed= TypeAdapter.Adapt<Foo, Bar>(from); // not working and a default structure is initialized.
}

public class Foo
{
      public int Key {get; set;}
}

public class Bar
{
    public intCode Key {get; set;}
}

public struct intCode
{
        public int Value { get; set; }
        public string Name { get; set; }
        public intCode(int val)
                :this(val, null)  { }
        public intCode(int val, string name)
        {
            Value = val; Name = name;
        }
}

**Comment by chaowlert** [comment]
`MapToTargetWith` applied only mapping to existing object. If you would like to map to new object use `MapWith`.
