### ISSUE TITLE
MapWith: Cannot use expression with a body!

### ISSUE THREAD

**Issue by ckarcz** [MapsterMapper/Mapster#223]
The MapWith API is very useful to map a simple dumb DTO to a domain object that requires a constructor call. BUT, we cannot write this up outside of a single line lambda! It's extremely limiting for some more advanced situations.

Would it be possible to extend this API to allow lambdas with bodies and method groups etc? Or do you happen to have a work around in order to handle more complex target object initialization?

----

See the following:

```
config.ForType<FirmDto, Firm>()
      .Map(dest => dest.Id, src => src.Id)
      .Map(dest => dest.Name, src => src.Name)
      .Map(dest => dest.Code, src => src.Code)
      .Map(dest => dest.Description, src => src.Description)
      .Map(dest => dest.Website, src => src.Website)
      .MapWith(src =>
      {
          var website = src.Website != null ? new Uri(src.Website) : null;
          return new Firm(src.Id, src.Name, src.Description, website, src.Code);
      });
```

Gives error:

```Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0834	A lambda expression with a statement body cannot be converted to an expression tree	Caissa.Api.Rest	....................\sources\xxxx.Api.Rest\V1\Firms\Mappings\FirmDtoMappings.cs	30	Active
```

Where as this is fine:

```
config.ForType<FirmDto, Firm>()
      .Map(dest => dest.Id, src => src.Id)
      .Map(dest => dest.Name, src => src.Name)
      .Map(dest => dest.Code, src => src.Code)
      .Map(dest => dest.Description, src => src.Description)
      .Map(dest => dest.Website, src => src.Website)
      .MapWith(src => new Firm(src.Id, src.Name, src.Description, src.Website != null ? new Uri(src.Website) : null, src.Code));
```

FYI, I know that the property mapping above is pointless when using a constructor, but I am also using Mapster to link **property names** of Dtos to Domain objects To Data Models (since they can vary). This is useful for pagination where you need to sort by a prop.

**Comment by chaowlert** [comment]
1. I understand your pain, however, the reason that it need to be expression because, Mapster also need to support query expression and code generation. For this, if you really want to have multi line lambda, you can pass function to expression ex. `src => CreateFirm(src)`.

2. In case you not know, Mapster can map to constructor, if `Firm` has only one constructor, you not need `MapWith`, otherwise, you can use [`MapToConstructor`](https://github.com/MapsterMapper/Mapster/wiki/Constructor-mapping).

3. You can map `string` and `Uri` by `config.ForType<string, Uri>().MapWith(src => new Uri(src))`, and not need to manually map everywhere.

4. I wonder how you do sort by prop? Recommended way is using OData, where you don't need to mess with linking property name. You can select, filter, orderby and paging by using dto, all operation will be mapped to query expression and operate in db.

**Comment by ckarcz** [comment]
@chaowlert 

Hi, regarding your points:

1. I must have only tired a local private function which was not allowed. I will use a normal method this if needed.

2-3. I know of these APIs.

4. OData is nice but I believe (when I used it last) it is used with Entity object directly. In this application we are working with a rich domain that we cannot leak, so we use DTOs, and have separate data layer models to decouple from a messy database schema. What I do is take the string prop name of the source object and use Mapster as a property-to-property registry using the configs to resolve the target property name. Then I can create an Expression to use in sorting with LINQ (or IQueryable if wanting to append an ORDER BY clause to SQL etc). That was my issue figuring this out in Issue #216 . I just need to make it work with nested properties, given a property path like string "rootProperty.propertyInner". :)

**Comment by chaowlert** [comment]
For OData, you can use `ProjectToType` to cast from entity to dto. Then client doesn't need to touch to any entity models. It also supports inner properties. If you use type that EF not support (ex. `Uri`), you need converter.

Another way, I can think of if you would like to get property mappings, you can use [builder](https://github.com/MapsterMapper/Mapster/wiki/Mappers#builder), and use `CreateProjectionExpression `. From expression, the body should be class initializer where source properties map to dto properties. Nested properties will be nested class initializer.
