### ISSUE TITLE
Mapping must be called using ServiceAdapter

### ISSUE THREAD

**Issue by sonsy-soft** [MapsterMapper/Mapster#224]
when I want to use MapContext.Current.GetService<IMyService>() in my mapping 
I get the error
Mapping must be called using ServiceAdapter
?
```

public class RegisteredCharityConfig : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            config
                .NewConfig<CharityAccount,RegisteredCharityDto>()
                .PreserveReference(true)
                .AddDestinationTransform((string x) => x.Trim())
                .Map(dest => dest.ImageUrl, src => MapContext.Current.GetService<IUrlUtility>().GetUrlDirectoryMinified(DirectoryKind.Charity, src.Id) )
                ;
         }
    }
```

**Comment by chaowlert** [comment]
How you do mapping? You must configure and inject `IMapper`

see usage here https://github.com/MapsterMapper/Mapster/wiki/Dependency-Injection#mapping

see example here https://github.com/MapsterMapper/Mapster/tree/master/src/Sample.AspNetCore

**Comment by sonsy-soft** [comment]
thanks chaowlert 
what about scan ?
how should be priority of calling if i want to use scan?
becuase i dont want to write every mapping in GetConfiguredMappingConfig() at sample code
i would like to use scan for scan assembly

**Comment by chaowlert** [comment]
Instead of `GetConfiguredMappingConfig()` method that you mentioned, you can made `config.Scan` call.

**Comment by sonsy-soft** [comment]
for last question if we use DI  then cant use ProjectToType  for mapping ?
it doesnt work does it?
we must using IMapper , is right?

**Comment by chaowlert** [comment]
Can  `linq.ProjectToType<Dto>(mapper.Config)`

**Comment by sonsy-soft** [comment]
Hi chaowlert 
I get the same error after calling the scan method in code.
here is my Code

```
            var Config = GetConfiguration();
            Services.AddSingleton(Config);
            Services.AddScoped<IMapper, ServiceMapper>();
            Config.Scan(assemblies);
```
more informatino i use autofac for DI in .net core 3.1
