### ISSUE TITLE
AdaptMember confuses me

### ISSUE THREAD

**Issue by bdaniel7** [MapsterMapper/Mapster#226]
> With AdaptMember attribute, you can specify name of source or target to be mapped. For example, if we would like to map Id to Code
```
public class Product {
    [AdaptMember("Code")]
    public string Id { get; set; }
    public string Name { get; set; }
}
```
This behavior is very confusing. If I have a dto with property Code and an entity with property Id, and want to map entity to dto, I should use ```[AdaptMember("Id")]``` or ```[AdaptMember("Code")]```?

Maybe you should add 2 parameters, as for AdaptIgnore: source property name, destination property name. Or by convention use it just for the source. If the attribute is not found, it should look at the property name itself.

I have the following situation:
```
public class Measure
{
	public NomenclatureVersion NomenclatureVersion {}
}

public class NomenclatureVersion
{
	public string NomenclatureCode {}
}

public class MeasureDto
{
	[AdaptMember("NomenclatureVersionNomenclatureCode")]
	public string NomenclatureVersionCode {}
}

public class MeasureForListDto
{
	[AdaptMember("NomenclatureVersionNomenclatureCode")]
	public string NomenclatureVersionCode {}
}
```

I want to map Measure -> MeasureDto -> MeasureForListDto (yes, I'm lazy)
And the second mapping doesn't work, I assume because the library uses the AdaptMember attribute and tries to find a property called ```NomenclatureVersionNomenclatureCode```.

I'm using Mapster 4.1.0.

**Comment by chaowlert** [comment]
I wrote unit test using your classes, it seemed working correctly. (Tested with v4.1.0 and current version)

```csharp
var poco = new Measure
{
    NomenclatureVersion = new NomenclatureVersion {NomenclatureCode = "foo"}
};
var dto = poco.Adapt<MeasureDto>();
dto.NomenclatureVersionCode.ShouldBe(poco.NomenclatureVersion.NomenclatureCode);

var dto2 = dto.Adapt<MeasureForListDto>();
dto2.NomenclatureVersionCode.ShouldBe(dto.NomenclatureVersionCode);

```
