### ISSUE TITLE
Mapster returning null for Collections instead of empty collection

### ISSUE THREAD

**Issue by hann4n** [MapsterMapper/Mapster#227]
I recently migrated to Mapster from Automapper. 
We have a huge application and applied mapster and it looks good. 
But we are facing an issue that When collections are mapped they are returning as null instead of empty collection when source object property is null. 

Is there any workaround or feature so that we can have Empty collection instead of null just like Automapper.

Thanks

**Comment by chaowlert** [comment]
You can use `AddDestinationTransform`.

```csharp
TypeAdapterConfig.GlobalSettings.Default
    .AddDestinationTransform((IReadOnlyList<ChildDto> list) => list ?? new List<ChildDto>());
```

Problem is you need to list all target types to handle null.

I think Mapster need to support this in future version.

**Comment by chaowlert** [comment]
Added generic support for `AddDestinationTransform`.

```csharp
config.Default.AddDestinationTransform(DestinationTransform.EmptyCollectionIfNull);
```

**Comment by hann4n** [comment]
Thank you very much. This is great

**Comment by hann4n** [comment]
@chaowlert  This is working great when Collections are a property of a class however when we map Collections directly its still returning null 

`var lst3 = mapster.Map<List<CA2>>(lst);` returns `null`

Here I have tried using both `config.Default.AddDestinationTransform((List<CA2> list) => list ?? new List<CA2>());`  and `config.Default.AddDestinationTransform(DestinationTransform.EmptyCollectionIfNull);`
