### ISSUE TITLE
AfterMapping is error,please help me

### ISSUE THREAD

**Issue by gudufy** [MapsterMapper/Mapster#228]
var menus = _MenuRepository.TableNoTracking.Include(x => x.Translations).ToList();

            TypeAdapterConfig<SysMenu, MenuDto>.ForType().AfterMapping((source, destination) =>
            {
                var translation = source.Translations.FirstOrDefault(pt => pt.Language == AppSession.Language);
                if (translation != null)
                {
                    destination = translation.Adapt(destination);
                    return;
                }

            });

error message:TypeAdapter.Adapt was already called, please clone or create new TypeAdapterConfig.

**Comment by chaowlert** [comment]
TypeAdapterConfig should set only once. https://github.com/MapsterMapper/Mapster/wiki/Config-location#entry-point
