### ISSUE TITLE
Mapping of Collections without Default Constructor not working

### ISSUE THREAD

**Issue by hann4n** [MapsterMapper/Mapster#229]
Recently we have shifted from Automapper to Mapster and facing another issue which was working fine with Automapper.

We have several classes with the following structure:

```
public class ErpProductPropertyTranslationDictionary
	{
		public ErpProductPropertyTranslationDictionary()
		{
		}
		public System.Collections.Generic.ICollection<ErpProductPropertyTranslation> ProductPropertiesAsList	{ get; set; }//;
		public System.Collections.Generic.IEqualityComparer<string> Comparer	{ get; set; }//;
		public int Count	{ get; set; }//;
		public System.Collections.Generic.Dictionary<string, ErpProductPropertyDictionary>.KeyCollection Keys	{ get; set; }//;
		public System.Collections.Generic.Dictionary<string, ErpProductPropertyDictionary>.ValueCollection Values	{ get; set; }//;
		public ErpProductPropertyDictionary Item	{ get; set; }//;
	}
```

When mapping `_mapster.Map<ErpProductPropertyTranslationDictionary,ErpProductPropertyTranslationDictionary>()`

It gives exception for Comparer, Keys and Values properties as they dont have default constructors. This was working fine with Automapper. Is there any way we can make this work?

Your help is highly appreciated. Thank you

**Comment by chaowlert** [comment]
Can you show your `ErpProductPropertyDictionary` constructors?

**Comment by hann4n** [comment]
```
public ErpProductPropertyDictionary()
		{
		}
```

**Comment by chaowlert** [comment]
Do you need deep copy? By default Mapster try to deep copy all types. Otherwise you can use [`ShallowCopyForSameType`](https://github.com/MapsterMapper/Mapster/wiki/Object-references#shallow-copy)
