### ISSUE TITLE
Question: how to conditionally map destination object to null

### ISSUE THREAD

**Issue by PieEatingNinjas** [MapsterMapper/Mapster#231]
Hi!
I was wondering if there is a backed-in way to conditionally map the destination object to null when a particular condition on the source object is met.

I've written a custom extension method to handle this now, but it doesn't feel right as my calling class that passes-in the predicate should not know when the destination object should be null. I would rather have this logic in my AdapterConfig.

```csharp
public static TDestination Adapt<TSource, TDestination>(this TSource source, TypeAdapterConfig config, Predicate<TSource> predicate)
{
    if (predicate?.Invoke(source) ?? true)
        return source.Adapt<TDestination>(config);
    return default;
}
```

How should these kinds of scenarios be handled? Maybe I'm missing some out-of-the-box functionality that is built for this?

Keep up the good work you guys are doing for this library!

**Comment by chaowlert** [comment]
Hi, this is not support

Mapster support only ignore some members conditionally (https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members#ignore-conditionally)

I think your extension method is good.

**Comment by PieEatingNinjas** [comment]
Thanks for your feedback!
