### ISSUE TITLE
I can't find to way out my nested classes and dtos mapping with Mapster.

### ISSUE THREAD

**Issue by bugrakosen** [MapsterMapper/Mapster#232]
I have some DTO classes in very complex relation as same as my Entity classes. 

**Here is my DTOs:**

![product](https://user-images.githubusercontent.com/32344242/77594624-0dca3a80-6f08-11ea-8237-9d72578054cb.PNG)

![product material using](https://user-images.githubusercontent.com/32344242/77594651-1ae72980-6f08-11ea-9d19-f1c5ae1cb653.PNG)

![material](https://user-images.githubusercontent.com/32344242/77594658-220e3780-6f08-11ea-8084-960f1691c0a8.PNG)

![Material stock](https://user-images.githubusercontent.com/32344242/77594666-25a1be80-6f08-11ea-8d2b-a695ed60c537.PNG)

 **IMapper :**

![Imapper](https://user-images.githubusercontent.com/32344242/77595255-bf1da000-6f09-11ea-9a6d-d0afed7202fb.PNG)

**Mapper:**

![Mapper](https://user-images.githubusercontent.com/32344242/77595272-cc3a8f00-6f09-11ea-83f5-180581afe406.PNG)

**Startup.cs:**

![startup](https://user-images.githubusercontent.com/32344242/77595301-dbb9d800-6f09-11ea-98fc-fb23c63d70c6.PNG)

**My Service:**

![service](https://user-images.githubusercontent.com/32344242/77595329-ebd1b780-6f09-11ea-912d-02912ff6a964.PNG)

**Result:**

![result](https://user-images.githubusercontent.com/32344242/77595341-f2f8c580-6f09-11ea-9d33-96324263157b.PNG)

I want to blue marked datas. I don't want to map red marked datas. Because i already have `product `and `productmaterialusing`.
I may have told a little badly, my English is not good enough. I'm sorry about that. Thanks for your helping!!

**Comment by chaowlert** [comment]
If you would like to skip some properties, use ignore. https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members
