### ISSUE TITLE
Include members from parent class

### ISSUE THREAD

**Issue by matipaulo** [MapsterMapper/Mapster#237]
Hi, I have a question about how to perform some kind of map, let me post you an example:

```
public class Parent<T>
{
 public T Item { get; set; }
 public AnotherClass AnotherItem { get; set; }
}

public class A 
{
 public int property1 { get; set; }
}

public class B : Parent<A>
{
 public int property2 { get; set; }
}

public class DTO
{
 public int property1 { get; set; }
 public int property2 { get; set; }
}
```

How should I configure the mapper in order to have mapped in `DTO` the properties from class `A` and `B`??

I tried with `Unflattening` without any succeed.

Thanks!

**Comment by chaowlert** [comment]
There are 3 options

1. Flattening/unflattening required property name to match with source path.

So you can change DTO to this.

```csharp
public class DTO {
  public int Item_property1 { get; set; }
  public int property2 { get; set; }
}
```

2. define mapping explicitly

```csharp
TypeAdapterConfig<B, DTO>.NewConfig()
    .Map(it => it.property1, it => it.Item.property1);
```

3. Or you can map everything from parent to DTO.

```csharp
TypeAdapterConfig<B, DTO>.NewConfig()
    .Map(it => it, it => it.Item);
```
