### ISSUE TITLE
AfterMapping is not being called after ProjectToType

### ISSUE THREAD

**Issue by sergeyovchinnikov** [MapsterMapper/Mapster#239]
Hello,

i'm stuck with the AfterMapping fuction right now.
The given Action will be called when i use the Adapt method, 
but not after ProjectToType Extension method.

Is that a bug or works as designed?

TypeAdapterConfig<Person, PersonDto>.NewConfig()
                .AfterMapping((src, dest) => dest.Name += "xxx");

// AfterMapping Action will be called.
            IList<PersonDto> allPersons =
                context.Person
                    .Adapt<List<PersonDto>>(Mapper.Config);

// AfterMapping Action will not be called.
            IList<PersonDto> allPersons =
                context.Person
                    .ProjectToType<PersonDto>(Mapper.Config)
                    .ToList();

Regards

Sergey

**Comment by chaowlert** [comment]
Sorry `AfterMapping` cannot use with `ProjectToType`. When using queryable, expression must be single expression in order to convert to sql statement. 

You can check method that support queryable here https://github.com/MapsterMapper/Mapster/wiki.
