### ISSUE TITLE
can I ignore dest propety which is not null or emptystring easily

### ISSUE THREAD

**Issue by yezi34880** [MapsterMapper/Mapster#242]
can I ignore dest propety which is not null or emptystring easily

**Comment by chaowlert** [comment]
To ignore globally, No.

You can ignore per property. https://github.com/MapsterMapper/Mapster/wiki/Ignoring-members#ignore-conditionally.

I will leave this issue open as feature request.

**Comment by yezi34880** [comment]
OK, I see.
I think is a  common request, and I can not use request, because the propety name is not šcertain,actually, if hava not  a globally function, in code , it will be hard code like 
class1.a = class1.a??class2.a;
not mapper

**Comment by chaowlert** [comment]
created new feature to apply mapping for a type pair. For example

```csharp
config.NewConfig<SimplePoco, SimpleDto>()
    .Fork(cfg =>
        cfg.ForType<string, string>()
            .MapToTargetWith((src, dest) => string.IsNullOrEmpty(src) ? dest : src));
```

To interpret above command, mapping `SimplePoco` to `SimpleDto`, for `string` to `string` mapping, we will check src string is empty first.
