### ISSUE TITLE
Mapping nested list of objects returning empty array

### ISSUE THREAD

**Issue by ZeroDarkThirty** [MapsterMapper/Mapster#250]
I have a Post and Tag class, with a many-to-many relationship in a PostTag link table.

```
public class Post
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    
        public List<PostTag> PostTag { get; set; }
    }
    
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set;  }
        public List<PostTag> PostTag { get; set; }
    }
    
    public class PostTag
    {
        public Guid PostId { get; set; }
        public Post Post { get; set; }
    
        public Guid TagId { get; set; }
        public Tag Tag { get; set; }
    }
```

I'm trying to create a custom mapping using Mapster, of PostDto as shown below:

 ```
   public class PostDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    
        public List<TagDto> Tags { get; set; }
    }
    
    public class TagDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

```
Here's the query I'm running to return all Posts:

```
    var posts = await _ctx.Posts
                            .Include(s => s.PostTags)
                            .ThenInclude(st => st.Tag)
                            .ToListAsync();
    
    return _mapper.Map<List<PostDto>>(posts); // _mapper is injected using IMapper
```

Custom mapping and DI in Startup.cs:

```
    var config = new TypeAdapterConfig();
    config.NewConfig<Post, PostDto>()
            .Map(dest => dest.Tags, src => src.PostTags.Adapt<TagDto>());
    
    services.AddSingleton(config);
    services.AddScoped<IMapper, ServiceMapper>();
```

The problem: The query always returns an empty array for Tags.

**Comment by chaowlert** [comment]
My guess is data type in mapping config is incorrect

```csharp
config.NewConfig<Post, PostDto>()
            .Map(dest => dest.Tags, src => src.PostTags.Adapt<TagDto>());
```

It should be

```csharp
config.NewConfig<Post, PostDto>()
            .Map(dest => dest.Tags, src => src.PostTags.Adapt<List<TagDto>>());
```

<hr/>

However, I would like to suggest few optimization

1. You don't need `Adapt` in mapping config.
Which will reduce to 

```csharp
config.NewConfig<Post, PostDto>()
            .Map(dest => dest.Tags, src => src.PostTags);
```

2. You can use `ProjectToType` instead of `Adapt`.

```csharp
return await _ctx.Posts
                            .ProjectToType< PostDto>(_mapper.Config)
                            .ToListAsync()
```

**Comment by JANA-mkalia** [comment]
What shall be done a situation when the names of the properties of the nested object is not matching. For example this case the property names were different for Tags and TagDto object.

**Comment by AbdallahNagy** [comment]
@chaowlert I think this won't work
```cs
config.NewConfig<Post, PostDto>()
    .Map(dest => dest.Tags, src => src.PostTags);
```
because PostTags is not the tags themselfs but the intermediate class
we could get the tags from the PostTags Class like this:
```cs
config.NewConfig<Post, PostDto>()
    .Map(dest => dest.Tags, src => src.PostTags.Select(pt => pt.Tag));
```

**Comment by Quanghuy128** [comment]
what's happened if PostTag has one more field? And I want to retrieve that field in PostTag.

**Comment by fafeoik** [comment]
@AbdallahNagy When i did this, my build just crashes with an error (0xc0000005) 'Access violation'.

**Comment by fafeoik** [comment]
This code worked for me tho. But i don't know if it's a perfect solution
`TypeAdapterConfig<List<AccountModel>, List<AccountWithResidentsDTO>>
    .NewConfig()
    .Map(dest => dest, src => src.Select(a => a.Adapt<AccountWithResidentsDTO>()));


TypeAdapterConfig<AccountModel, AccountWithResidentsDTO>
.NewConfig()
.Map(dest => dest.Residents, src => src.AccountResidents.Select(r => r.Resident));`
