### ISSUE TITLE
How To map string to object when using ProjectTo

### ISSUE THREAD

**Issue by maoxian-1** [MapsterMapper/Mapster#253]
I had install Mapster.JsonNet and try
```
TypeAdapterConfig<model, dto>
        .NewConfig()
        .Map(dest => dest.Pics, src => JsonConvert.DeserializeObject<string[]>(src.Pics));
```

but i got an error
```
System.InvalidOperationException: Client projection contains reference to constant expression of 'System.RuntimeType' which is being passed as argument to method 'ChangeType'.
```

**Comment by chaowlert** [comment]
I don't have detail so I can't debug, but this issue should related to EF cannot translate sql.
You cannot use method that EF not know (which could be `JsonConvert.DeserializeObject`).

I would suggest 2 ways to fix.

1. query model first and then cast to dto.

```csharp
context.Models.ToList().Adapt<List<Dto>>();
```

2. or you can use EF value converter.
- https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions
- https://github.com/Innofactor/EfCoreJsonValueConverter
