### ISSUE TITLE
Can't Adapt List to List at the version v6

### ISSUE THREAD

**Issue by bezzad** [MapsterMapper/Mapster#254]
Hi,
I use the Mapster v5.3 and I can to map any same list together. But after release the Mapster version 6, I decided to update my app package to v6 and now I see the list mapping doesn't work.  For example:

```
var notifications = new List<NotificationModel>();
unit.UserNotificationRepository.All.Adapt(notifications);

var count = notifications.Count; // now is 0 !?
```

**Comment by chaowlert** [comment]
There are bugs that related to mapping to existing list multiple times 
- Mapster 3.0, I just allowed mapping to existing list
- Mapster 4.0, there is bugs (https://github.com/MapsterMapper/Mapster/issues/209) so I turned off
- Mapster 5.0, I tried to fixed, but there are another bugs (https://github.com/MapsterMapper/Mapster/issues/247)
- So I removed mapping to existing list again in Mapster 6.0.

From your use case, there is still no strong use case to mapping to existing list. Please map to new object instead.

```csharp
var notifications = unit.UserNotificationRepository.All.Adapt<List<NotificationModel>>();
```

Let me know if you have different opinion.

**Comment by bezzad** [comment]
No problem, thanks.
