### ISSUE TITLE
SN Issue

### ISSUE THREAD

**Issue by mxmissile** [MapsterMapper/Mapster#257]
Getting this with nuget 6.1.0, had to roll back to 6.0.0

`Could not load file or assembly 'Mapster' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. `

**Comment by chaowlert** [comment]
I cannot reproduce, but I changed build machine for 6.1.0, this may cause issue.
I released 6.1.1 (together with some fixes) https://www.nuget.org/packages/Mapster/6.1.1
Could you please help validate, is 6.1.1 working?

**Comment by Bobetti** [comment]
6.1.1 - works great for me. 6.1.0 - gave - "Strong name signature not valid for this assembly Mapster.dll" in clickonce

**Comment by mxmissile** [comment]
Confirmed fixed, thanks!
