### ISSUE TITLE
[Q] define defaults to ignore all members with default value.

### ISSUE THREAD

**Issue by norvegec** [MapsterMapper/Mapster#259]
In addition to mapping features, I'd be happy to use this tool to _patch_ objects.
Typical use case: 

```csharp

Entity entity = CreateNewEntity();
Entity patch = GetAdditionalData(entity);
_mapper.Map(patch, entity);
```

Now, `patch` is partially initialized object of the same type. 
I would like to ignore members of the `patch` that has default values (particularly of type `Guid`, `int`, `double` and reference types). 
Ideally, I'd like not to define settings (especially, per entity type) at all.

This "request" is partially "addressed" ;) with such a convenient method `myMapperConfig.Default.IngoreNullValues(true)`.

In addition to that, is there something like `myMapperConfig.Default.IngoreIf((src, dst) => src == default)`?

**Comment by chaowlert** [comment]
I used to have similar use case, I solved it by having different DTO to patch (eg. `EntityPatch` class), and mark all properties nullable. I used code generator to transform all POCOs to patched DTOs to save time. I think using dictionary or json also could also work. Using the same `Entity` type, what would happen if 0 is real value to update?

However, for you question, `config.Default.IgnoreIf((src, dst) => src == default)` should be similar to this setting

```csharp
config.ForType<int, int>().MapToTargetWith((src, dest) => src == 0 ? dest : src);
config.ForType<double, double>().MapToTargetWith((src, dest) => src == 0 ? dest : src);
// so on
```

**Comment by norvegec** [comment]
Thx, I've just found this repo, still haven't read all the docs. You suggestion should work for me.
About default values - they are defaults in C# , not in our business domain AFAIK.
Having a separate DTO is for sure a better design (explicit intent). 
Sometimes,  dough, you need to GTD before cleaning the code base.
I'm quite new to this repo, code gen looks very interesting, definitely will have a look.
