### ISSUE TITLE
Proposal - ProjectToType as NonGeneric

### ISSUE THREAD

**Issue by JMPSequeira** [MapsterMapper/Mapster#260]
Hello,

IMHO it would add great value to your library if one could use `ProjectoToType` with the following:
```csharp
IEnumerable<object> result = someDbContext.SomeDbSet.ProjectToType(typeof(SomeProjectionType));
```
This is already possible with the Adapt method.

This would allow for, i.e., dynamic api requests mapped straight in the projection.

Let me know if you think this to be useful?

**Comment by chaowlert** [comment]
I think `IEnumerable<Poco>` can be assigned to `IEnumerable<object>` right?

If your type is dynamic, for now Mapster doesn't support your use case. The closest, you can call `config.CreateMapExpression` to create `LambdaExpression` and create query from there.

**Comment by JMPSequeira** [comment]
No dynamics, I expressed the idea poorly.

I meant projection to types unknown at design time in order to provide flexibility and segregation between the query and the projection.

The example was also expressed poorly :) 2 for 2 I'm on a roll.

Imagine a scenario where you have a web api that performs a query and the return result can be any of the possible projections for the type being queried, something like:

```csharp
public ActionResult Get(int projectionToken)
{
    Type projectionType = GetProjectionType(projectionToken);

    if(projectionType != null)
    {
        IEnumerable<object> result = someDbContext.SomeDbSet.ProjectToType(projectionType);

        return Ok(result);
    }
    return BadRequest();
}
```

If I understood correctly your idea would be:

```csharp
var config = new TypeAdapterConfig().NewConfig(typeof(Source), typeof(Destination));

var lambda = config.Config.CreateMapExpression(new TypeTuple(typeof(Source), typeof(Destination)), MapType.Projection);

var projection = someDbContext.SomeDbSet.AsQueryable().Provider.CreateQuery(lambda);

var result = projection.Cast<object>().ToList();
```

This is what I envision to be under the hood :)

**Comment by JMPSequeira** [comment]
@chaowlert 👍
