### ISSUE TITLE
Adapt does not include initialized auto properties.

### ISSUE THREAD

**Issue by atillabyte** [MapsterMapper/Mapster#261]
```csharp
    public class Character
    {
        public string Name { get; set; }
        public int Level { get; set; } = 1;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var character = new Dictionary<string, object>() { { "Name", "Alice" } }.Adapt<Character>();
        }
    }
```

When the property "Level" is not specified in the dictionary, I would expect it to be in the Character as it is public and an initialized automatic property. In this case, it should be set to 1 instead of 0, which is the default(int).

**Comment by chaowlert** [comment]
You need to add config `IgnoreNullValues`. No value will be treated as null, which map to 0.
