### ISSUE TITLE
IEnumerable is enumerating twice when adapted to array

### ISSUE THREAD

**Issue by DaniilPalii** [MapsterMapper/Mapster#272]
When adapting IEnumerable to an array, it's adapted twice.

Example of code:

```csharp
        static void Main(string[] args)
        {
            GetMyObjects().Adapt<MyObject[]>();

            Console.WriteLine(EnumerateTimes);
        }

        static IEnumerable<MyObject> GetMyObjects()
        {
            EnumerateTimes++;
            yield return new MyObject { SomeProperty = "A" };
            yield return new MyObject { SomeProperty = "B" };
        }

        static int EnumerateTimes = 0;
```

Result of executing: 2.
Expected result: 1.

Version: 6.5.0.

**Comment by DaniilPalii** [comment]
I assume that proper workaround for now is calling `ToList` before adapting:

```csharp
GetMyObjects().ToList().Adapt<MyObject[]>();

**Comment by chaowlert** [comment]
Thanks for reporting. Problem with array is we need to know array size before creating array, so it create extra enumerable access because enumerable has no `Count` method. I will check how to solve this problem.

**Comment by satano** [comment]
Possible solution is to create a `List<T>` and then call `ToArray()`. Of course, data (references in case of objects) are doubled.

**Comment by DaniilPalii** [comment]
Thank You!
