### ISSUE TITLE
.Net 5 support issue

### ISSUE THREAD

**Issue by zs-dima** [MapsterMapper/Mapster#275]
Error on generation model on .Net 5 core project:

`Error MSB3073 The command "dotnet mapster model -a C:\some.dll" exited with code -532462766`

**Comment by chaowlert** [comment]
let the framework exit RC version I will add support for 5.0.

**Comment by zs-dima** [comment]
.Net 5 marked as production redy and release going to be in a few weeks

**Comment by zs-dima** [comment]
@chaowlert 
.Net 5 release already there:
https://dotnet.microsoft.com/download/dotnet/5.0
>let the framework exit RC version I will add support for 5.0.

**Comment by chaowlert** [comment]
I just published Mapster.Tool V7.0.0 support NET5.0 pls try

**Comment by zs-dima** [comment]
@chaowlert
Mapster works well, thanks a lot for the fast fix!
