### ISSUE TITLE
2 Adapt's on one Class == errors in the generated code

### ISSUE THREAD

**Issue by zs-dima** [MapsterMapper/Mapster#276]
Sometime we having 2+ DTO objects versions at once - one for the full object information and other for the short information.

Currently we having error: 'CS0102 The type 'UserMapper' already contains a definition for 'ProjectToEntity'':

```C#
[GenerateMapper]
[AdaptTwoWays(typeof(Rpc.User))]
[AdaptTwoWays(typeof(Rpc.UserShortInfo))]
public partial class User { ... }
```

- here I mapping gRPC model with 'Mapster.Tool' - so I could not add any attribute to the 'Rpc.UserShortInfo' or 'Rpc.User' class as they are auto-generated by gRPC lib

**Comment by chaowlert** [comment]
Thank you for reporting. For now, interface mapper will let you define method name.

```csharp
[Mapper]
public interface IUserMapper
{
    Expression<Func<User, Rpc.User>> ProjectToRpcUser { get; }
    Expression<Func<User, Rpc.UserShortInfo>> ProjectToRpcUserShortInfo { get; }
}
```

**Comment by chaowlert** [comment]
Another ways, you can specify which MapType you want.

```csharp
[GenerateMapper]
[AdaptTwoWays(typeof(Rpc.User), MapType = MapType.Map | MapType.MapToTarget)]
[AdaptTwoWays(typeof(Rpc.UserShortInfo), MapType = MapType.Map | MapType.MapToTarget)]
public class User
{
...
}

```

**Comment by zs-dima** [comment]
Thanks a lot for answers

> 
> 
> Thank you for reporting. For now, interface mapper will let you define method name.
> 
> ```cs
> [Mapper]
> public interface IUserMapper
> {
>     Expression<Func<User, Rpc.User>> ProjectToRpcUser { get; }
>     Expression<Func<User, Rpc.UserShortInfo>> ProjectToRpcUserShortInfo { get; }
> }
> ```

It doesn't generate AdaptTo and TwoWays as well

**Comment by chaowlert** [comment]
Nah, it's the interface, you need to create method signature, and Mapster will generate implementation.

```csharp
[Mapper]
public interface ICustomerMapper
{
    //for queryable
    Expression<Func<Customer, CustomerDTO>> ProjectToDto { get; }
    
    //map from POCO to DTO
    CustomerDTO MapToDto(Customer customer);

    //map to existing object
    Customer MapToExisting(CustomerDTO dto, Customer customer);
}
```

**Comment by zs-dima** [comment]
Thanks, now I could see it could not replace AdaptTwoWays attribute as it does not generate extension methods to map objects + it is namespace errors for this case:

```C#
    [Mapper]
    public interface IUserMapper
    {
        //map to existing object
        Model.User MapToExisting1(Rpc.User dto, Model.User user);
        Rpc.User MapToExisting2(Model.User dto, Rpc.User user);
    }
```

**Comment by zs-dima** [comment]
Could be really nice if you will fix this issue or invent how to generate extension methods from interface.
Thanks in advance

**Comment by chaowlert** [comment]
Mapster.Tool V7.0.0 should fix the duplicated name, please try.

**Comment by zs-dima** [comment]
Thanks a lot for the fix
However methods names looks like: ProjectToUser2 and ProjectToInfo, however they are could be ProjectToUser and ProjectToUserInfo, but it is not really critical.
