### ISSUE TITLE
Mapster.Tool TwoWays Configuration doesn't work

### ISSUE THREAD

**Issue by zs-dima** [MapsterMapper/Mapster#277]
Mapster.Tool works with 'AdaptTwoWays' attribute, but it could be nice to describe Configuration for tool as well, specially for the EF objects.

Mapster.Tool TwoWays Configuration doesn't work currently:

```C#
TypeAdapterConfig<Staff, StaffDto>
    .NewConfig()
    .TwoWays();
```

**Comment by chaowlert** [comment]
Could you give me more info why you need configuration? 

For now, only interface mapper supports configuration.

```csharp
public class MyRegister : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        config.NewConfig<Staff, StaffDto>().TwoWays();
    }
}

```

**Comment by zs-dima** [comment]
I want it to keep EF model classes untouched, however I will try interface as you described it other thread and let you know if it will solve question.

**Comment by zs-dima** [comment]
Thanks a lot for answers

I tried interface as you described to keep EF model classes untouched (as it could be regenerated form DB in DB-first cases)
But it doesn't generate AdaptTo and TwoWays as well:

> ```cs
> [Mapper]
> public interface IUserMapper
> {
>     Expression<Func<User, Rpc.User>> ProjectToRpcUser { get; }
>     Expression<Func<User, Rpc.UserShortInfo>> ProjectToRpcUserShortInfo { get; }
> }
> ```

**Comment by chaowlert** [comment]
May be you can take a look at sample project https://github.com/MapsterMapper/Mapster/blob/master/src/Sample.CodeGen/Mappers/IStudentMapper.cs.

And read through wiki https://github.com/MapsterMapper/Mapster/wiki/Mapster.Tool.

If you think Sample project or Wiki is not good, feel free to make changes and create pull request.

**Comment by zs-dima** [comment]
Thanks a lot for details, I see that Interface does not generate extension methods, so it could not be used to keep EF model untouched and have the same mapping as ~config.NewConfig<Staff, StaffDto>().TwoWays();
Hope it will be possible once.

**Comment by chaowlert** [comment]
I added config to do fluent configuration. Please check https://github.com/MapsterMapper/Mapster/blob/master/src/Sample.CodeGen/MappingRegister.cs
