### ISSUE TITLE
Feature - Obtain values from methods, extension methods and default interface implementations

### ISSUE THREAD

**Issue by atrauzzi** [MapsterMapper/Mapster#278]
This could be a weird and terrible thing to want, but I encountered a scenario today where it might have been neat to get values from:

 - Methods

-and/or-

 - Extension methods
 - Default method & property implementations from interfaces

**Comment by chaowlert** [comment]
Can you give more detail and example?

**Comment by chaowlert** [comment]
Since there is no further detail, I will close for now.

For custom mapping, you can take a look at https://github.com/MapsterMapper/Mapster/wiki/Custom-mapping.

**Comment by atrauzzi** [comment]
Sorry just have missed the notification earlier.  I'm just on mobile, but you can imagine that it's just sitting values from similarly named methods and extension methods when mapping.

**Comment by chaowlert** [comment]
Mapster can map from method to property (map `GetName()` to `Name`) (https://github.com/MapsterMapper/Mapster/wiki/Data-types#mappable-objects).

For extension method & interface, I would like understand use cases, why we need those features.

**Comment by atrauzzi** [comment]
Obviously for the same reason why one would map from a method, why would it be different?
