### ISSUE TITLE
Does it support anonymous mapping?

### ISSUE THREAD

**Issue by joinevans** [MapsterMapper/Mapster#279]
```
var news = new { Name = "evans", Age = 18};
User user = new User();
//user.Adapt<?>();
user.Adapt(news);

public class User
{ 
    public string Name { get; set; }
    public int Age { get; set; }
}
```
Is there any way to solve anonymity?

**Comment by chaowlert** [comment]
Can you give your use case, why you need to adapt to anonymous type?

**Comment by joinevans** [comment]
> Can you give your use case, why you need to adapt to anonymous type?
I used sqlsugar 
https://github.com/sunkaixuan/SqlSugar

SqlSugarClient client = new DBClient().Instance;
var list = client.Queryable<learm_category>().Select(p => new { p.id, p.name }).ToList();

The read is anonymous, but I can't map it

**Comment by chaowlert** [comment]
Sorry still not understand, do you want to map from, or map to anonymous type? Mapping from anonymous type should already support.

If you would like to map to anonymous type, please show the completed example, showing only part of example is hard to catch up.

**Comment by joinevans** [comment]
> Sorry still not understand, do you want to map from, or map to anonymous type? Mapping from anonymous type should already support.
> 
> If you would like to map to anonymous type, please show the completed example, showing only part of example is hard to catch up.

I read data from the database, using the SqlSugar ORM framework, the read data is anonymous, I want to map to objects

**Comment by chaowlert** [comment]
If you would like to map from anonymous type to a defined object, it should already support. `anonymousObj.Adapt<YourType>();`
