### ISSUE TITLE
Mapping b/t two objects derived from same ancestor failing

### ISSUE THREAD

**Issue by KidCeltic** [MapsterMapper/Mapster#280]
I am working in an architecture where identical objects implemented in different tiers of the application cannot be adapted to the other. From the exception received, it appears as though they are both being considered the type of their abstract ancestor. Because that ancestor has types associated with other base types (that are overridden in the descendants), I am getting a "No default constructor for type 'BaseStudentIep'" exception (even though that abstract base class does have a concrete default constructor).

**Comment by chaowlert** [comment]
If in coding you map BasedType and expect Mapster to map DerivedType, Mapster is based on code generator, it need to know type in advance to generate mapping.

1. Pls check [`Include`](https://github.com/MapsterMapper/Mapster/wiki/Config-inheritance#include-derived-types)
2. Or you can pass type to `Adapt` overload.

**Comment by KidCeltic** [comment]
I am using the type in the Adapt<> statement.

Tim

**Comment by chaowlert** [comment]
If you use generic `Adapt<>`, you need to pass both derived srcType and derived destType. Ex. `src.Adapt<DerivedSrcType, DerivedDestType>(); `Or you can use non generice `src.Adapt(src.GetType(), typeof(DerivedDestType))`

**Comment by KidCeltic** [comment]
I tried both of those approaches and got the exact same error.

Tim

**Comment by chaowlert** [comment]
Sorry, then I might misunderstand your issue. Could you provide code to reproduce the error?
