### ISSUE TITLE
Merge dictionaries

### ISSUE THREAD

**Issue by atrauzzi** [MapsterMapper/Mapster#284]
Is there any way to configure mapster to merge dictionaries when it encounters them, rather than ignoring them, or trying to overwrite?

**Comment by chaowlert** [comment]
Really sorry, Mapster is object mapper. Currently only `Dictionary<string, *>` which treated as object like is able to merge. For now you can use [custom map](https://github.com/MapsterMapper/Mapster/wiki/Custom-conversion-logic) to create your own logic.

**Comment by atrauzzi** [comment]
Hmm, I do have a string, *, but it doesn't seem to be merging them.

**Comment by chaowlert** [comment]
```csharp
var dict1 = new Dictionary<string, int>
{
    ["foo"] = 1,
    ["bar"] = 2,
};
var dict2 = new Dictionary<string, int>
{
    ["bar"] = 3,
    ["baz"] = 4,
};
dict2.Adapt(dict1);
//dict1 = { ["foo"] = 1, ["bar"] = 3, ["baz"] = 4 }
```

**Comment by atrauzzi** [comment]
I'll keep an eye on this one and reopen if I encounter it again.  Apologies, moving fast on some things and ended up coding a workaround because the dictionaries just weren't being merged.
