### ISSUE TITLE
Issue with generated mapper using mapster tool

### ISSUE THREAD

**Issue by FlippyFloppyDoo** [MapsterMapper/Mapster#285]
I have a multiple classes with same name separated by namespaces.
When i generate Mapper using Mapster tool, mapper created without full class name in input and output types.

[Repository to reproduce](https://github.com/FlippyFloppyDoo/MapsterToolTest/tree/master/MapsterToolTest)

**Comment by chaowlert** [comment]
I uploaded Mapster.Tool 7.0.3, you can add -p to generate full type name.

`<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a $(TargetDir)$(ProjectName).dll -p" />`
