### ISSUE TITLE
Mapster + .net 5.0.1 error MSB3073

### ISSUE THREAD

**Issue by zs-dima** [MapsterMapper/Mapster#286]
Mapster v7.0.1 and v7.0.0 with .net 5.0.1 have error
and Mapster v7.0.1 with .net 5.0.0 have same error:
`Error	MSB3073	The command "dotnet mapster model -a abc.dll exited with code -532462766"`

**Comment by chaowlert** [comment]
Which Mapster.Tool version are you using? (Not Mapster library but Mapster.Tool).

Otherwise, please type command `dotnet mapster model -a abc.dll` explicitly, and copy the really error you got.

Pls also specify your OS & IDE.

**Comment by zs-dima** [comment]
@chaowlert 
thanks for reply
I am using Mapster v7.0.1 with Mapster.Tool v7.0.1 
(and tied Mapster v7.0.0 with Mapster.Tool v7.0.0 for .net 5.0.1 as well)
however Mapster v7.0.0 with Mapster.Tool v7.0.0 for .net 5.0.0 works well - all other combinations fire errors

OS Windows 10 64x
Latest VS 2019 16.9.0 Preview 2.0

**Comment by chaowlert** [comment]
I just uploaded Mapster.Tool 7.0.3 fix this problem.

**Comment by zs-dima** [comment]
Mapster v7.0.1 with Mapster.Tool v7.0.1 for .net 5.0.1

Same Error with other log:

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Google.Protobuf, Version=3.14.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. Invalid pointer (0x80004003 (E_POINTER))
Could not load file or assembly 'Mapster, Version=7.0.1.0, Culture=neutral, PublicKeyToken=2f39883af23c29a8'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad'. Invalid pointer (0x80004003 (E_POINTER))
Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Mapster.Tool.Program.GenerateModels(ModelOptions opt) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 120
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Mapster.Tool.Program.Main(String[] args) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 17
System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.14.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. Invalid pointer (0x80004003 (E_POINTER))
***
```

**Comment by chaowlert** [comment]
Do your path included space? Can you copy your path to the model?

I tried to reproduce with a grpc project, I works fine. But when I included space on a path then it produced error. So I would like to ensure you have the same root cause.

**Comment by chaowlert** [comment]
to fix space problem, you need to add quote

```xml
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster model -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
```

**Comment by chaowlert** [comment]
This is sample that works on my machine. https://github.com/chaowlert/hellogrpc

**Comment by zs-dima** [comment]
> Do your path included space? Can you copy your path to the model?
> 
> I tried to reproduce with a grpc project, it works fine. But when I included space on a path then it produced error. So I would like to ensure you have the same root cause.

No, path does not include space.
And .net 5.0.0 works fine with mapster 7.0.0 with the same project

**Comment by zs-dima** [comment]
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by zs-dima** [comment]
@chaowlert 

It does not works as well with 'Models' subfolder https://github.com/chaowlert/hellogrpc :

```
  <Target Name="Mapster" AfterTargets="AfterBuild">
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet tool restore" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster model -a $(TargetDir)$(ProjectName).dll" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster extension -a $(TargetDir)$(ProjectName).dll" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster mapper -a $(TargetDir)$(ProjectName).dll" />
  </Target>
  
```

**Comment by chaowlert** [comment]
I think you might need to create sample docker image. My machine has only 5.0.1 and it works fine.

**Comment by zs-dima** [comment]
Your sample does !not work on Windows 10 64x + VS 2019 16.9.0 Preview 2.0

with this project settings:
```
  <Target Name="Mapster" AfterTargets="AfterBuild">
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet tool restore" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster model -a $(TargetDir)$(ProjectName).dll" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster extension -a $(TargetDir)$(ProjectName).dll" />
    <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster mapper -a $(TargetDir)$(ProjectName).dll" />
  </Target>
  
```

**Comment by zs-dima** [comment]
Project folder: Models\Models: `"$(ProjectDir)\Models"`
Folder without spaces

**Comment by chaowlert** [comment]
> Your sample does !not work on Windows 10 64x + VS 2019 16.9.0 Preview 2.0
> 
> with this project settings:
> 
> ```xml
>   <Target Name="Mapster" AfterTargets="AfterBuild">
>     <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet tool restore" />
>     <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster model -a $(TargetDir)$(ProjectName).dll" />
>     <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster extension -a $(TargetDir)$(ProjectName).dll" />
>     <Exec WorkingDirectory="$(ProjectDir)\Models" Command="dotnet mapster mapper -a $(TargetDir)$(ProjectName).dll" />
>   </Target>
>   
> ```

Really sorry, I tried this on my machine, it also works. I have no idea where problem is.

I'm wondering when you said .NET 5.0 and .NET 5.0.1 what does it means? Currently when I run `dotnet --version` on my machine it says `5.0.101`.

**Comment by zs-dima** [comment]
@chaowlert looks it had been .NET 5.0 installation issue, now it works well
thanks a lot for looking into and awesome library that helps a lot
