### ISSUE TITLE
Issue in Mapster.Tool with -p flag and linq extension method

### ISSUE THREAD

**Issue by FlippyFloppyDoo** [MapsterMapper/Mapster#287]
When i use -p flag, linq methods generated with errors, cause its not in using directive.
I think with flag p namespace begins with System need to put in using.
Mapster.Tool version 7.0.3

[Repository to reproduce](https://github.com/FlippyFloppyDoo/MapsterToolTest/tree/master/MapsterToolTest)

**Comment by chaowlert** [comment]
I just published 7.0.4 fixed extension method issue.
