### ISSUE TITLE
Obtain differences between mappable properties

### ISSUE THREAD

**Issue by atrauzzi** [MapsterMapper/Mapster#288]
I encountered a scenario today where it would be useful to be able to take two objects and have the differences of the values mapster recognizes returned.

```csharp
var objectOne = ...;
var objectTwo = ...;

// option one
IDictionary<string, ???> = objectOne.Difference(objectTwo);
// option two
IList<string> = objectOne.Difference(objectTwo);
```

### Option One
The `string` would be the name of the property, and then the `???` could either be the value that differs, or special mapster type that contains metadata about the diff.

### Option Two
Simply a list of the properties that differ.

**Comment by chaowlert** [comment]
I think, you can map object into dictionary or json and comparing diff using dict/json could be better. Mapster focus only on mapping object, you can find or create another lib to do the diff.
