### ISSUE TITLE
Mapster.Tool or TextTemplate with EnableNonPublicMembers

### ISSUE THREAD

**Issue by leachdaniel** [MapsterMapper/Mapster#289]
## Backstory
I am looking at following a pattern that will allow keeping domain objects fully encapsulated and use different objects to represent tables (single responsibility) the setters on the domain object are currently protected.

## Issue
I like the idea of using generated code and have experimented with Mapster.Tool, but found it doesn't appear to support `EnableNonPublicMembers`.

## Question
Is there way to make generated code that will compile? The compile error is:

> CS0272	The property or indexer 'User.Username' cannot be used in this context because the set accessor is inaccessible

### Example Source:
```csharp
    public class User
    {
        public User(string username)
        {
            Username = username;
        }
       
        public int UserID { get; protected set; }
        public string Username { get; protected set; }
    }
   
    public class DBUser
    {

        public int UserID { get; set; }
        public string Username { get; set; }
    }
   
    [Mapper]
    public interface IUserMapper
    {
        User Map(DBUser value);
    }
   
    public class TableRegister : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            config.ForDestinationType<User>()
                .MapToConstructor(true)
                .EnableNonPublicMembers(true);
        }
    }
```
### Example Generated:
```csharp
    public partial class UserMapper : IUserMapper
    {
        public User Map(DBUser p1)
        {
            return p1 == null ? null : new User(p1.Username)
            {
                UserID = p1.UserID,
                Username = p1.Username
            };
        }
    }
```

**Comment by chaowlert** [comment]
Codegen doesn't support non-public property. It is language limitations not library limitations. Please try changing to `internal`. If not work, please map using `Adapt` method instead of code geneation.
