### ISSUE TITLE
Support private parameterless constructor

### ISSUE THREAD

**Issue by hanslai** [MapsterMapper/Mapster#290]
Seems like Mapster does not support `private `default (parameterless) constructor for mapping.  One will have to provide a `public` default constructor or use `ConstructUsing`

Yet, In order to follow DDD rules, public default constructor shall not be allowed because we do not want programmers to instantiate an entity without setting the require properties.  

Also, using `ConstructUsing` is kind of troublesome because we have to update the ConstructUsing code every time we change an entity's properties.  It is almost the same amount of work as mapping the object manually.

Is it possible for Mapster to support private default constructor like Automapper does?  Thank you

Related Issue #28

**Comment by chaowlert** [comment]
You can use `MapToConstructor(true)`

**Comment by hanslai** [comment]
Thanks @chaowlert MapToConstructor(true) works fine.

We did the following 
```
  public class MappingConfig : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            config.ForType<Create.Command, Department>()
                   .MapToConstructor(true);
        }
    }
```

Yet, it will still be nice if there is a global setting to support `private `parameterless constructor for all the mappings.  So, programmer can avoid this mapping configuration completely for all each entity.
