### ISSUE TITLE
IgnoreIf based on other fields

### ISSUE THREAD

**Issue by Porkechebure** [MapsterMapper/Mapster#291]
How to make a rule that map 2 fields based on the value of another?

For instance I have:
```
public class Test
    {
        public string field1 { get; set; } = "MapMeToField2";
        public bool canMap { get; set; } = false;
    }
```

```
    public class Test2
    {
        public string field2 { get; set; } = null;
    }

```
and I need to map field1 to field2 only if canMap = true

Documentation don't give enough info to do that through Ignore or IgnoreIf (and I think it's a dumb move as it'a common scenario).

Tried
`TypeAdapterConfig config = new TypeAdapterConfig()
                .NewConfig<Test, Test2>()
                .IgnoreIf((src,dest) => src.canMap, dest => dest.field2)
                .Config;`

This doesn't work, as it expects that the first class has a property with same name.

Tried
`TypeAdapterConfig config = new TypeAdapterConfig()
                .NewConfig<Test, Test2>()
                .IgnoreIf((src,dest) => src.canMap, src=> src.field2, dest => dest.field2)
                .Config;`

Doesn't work. It's even hard to understand what it does, because docs don't explain, but I guess you can give a list of properties of the destination class and they will be mapped upon the rule given, so you don't have to declare a IgnoreIf for each one.

Now, how one does a rule to say
`
if(canMap)
    {dest.field2 = src.field1}
`

It's a common scenario and I find strange it hasn't been implemented or there is no easy way to do it

Otherwise the solution I found is a simple bool condition on the map, which does not look all that great, but could work

`.Map(dest => dest.field2, src => src.canMap ? src.field1 : null)`

Thank you

**Comment by chaowlert** [comment]
You can use Map, third parameter accepts condition.
`.Map(dest => dest.field2, src => src.field1, src => src.canMap)`
