### ISSUE TITLE
AdaptMember attribute only Memberside ?

### ISSUE THREAD

**Issue by sphildreth** [MapsterMapper/Mapster#292]
Hi, 
I have a Entity Framework model which has terrible names like 
```
    public class User
    {
        public int UserIdentification {get; set;}
    }
```

Then I have a DTO used by my Business models like this:
```
    public class UserDto
    {
        [AdaptMember("UserIdentification"]
        public int UserId {get; set;}
    }
```

This works lovely and the UserDto UserId gets set as expected. Then we have some API models like this:
```
    public class UserInfo
    {
        public int UserId {get; set;}
    }
```

The issue I am having is I cannot get the UserInfo UserId value set via an Adapt():
```
    userDto.Adapt<UserInfo>();
````
 Unless I add the AdaptMember attribute as set on the DTO User. I don't want to do this as then the API model seems tightly coupled to the database, just seems I must be doing this incorrectly.

Any help is appreciated!

**Comment by chaowlert** [comment]
Will add in future version. For now, you might need to config using [Map](https://github.com/MapsterMapper/Mapster/wiki/Custom-mapping) instead of attribute.
