### ISSUE TITLE
Question: Create DTOs without attributes on POCOs?

### ISSUE THREAD

**Issue by MichaeIDietrich** [MapsterMapper/Mapster#295]
**Description**

As shown in your example it is possible to automatically create DTOs and mappers by defining attributes on the POCOs:
```cs
[AdaptTo("[name]Dto"), GenerateMapper]
public class Student {
    ...
}
```

But doing so the POCO would have a dependency on the DTO and mapper code, which is usually not wanted.

I think of something like an external descriptor class (pseudo code):
```cs
[MappingDescription("[name]Dto")]
public class StudentMappingDescriptor : IGenerateDto, IGenerateMapping {
    ...
}
```

**Question**

Is there a way to generate DTOs and mappers without defining attributes on the exisiting POCOs?

**Scenarios**

* Better separation for POCOs and DTOs (POCOs should usually not know about DTOs)
* Possibility to generate classes from within another assembly (since those descriptors could be defined everywhere)
* Possibility to generate multiple different DTOs for one POCO (e.g. one for the database layer and one for a REST API)
* The descriptor class could also be used to define the behavior of the DTO (e.g. map GUIDs as strings etc.)

**Comment by MichaeIDietrich** [comment]
Oh I missed that you want Q&A to be on StackOverflow. 

I still would like to let this issue to be open, since I expect the answer of my question just to be no. 
So this issue could be formed into a feature request if this is OK for you?

**Comment by chaowlert** [comment]
Currently only mapper can be generated without attribute. (https://github.com/MapsterMapper/Mapster/wiki/Mapster.Tool#generate-using-configuration).

I will leave this open as feature request. I might add support to generate DTO using fluent API.

**Comment by chaowlert** [comment]
Pls see sample to code generation fluent API sample https://github.com/MapsterMapper/Mapster/blob/master/src/Sample.CodeGen/MappingRegister.cs
