### ISSUE TITLE
Tuple to object mapping with Mapster.Tool / ICodeGenerationRegister ?

### ISSUE THREAD

**Issue by suntereo** [MapsterMapper/Mapster#300]
First, thank you for such a nice tool! I have a question on how to get code generation to work.

Please see my sample console app:
[MapsterTesting.Question.zip](https://github.com/MapsterMapper/Mapster/files/5877482/MapsterTesting.Question.zip)

In this app, I can successfully create a mapping between a tuple and destination like this:
config.NewConfig<(Database.Driver, Database.DriverAccountingSetting), Domain.DriverDto>()
   .Map(dest => dest, src => src.Item1)
   .Map(dest => dest, src => src.Item2)
   .TwoWays();

I am able to create 1 DTO from 2 database classes:
var driverDto = mapper.Map<Domain.DriverDto>((dbDriver, driverAccountingSetting));

I'm able to extract each database class from 1 DTO:
var dbDriverFromDto = mapper.Map<Database.Driver>(driverDto);
var dbDriverSettingsFromDto = mapper.Map<Database.DriverAccountingSetting>(driverDto);

This works well! But my project manager is concerned about the performance hit seen at Compile() time. So I'm exploring Mapster.Tool to see how to handle code generation. However, I'm not seeing any way to configure that for similar tuple usage. I've looked at the entire wiki for Mapster.Tool. I would expect to be able to define the same kind of mapping with ICodeGenerationRegister. I've spent all day on it and am thinking it's not possible. I just wanted to confirm. If it is possible, would you be able to point me in the right direction. Thanks!

**Comment by chaowlert** [comment]
`ICodeGenerationRegister` main purpose is to generate model classes without attributes, some projects would like to generate DTOs without attributing their domain, so they can use `ICodeGenerationRegister` to declare how you generate models together with mappings. 

To define mapping config, you can put all configuration in [`IRegister`](https://github.com/MapsterMapper/Mapster/wiki/Attribute-base-Code-generation#generate-using-configuration). Code generation will pickup all logics from classes implemented `IRegister`.

**Comment by suntereo** [comment]
Thank you! I have it working now thanks to your help.
