### ISSUE TITLE
.AfterMapping() creates class with a null Action resulting in object reference error

### ISSUE THREAD

**Issue by suntereo** [MapsterMapper/Mapster#301]
Please see my sample project demonstrating the issue:
[MapsterTesting.Question2.zip](https://github.com/MapsterMapper/Mapster/files/5883767/MapsterTesting.Question2.zip)

I am using AfterMapping() like this:

```
public class MyRegister : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        // specify complex code mapping like this
        config.NewConfig<(Database.DriverDbEntity, Database.DriverAccountingSettingDbEntity), Domain.DriverDto>()
            .Map(dest => dest, src => src.Item1)
            .Map(dest => dest, src => src.Item2)
            .AfterMapping((src, dest) => // this doesn't seem to work
            {
                dest.DriverCode = $"{src.Item1.FirstName} Hello World!!!";
            });
    }
}
```

When the generated Adapt method is called, an object reference error is thrown:
<img width="714" alt="Screen Shot 2021-01-27 at 3 45 33 PM" src="https://user-images.githubusercontent.com/171720/106069108-bd3ae500-60b6-11eb-9e29-3ab95e6dd49f.png">

The code generator is creating a null Action1 (can be seen in pic above) and I cannot figure out how to avoid this.

It looks to me like a bug, but perhaps I'm not using it correctly. Any insight would be appreciated. Thanks!

**Comment by chaowlert** [comment]
For code generation, please use [`AfterMappingInline`](https://github.com/MapsterMapper/Mapster/wiki/Before-after-mapping#before--after-mapping-in-code-generation). There is some limitation on code generation.

**Comment by suntereo** [comment]
Sorry, I missed that in the documentation. It works nicely! Thank you!!
