### ISSUE TITLE
Mapster show a wrong dependency

### ISSUE THREAD

**Issue by mhamri** [MapsterMapper/Mapster#302]
is it a real dependency of Mapster? if not then some error is being thrown at the very core of .Net runtime and mapster doesn't catch it.

![image](https://user-images.githubusercontent.com/8991783/107067657-8f724080-681a-11eb-8d0d-c237eb8eb173.png)

here is the repo. please make sure to use the `Mapster` Branch

https://github.com/mhamri/ef-int32-bug/tree/mapster

also, if I add the `[AdaptTo("[name]Dto"), GenerateMapper]` on top of entity classes, all the generated mappers are empty hence I mapped them manually.

**Comment by chaowlert** [comment]
Thank you for report. My project still use EF Core 2.x so I don't know it has problem. Please use https://www.nuget.org/packages/Mapster.EFCore/5.0.0.

**Comment by chaowlert** [comment]
NOTE: you might need to use MaxDepth, PreserveReference doesn't support for EF Query.

**Comment by chaowlert** [comment]
The reason, Mapster cannot generate mapper is because Mapster cannot generate circular reference projection. I will throw descriptive error in the future. Here is the way to fix.

    public class MyRegister : IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            Console.WriteLine("HOOOOOOOOOOOOOOOOOOOOOOOOO");
            config.Default.MaxDepth(2);
        }
    }
