### ISSUE TITLE
How do I know which mapping field cause the mapping to fail?

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [MapsterMapper/Mapster#304]
If I have a mapping of 50 fields and then run it and I get the error: "Input string is not in correct format", how do I know which field it failed at? I mean the stack trace may say something about the type gone wrong but if I have 50 fields how do I know which one failed? Or is that not possible with Mapster?

**Comment by chaowlert** [comment]
You need to debug. https://github.com/MapsterMapper/Mapster/wiki/Debugging
