### ISSUE TITLE
Fluent API not generating code from other assembly

### ISSUE THREAD

**Issue by daniaremon** [MapsterMapper/Mapster#306]
First, thanks for this awsome tool !!!

#### Issue description

When trying to generate code referencing OTHER_ASSEMBLY in fluent api, nothing happens.

#### Steps to reproduce the issue

1. Install Mapster.Tool in a project
2. Copy "Generate automatically on build" tags on csproj file
3. Create a POCO class inside OTHER_ASSEMBLY.
4. Create a "fluent api configuration class" inside the project:

```c#
    config.AdaptTo("[name]Dto")
            .ForAllTypesInNamespace(OTHER_ASSEMBLY, "POCO..Namespace");
```
5. Build

#### What's the expected result?

- Generated Dtos in Models Folder inside current Assembly.

#### What's the actual result?

- nothing happens

#### Additional details 

I review the code. Maybe I'm wrong, but in this method:
https://github.com/MapsterMapper/Mapster/blob/d7a8397b072fc65b3e9bac17770f5574db30f215/src/Mapster.Tool/Program.cs#L116-L137
the current ASSEMBLY is used, but inside the codeGenConfig.Scan method:
https://github.com/MapsterMapper/Mapster/blob/d7a8397b072fc65b3e9bac17770f5574db30f215/src/Mapster.Tool/Extensions.cs#L175-L186
when Register is called, my ForAllTypesInNamespace with OTHER_ASSEMBLY is called.

So, I think the problem is in the foreach of the GenerateModels method. There, the GetTypes() of the current ASSEMBLY is called (ignoring completely the OTHER_ASSEMBLY types).

Thanks in advance

**Comment by chaowlert** [comment]
Yeah, it seemed like bug. If you can fix PR is welcome. It might take a while for my availability.
