### ISSUE TITLE
Feature request: ForAllTypesContainsNamespace 

### ISSUE THREAD

**Issue by daniaremon** [MapsterMapper/Mapster#308]
🚀Feature request

Description: A Method like ForAllTypesInNamespace, but that allows to include all types that belong to a namespace that contains a supperior hierarchy. 
Type: Enhancement

### Is your proposal related to a problem?

Maybe related with:
#306

### Describe the solution you'd like

Namespaces structure:

- Pocos
- Pocos\PocosAccounting
- Pocos\PocosOrders

Method: 

ForAllTypesContainsNamespace(ASSEMBLY, "Sample.Pocos");

This method would include all types inside the sub namespaces.

### Describe alternatives you've considered

This is possible with ForTypes method and Linq filtering:

ForTypes(typeof(PocoInvoice).Assembly.GetTypes().Where(....).ToArray());

### Additional Ideas

This method is too close to this requested functionality. It would be better that have more options.

**Comment by chaowlert** [comment]
Cool idea, thank you for suggestion.

**Comment by daniaremon** [comment]
thanks @chaowlert for all the fixes and features!
