### ISSUE TITLE
!!!suggestion!!! Generate record DTO

### ISSUE THREAD

**Issue by sneltyn** [MapsterMapper/Mapster#312]
With the advent of record in c# 9, it would be great to generate a DTO as a record.

Have you ever thought about it? I would be happy to help with this

**Comment by chaowlert** [comment]
Thank you. I'm waiting for PR. You also might to check this repo https://github.com/chaowlert/ExpressionDebugger. It is library that Mapster use to generate source.

**Comment by sneltyn** [comment]
@chaowlert ok, I try this
