### ISSUE TITLE
GenerateMapper(MapType.Map) with 'print full type name' generates invalid method names

### ISSUE THREAD

**Issue by Rans4ckeR** [MapsterMapper/Mapster#313]
When mapping classes with the same name in different layers, using this code:

internal sealed class Register : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        config.NewConfig<X.Y.Z.ClassName, A.B.C.ClassName>().GenerateMapper(MapType.Map);
    }
}

The following code is generated when using Mapster.Tool with the -p switch which does not compile:

public static A.B.C.ClassName AdaptToA.B.C.ClassName(this X.Y.Z.ClassName p1) { ... }

Tested using:
Mapster.Tool 8.0.0 & 7.1.3
Mapster 7.1.5 & 7.1.3

**Comment by chaowlert** [comment]
Thank you for report. I will release 8.0.1 to fix this problem.
