### ISSUE TITLE
Mapping inherited interface without members causes CompileException

### ISSUE THREAD

**Issue by MSinstein** [MapsterMapper/Mapster#314]
Hi, I have the following issue:
I would like to map from a data transfer object `Dto` to a domain object `Domain`
```cs
public class Dto
{
    public ISource Property { get; set; }
}

public class Domain
{
    public IDestination Property { get; set; }
}
```
using the technique to map respective derived types of `ISource` and `IDestination` as [described in the Wiki](https://github.com/MapsterMapper/Mapster/wiki/Config-inheritance#include-derived-types).

Sadly, this mapping fails with a `Mapster.CompileException` if said interfaces are empty.
Currently, I am adding a dummy property to the interfaces as a workaround. It would be really nice, if this could be avoided.

Minimal example to reproduce the issue:
```cs
[TestClass]
public class WhenMappingDerived
{
    [TestMethod]
    public void WhenMappingDerivedFromInterfaceWithoutMembers()
    {
        //Arrange
        var config = TypeAdapterConfig<ISource, IDestination>.NewConfig()
            .Include<Source, Destination>(); // and possibly many more

        //Act && Assert
        Should.NotThrow(() => config.Compile());
    }
}

public interface ISource
{
}

public class Source : ISource
{
    public string Tag { get; set; }
}

public interface IDestination
{
}

public class Destination : IDestination
{
    public string Tag { get; set; }
}
```

**Comment by chaowlert** [comment]
Thx for report & unit test. When Mapping the interface, Mapster will try to create proxy class. And it will throw error if there is no property in the interface. This check should be ignored, when there is `Include` setting.

For now you can add constructUsing if you don't want to have dummy property.

```csharp
var config = TypeAdapterConfig<ISource, IDestination>.NewConfig()
            .ConstructUsing(dest => new Destination())
            .Include<Source, Destination>();
```

**Comment by MSinstein** [comment]
Thanks for the quick reply and your suggestion.
In the real use case, `Destination` is not the only derivative of `IDestination` but there are many more, say `Destination2`, `Destination3`, etc.
When I use
```cs
ConstructUsing(() => new Destination())
```
I will always just get `Destination` and none of the other derived types.
