### ISSUE TITLE
Mapster in .NET 5 (C# 9.0)

### ISSUE THREAD

**Issue by GlebGulin** [MapsterMapper/Mapster#317]
Good afternoon. How does the library behave with records in .NET 5? I've noticed the tendency that the names of class and record fields should be strictly the same, and also use the same nesting of objects, even though we prescribe a behavior rule. Sometimes this is inconvenient. For example: 
```
TypeAdapterConfig<a, aDTO>.NewConfig()
                          .Map(dest => dest.b, src => src.b)
                          .Map(dest => dest.c, src => src.c)
                              .Map(dest => dest.c.d.e, src => src.c.d.e)
                              .Map(dest => dest.c.d.f, src => src.c.d.f)
```
It just won't work any other way. And another question: what if you work with a model where an entity accepts parameters by constructor but gives them away by the usual get property?
Maybe there is some kind of guide to use in new environments? Thank you very much for the answer

**Comment by chaowlert** [comment]
There are a lot of questions, I cannot capture what is the issue. I will try to answer question by question.

> How does the library behave with records in .NET 5?

Mapster should be able to map.

> I've noticed the tendency that the names of class and record fields should be strictly the same, and also use the same nesting of objects, even though we prescribe a behavior rule. Sometimes this is inconvenient.

I cannot capture concern for this issue. If property names are the same, you don't need Map config.

> what if you work with a model where an entity accepts parameters by constructor but gives them away by the usual get property?

I also cannot capture this, could you provide example? The model you described is similar to record types, so it should be able to map without config. (If property names are the same)

> Maybe there is some kind of guide to use in new environments?

[Wiki](https://github.com/MapsterMapper/Mapster/wiki), or [Sample projects](https://github.com/MapsterMapper/Mapster/tree/master/src/Sample.AspNetCore), if you need more, feel free to contribute.
