### ISSUE TITLE
How to generate DTO to another Project and directory

### ISSUE THREAD

**Issue by oyama1100** [MapsterMapper/Mapster#318]
How to generate DTO to another Project and directory (From Domain project To Application project and from Model directory to DTO directory) in Mapster(generating models) ?
The default generate to the current project(Domain project) in model folder but I want to generate to DTO Folder in Application project.
How can I do this?

**Comment by chaowlert** [comment]
Please check [Fluent-API-Code-generation](https://github.com/MapsterMapper/Mapster/wiki/Fluent-API-Code-generation) method `ForAllTypesInNamespace`.

Please help contribute Wiki if you think documentation is not helpful.

**Comment by unclesp1d3r** [comment]
Literally nothing about this answer helps. There's nothing in the documentation about how to output to another project. I'm happy to update the documentation, but I don't have the correct answer to start with. I tried adding the build to my shared project, but then it has to reference the parent, which would create a circular reference.

**Comment by unclesp1d3r** [comment]
Sorry, I just figured out my failures. There doesn't appear to be a clear solution to my specific issues, but I was able to achieve the stated goal by moving my domain objects, ICodeGenerationRegister, and the generated Dto files to my shared project. I then moved the build directives to that project file and everything worked.
