### ISSUE TITLE
Feature Request - Interface code gen - option to produce extension method mappings

### ISSUE THREAD

**Issue by Hoopie** [MapsterMapper/Mapster#320]
Interface code gen allows us to use our own pocos and create an interface from which we can generate a mapper.
I would to be able to have the option of generating the mapping as extension methods rather then a mapper class.

So given my own existing classes, Contact (domain model) and ContactDetailVm (dto) I can define:
```csharp
   [Mapper]
    public interface IContactMapper
    {
        ContactDetailVm MapTo(Contact contact);
    }
```

Which currently gives me this mapper class
```csharp
    public partial class ContactMapper : IContactMapper
    {
        public ContactDetailVm MapTo(Contact p2)
        {
            return p2 == null ? null : new ContactDetailVm()
            {
                Id = p2.Id,
                ....
            };
        }
    }
```

I would like the option to have it generate extension method(s) instead rather then the mapper class.

```csharp
    public static class ContactMappingExtensions
    {
        public static ContactDetailVm MapToContactDetailVm (this Contact p2)
        {
            return p2 == null ? null : new ContactDetailVm()
            {
                Id = p2.Id,
                ....
            };
        }
    }
```

**Comment by chaowlert** [comment]
This should already supported by using [attributes](https://github.com/MapsterMapper/Mapster/wiki/Attribute-base-Code-generation) or [Fluent api](https://github.com/MapsterMapper/Mapster/wiki/Fluent-API-Code-generation).

**Comment by afj88** [comment]
> This should already supported by using [attributes](https://github.com/MapsterMapper/Mapster/wiki/Attribute-base-Code-generation) or [Fluent api](https://github.com/MapsterMapper/Mapster/wiki/Fluent-API-Code-generation).

Is there any chances that this feature will also be available via interface code generation?
