### ISSUE TITLE
Mapster IMapper with config fork

### ISSUE THREAD

**Issue by adriano-digiere** [MapsterMapper/Mapster#325]
How to properly use IMapper (dependency injection) with a config fork?? I have the following class:

`public class Example: IExample
{
    #region Variables and Properties

    public IAppContext Context { get; }
    private readonly IMapper _mapper;

    #endregion Variables and Properties

    #region Constructors

    public Example(IAppContext context, IMapper mapper)
    {
        Context = context;
        _mapper = mapper;
    }

    #endregion Constructors
}`

How to use _mapper with a fork in TypeAdapterConfig?

Thanks.

**Comment by chaowlert** [comment]
No way for now, currently a mapper has only one config. Can you provide your use case? So I can see how to support this.

**Comment by adriano-digiere** [comment]
Hi @chaowlert! Thanks for your time. I'll try to explain.

I have configured mapping in Startup (ConfigureServices):

`            services.AddSingleton(GetConfiguredMappingConfig());
            services.AddScoped<IMapper, ServiceMapper>();
`

Than I have the GetConfiguredMappingConfig method:

`        private static TypeAdapterConfig GetConfiguredMappingConfig()
        {
            TypeAdapterConfig config = new TypeAdapterConfig();

            config.Default.PreserveReference(true);
            config.AllowImplicitSourceInheritance = true;
            config.AllowImplicitDestinationInheritance = true;

            // Ignores the TimeStamp field for all mappings
            config.Default.Ignore("TimeStamp");

            config.NewConfig<WBaseEntity, WBaseEntity>()
                .Ignore(dest => dest.Id)
                .Ignore(dest => dest.ChangeDate)
                .Ignore(dest => dest.ChangeUserId);

            config.NewConfig<TimeSpan, uint>()
                .MapWith(s => (uint)Math.Round(s.TotalMinutes));

            config.NewConfig<TimeSpan?, uint?>()
                .MapWith(s => s.HasValue ? (uint)Math.Round(s.Value.TotalMinutes) : null);

            config.NewConfig<uint, TimeSpan>()
                .MapWith(s => TimeSpan.FromMinutes(s));

            config.NewConfig<uint?, TimeSpan?>()
                .MapWith(s => s.HasValue ? TimeSpan.FromMinutes(s.Value) : null);

            config
                .NewConfig<ResourceAvailability, ResourceAvailability>()
                .Map(dest => dest.Id, src => Guid.NewGuid());


            return config;
        }
`

I have this class ResourceAvailability that is not a entity nor a dto. It's a class that I use in a heavy process and I need to constantly make copies of it. I'm using mapster to do that, because a need high performance and mapster is doing great.
In most cases when mapping from a ResourceAvailability to another ResourceAvailability, I need a new Guid for Id field. But in some specific cases, I need to simple copy Id field. That's the reason why I need a difrent config.

Is there a way of doing that?

Thanks.

**Comment by chaowlert** [comment]
This is dependency injection topic, not Mapster itself. A lot of DI libraries can solve this problem. If you prefer not to use DI library, you can use Dictionary<string, IMapper> as a factory.

```csharp
services.AddSingleton(GetConfiguredMappingConfig());
services.AddScoped<IMapper, ServiceMapper>();
services.AddSingleton(provider =>
{
    var copyIdConfig = GetCopyIdConfig();
    var copyIdMapper = new ServiceMapper(provider, copyIdConfig);

    // other mappers here

    return new Dictionary<string, IMapper>
    {
        ["copyId"] = copyIdMapper,
        // other mapper keys
    };
});

```

Now you can have multiple kinds of IMapper instances.

```csharp
public MyService(
    IMapper mapper,     // this is default mapper
    Dictionary<string, IMapper> mapperFactory) {

    var copyIdMapper = mapperFactory["copyId"];    // this is copyId mapper
}
```
