### ISSUE TITLE
Mapping to an existing object doesn't work

### ISSUE THREAD

**Issue by tanbirhossain** [MapsterMapper/Mapster#326]
I am trying to map from the list Object to the existing created list object.
It doesn't work.

```
var dtoList = new List<CustomerDto>
                      {
                          new CustomerDto { Id = 1, FirstName = "##", LastName = "##" },
                          new CustomerDto { Id = 2, FirstName = "##", LastName = "##" },
                          new CustomerDto { Id = 3, FirstName = "##", LastName = "##" }
                      }; 

var listVM = new List<CustomerVM>();
 dtoList.Adapt(listVM);
```
Here,  **dtoList** data doesn't map with **listVM** object.

**Comment by chaowlert** [comment]
In fact, map to existing list directly is just not supported. You can use `Adapt<List<CustomerVM>>()` for now.

However, when mapping poco object, mapping to existing list is supported through [`UseDestinationValue`](https://github.com/MapsterMapper/Mapster/wiki/Mapping-readonly-prop).

I will see how to support this in the future.

**Comment by chaowlert** [comment]
Sorry, I don't think I will support this for now. Because it will conflict with behavior of type with list properties. And there is workaround for the problem. (using `Adapt<List<CustomerVM>>()`)
