### ISSUE TITLE
Mapster.Tools - How to define the namespace & output directory of a single DTO while generating code ?

### ISSUE THREAD

**Issue by Tire-Li** [MapsterMapper/Mapster#328]
Currently, global settings of output namespace & output directory is define in csproj file. In a complex project with deep nested namespace, i have to reorganize the namespace & directory of every generated DTO. I hope Mapster.Tools can help me to put the DTOs in specified directory & namespace, which is different from global settings.

**Comment by chaowlert** [comment]
https://github.com/MapsterMapper/Mapster/wiki/Mapster.Tool/_edit#dynamic-outputs--namespaces
