### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by elmurphy** [MapsterMapper/Mapster#330]
Used mapster adapt method and dotnet project is broked and throw 503 after that error.

I used set null child data to stop infinite loop error, but this is wrong, what should we do about that ?

Note: it's not throwing a proper error.

**Comment by chaowlert** [comment]
My guess is it should related to circular reference. By default, Mapster doesn't track object for you.

Please check out [this](https://github.com/MapsterMapper/Mapster/wiki/Object-references) (PreserveReference, MaxDepth, ShallowCopyForSameType).

I will close for now. Please reopen if you still have issue.
