### ISSUE TITLE
InvalidOperationException when using DI in collection element mapping

### ISSUE THREAD

**Issue by n-shay** [MapsterMapper/Mapster#332]
I've ran into this issue last week and spent quite some time looking into it, I would love to get some explanation about the implementation chosen and what the implications are for the workaround.

### Background
Our existing DTOs use `IEnumerable<T>` to represent child collection properties.
Some of the DTOs are complex and their child properties are of type of yet another DTO.
We define custom conversions of each POCO to DTO.
Certain POCO properties are mapped using a service injected with `MapContext`.

### Issue
When the destination type is evaluated, the value is set to `SelectListIterator` and no instantiated until after the IoC container scope is disposed and therefore generating the following exception:
```
System.InvalidOperationException: Mapping must be called using ServiceAdapter
    at Mapster.TypeAdapterExtensions.GetService[TService](MapContext context) in D:\Dev\Repos\GitHub\Mapster\src\Mapster.DependencyInjection\TypeAdapterExtensions.cs:line 19
   at lambda_method(Closure , Poco )
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
...
```
If we change the destination type properties to use `List<T>` or array, it works as intended. 
But we are talking about hundreds of occurrences that will need to be modified, so we should avoid that at all cost. Especially since AutoMapper works great with this scenario.

### Steps to Reproduce
This is the simplified scenario written as test within `Mapster.DependencyInjection.Tests.InjectionTest`:
(in the test, I'm mapping directly using `.Map<IEnumerable<Dto>>(...`  so please don't suggest to change it to `List<Dto>`)
```
        [TestMethod]
        public void InjectionInsideCollection()
        {
            var config = new TypeAdapterConfig();
            config.NewConfig<Poco, Dto>()
                .Map(dest => dest.Name, _ => MapContext.Current.GetService<IMockService>().GetName());

            IServiceCollection sc = new ServiceCollection();
            sc.AddScoped<IMockService, MockService>();
            sc.AddSingleton(config);
            sc.AddScoped<IMapper, ServiceMapper>();

            var sp = sc.BuildServiceProvider();

            IEnumerable<Dto> dtos;
            using (var scope = sp.CreateScope())
            {
                var mapper = scope.ServiceProvider.GetService<IMapper>();
                var pocos = new List<Poco> {new Poco {Id = "bar"}};
                dtos = mapper.Map<IEnumerable<Dto>>(pocos);
            }
            
            dtos.ShouldNotBeEmpty();
            dtos.Count().ShouldBe(1);
            dtos.Single().Name.ShouldBe("foo");
        }
```

### Workaround
I categorize it as a workaround since I'm not sure what the implications are and if none, I think that should be the default behavior. 
We added the following default configuration:
```
config.Default.Settings.AvoidInlineMapping = true;
```

Any help, clarification, suggestion is appreciated...

**Comment by chaowlert** [comment]
Too bad, it is because of `IEnumerable<>` behavior. Enumerable computed lazily outside service provider scope.

You have 2 choices.
1. Using `List<>`
2. Move `dtos.Count()`, `dtos.Single()` inside service provider scope.

**Comment by n-shay** [comment]
@chaowlert 
First, I appreciate the quick response. But can you explain the implications of using `AvoidInlineMapping`?

Second, I still think it's a bad design of this library. 
`IEnumerable` doesn't have any behavior, it is an interface. When you use a third party library, especially one that uses injected services, you'd expect the operation to materialize/instantiate before returning. You cannot control the scope of execution, especially then those `IEnumerable` are child properties 2 or 3 levels into mapped (root) object, once you pass it to the next service/layer of your application.

Here's a more detailed scenario:

```
// EF POCO
public class SomeEntity
{
    public int Id {get; set;}
    public virtual ICollection<ChildEntity> Childs {get; set;}
    // ...
}
public class ChildEntity
{
   public int Id {get; set;}
}




// Domain models / DTO
public record SomeDto(int Id, IEnumerable<ChildDto> Childs);

public record ChildDto(int Id, /* property that's mapped to resolve using injected service */ );
```

Other mapping libraries do that, but this one doesn't.

I understand you might not want to fix it, hence I'd like to understand the implication of the `AvoidInlineMapping` setting.

**Comment by chaowlert** [comment]
You are correct in your scenario that you might need materialized list for service injection.

Let me explain `AvoidInlineMapping` & why it becomes `IEnumerable<>` instead of materialized list.

Inline mapping is process to improve performance for mapping logic between types. For example,

```csharp
var dtoParent = MapParent(pocoParent)

DtoParent MapParent(PocoParent pocoParent) {
    return new DtoParent {
        Child = MapChild(pocoParent.Child),
        ....
    };
}

DtoChild MapChild(PocoChild pocoChild) {
    return new DtoChild {
        ....
    }
}

```

will become just

```csharp
var dtoParent = new DtoParent {
    Child = new DtoChild {
        ...
    },
    ...
};

```

In your case, default mapping will become

```csharp
var dtos = pocos.Select(poco => new Dto { 
    Id = poco.Id,
    Name = MapContext.Current.GetService<IMockService>().GetName(),
});
```

However, when you add `AvoidInlineMapping`, Mapster needed to create new method to map list, so new list will be created.

Unluckily, Mapster mapping logic needed to support not just only mapping. But also EF query and code generation. So if you expect `IEnumerable<>`, you got `IEnumerable<>`, not list.

Your concerned about EF, it should not happen. Because when your got the object, it means EF already materialize for us.

I will reopen, as it should materialize list for service provide (and other case which required `MapContext`).

PR is welcome, please help us improve project.

**Comment by n-shay** [comment]
Thank you for the detailed explanation, @chaowlert !

Fortunately for us, in our usage, we don't perform mapping on EF queryable and all our data is eagerly loaded. 
But the un-materialized DTOs/collections are passed to MVC's action result and fail during JSON serialization since the IoC container is not available.

That being said, I'm still interested in the performance boost from the inline mapping at some point so I'll dig into this source code and hopefully provide a PR for this issue. It might take a little while tho since I'm swamped at work at the moment.

**Comment by andrerav** [comment]
@n-shay Did you solve this issue on your end?

**Comment by n-shay** [comment]
> @n-shay Did you solve this issue on your end?

I did not. 
We are still using the workaround suggested in the original post: `config.Default.Settings.AvoidInlineMapping = true;`.

I ended up creating a mapper wrapper to be used globally in our solution with some `MapContextScope` wizardry (I don't remember if it was to solve this issue or another, forgot to leave comments):

```
    public class Mapper<TSrc> : IMapper<TSrc>
    {
        private readonly IMapper mapper;
        private readonly ILogger<Mapper<TSrc>> logger;

        public Mapper(IMapper mapper, ILogger<Mapper<TSrc>> logger)
        {
            this.mapper = mapper;
            this.logger = logger;
        }

        public TDest Map<TDest>(TSrc source)
        {
            try
            {
                using var scope = MapContextScope.RequiresNew();
                return this.mapper.Map<TSrc, TDest>(source);
            }
            catch (Exception ex)
            {
                this.logger.LogError(
                    ex,
                    "Failed to map object {SourceType} to {DestinationType}.",
                    typeof(TSrc).FullName,
                    typeof(TDest).FullName);

                throw new MappingException("Failed to map object.", ex);
            }
        }

        public IEnumerable<TDest> Map<TDest>(IEnumerable<TSrc> source)
        {
            try
            {
                using var scope = MapContextScope.RequiresNew();
                return this.mapper.Map<IEnumerable<TSrc>, IEnumerable<TDest>>(source);
            }
            catch (Exception ex)
            {
                this.logger.LogError(
                    ex,
                    "Failed to map object collection {SourceType} to {DestinationType}.",
                    typeof(TSrc).FullName,
                    typeof(TDest).FullName);

                throw new MappingException("Failed to map object collection.", ex);
            }
        }
    }
```

**Comment by andrerav** [comment]
As mentioned above this is basically a limitation in Mapster that can be worked around. PR's are still welcome if someone finds a nice solution that is compatible with code generation. Closing this for now.

**Comment by asymetrixs** [comment]
This looks like it is similar to #230 
I wrote a little solution/workaround on StackOverflow with an explanation on why it works this way: https://stackoverflow.com/questions/69749350/mapster-context-is-null-in-nested-mappings/75249680#75249680
