### ISSUE TITLE
Adapting DateTimeOffset to DateTime Not Working

### ISSUE THREAD

**Issue by edgett** [MapsterMapper/Mapster#335]
.net 5:

```
void Main()
{
	var ObjWithDateTimeOffset = new Dto1 { MyProperty = new System.DateTimeOffset(2020, 1, 1, 1, 1, 1,1,new TimeSpan(0, 0, 0)) };
	
	var ObjWithDateTime = ObjWithDateTimeOffset.Adapt<Dto2>();
	
}


public class Dto1
{ 
	public DateTimeOffset MyProperty { get; set; }
}
public class Dto2
{
	public DateTime MyProperty { get; set; }
	
}

```

Produces the errror:

Error while compiling
source=System.DateTimeOffset
destination=System.DateTime
type=Map

**Comment by chaowlert** [comment]
It is by design, whatever types are able to convert in .NET, will be able to convert in Mapster. Datetimeoffset required datetime+timezone, therefore it cannot convert directly from datetime.

Pls define custom mapping for this.
