### ISSUE TITLE
Request or Question with Entity Framework and SQL projection

### ISSUE THREAD

**Issue by cblaze22** [MapsterMapper/Mapster#346]
I have officially switched over from Automapper to Mapster and didn't know if there was a ProjectTo option with Entity Framework that creates sql based only on the properties of the DTO like Automapper does?  No worries if not, I wasn't using it anyway and curious if their was an option or plan on it for the future.

**Comment by chaowlert** [comment]
Do you mean this? https://github.com/MapsterMapper/Mapster/wiki/Basic-usages

**Comment by cblaze22** [comment]
So the ProjectToType works with an entity framework context? If so that great
