### ISSUE TITLE
Question: When I change proprety name, do I need to manually map it

### ISSUE THREAD

**Issue by floatas** [MapsterMapper/Mapster#357]
Hello,

I have following config:
![image](https://user-images.githubusercontent.com/7883111/125736145-fa169cff-6892-4d10-8262-db42fd9fbaca.png)

Swagger returns:
![image](https://user-images.githubusercontent.com/7883111/125736237-37b4fafd-66d5-46e6-8fd1-22a9a5a20236.png)

Controller:
![image](https://user-images.githubusercontent.com/7883111/125736371-ca739b79-28bd-44a4-b653-f53e9428c611.png)

Question: when I change property name, do I need to manually map it ?

**Comment by andrerav** [comment]
Please read the documentation and use StackOverflow for general questions.
