### ISSUE TITLE
Keep parameter casing when generating Immutable Record mapped through constructor

### ISSUE THREAD

**Issue by ericbeaudry** [MapsterMapper/Mapster#358]
Since Mapster.Tool is generating Record using the positional syntax, it is preferable/advisable not to change the casing of the properties that are mapped. 

Currently an Entity like this one:
```
public class EntityA {
	public string Prop1 { get; set; } // upper case P here 
}
```

Becomes a Record like this:
```
public partial record EntityAModel(string prop1); // lower case p here
```
The compiler then generates the property prop1 which is now of the wrong casing. Leading to inconsistency during mapper generation where the mapping between properties cannot be resolved. The mappers then simply inserts a null in place of the parameter, like so:

```
return new EntityAModel(null);
```

I understand that, in c#, constructor parameters should be starting with a lower case but here we're dealing with Record positional syntax which is a little different. A reference to the docs highlighting [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#positional-syntax-for-property-definition) and also where this is happening in [ExpressionDebugger](https://github.com/chaowlert/ExpressionDebugger/blob/fb878b81e6f45681d1ec6bfa07e39929f4ecaeef/ExpressionTranslator/ExpressionTranslator.cs#L2015)

**Comment by DonnelCyril** [comment]
Running into the same issue as above.

**Comment by andrerav** [comment]
@DonnelCyril @ericbeaudry Hm, seems like this could be a potentially easy fix. My immediate proposal is that this line:
```csharp
Write($"{TranslateNullable(parameter.Type, parameter.NullableContext ?? Definitions?.NullableContext, parameter.Nullable)} {char.ToLower(parameter.Name[0]) + parameter.Name.Substring(1)}");
```
Is changed into something like this (not syntax checked yet:P):
```csharp
Write($"{TranslateNullable(parameter.Type, parameter.NullableContext ?? Definitions?.NullableContext, parameter.Nullable)} {Definitions?.IsRecordType ? char.ToLower(parameter.Name[0]) + parameter.Name.Substring(1) : parameter.Name}");
```
Do you think this makes sense?

**Comment by EricOnGit** [comment]
That's how I overcame the problem on my branch at the time.

**Comment by andrerav** [comment]
@EricOnGit Great, thank you for confirming that. I just implemented the fix in ExpressionDebugger, and while I had to fix one test that failed, this is looking fairly straightforward. This will definitely break some code for people who are using the ExpressionDebugger library outside of Mapster though, but it will break only after generating code. So I think this should be fairly safe to push quickly to NuGet. Does this argument make sense to you guys?

**Comment by DonnelCyril** [comment]
Thanks for the quick turnaround @andrerav. Not sure about the process of getting this published into a NuGet package? I see this is flagged against the 7.4.0 milestone, but don't have a set release date for it?

**Comment by DonnelCyril** [comment]
I came across this issue trying to work around an issue with _init_ properties which I have logged - #422 
While the mapping issue goes away, casing of the properties causes the other issues mentioned above. 
Bit of a showstopper for us at the moment, any urgency in this will be much appreciated.

**Comment by andrerav** [comment]
@DonnelCyril I have published NuGet packages for ExpressionTranslator, as soon as the NuGet index updates I will update the Mapster dependency and create a prerelease package for 7.4.0 that you can try out.
