### ISSUE TITLE
Mapper does not map two dictionaries how I excpected

### ISSUE THREAD

**Issue by YuraPunchyk** [MapsterMapper/Mapster#361]
Example:

var source = new Dictionary<string, string>() {
  {"key1": "value1"},
  {"key2": ''value2"}
}

var destination = new Dictionary<string, string>() {
  {"key1": "value"},
  {"key3": ''value3"}
}

mapping result:
  {"key1": "value"},
  {"key2": ''value2"},
  {"key3": ''value3"}

I expect the result like: 
  {"key1": "value"},
  {"key2": ''value2"}

Can I configure Mapper so that mapping of dictionary would not be union for all dictionaries in my Class?

**Comment by andrerav** [comment]
You can use Ignore() if you wish to exclude certain keys from the mapping.
