### ISSUE TITLE
Unable to generate Viewmodel because Mapster.Tool can't handle ObservableCollection

### ISSUE THREAD

**Issue by FinalFortune** [MapsterMapper/Mapster#372]
```
System.InvalidOperationException: System.Collections.ObjectModel.ObservableCollection`1[System.String] is not supported for projection, please consider using List<>
```

**Comment by andrerav** [comment]
@FinalFortune The error message seems clear enough, I will close this issue for now but if you have more information about your use case and why/how you think this should be fixed and please feel free to reopen.
