### ISSUE TITLE
generate mappers without the mapping register class

### ISSUE THREAD

**Issue by xapr170** [MapsterMapper/Mapster#373]
Awesome tool by the way! I am building a console generator that asks for the class in runtime... I  created a wrapper over the mapster tool and currently generate everything on the assembly. Is there a way to just generate a specific class and any other class declared inside the entity? Or could you point me over the method that generates the two way mappings?

**Comment by andrerav** [comment]
@xapr170 Please use StackOverflow for questions about usage. Thank you very much :)
