### ISSUE TITLE
Interface Property not mapping

### ISSUE THREAD

**Issue by aicukltd** [MapsterMapper/Mapster#392]
Hello

I love the lightweight powerful mapper however I am struggling with one element of the mapping capability. 

Class
`public class TypeA
{
     ITypeB TypeB {get;set;}
}`

Mapping
`var destination = source.Adapt<TSource, TDestination>();`

Result
`public class TypeA
{
     GeneratedType_1 TypeB {get;set;}
}`

1. I have a class that implements ITypeB. 

Any help would be appreciated.

**Comment by aicukltd** [comment]
Further to this, this is the class that registers my configs.

`
    public static void RegisterMapster(IServiceCollection serviceCollection)
    {
        var externalModelsAssemblyTypes = Assembly.Load("Project.Models.Persistence.External").DetectTypesToRegisterAndMatchToInterface();
        var externalSharpModelsAssemblyTypes = Assembly.Load("ExternalSharp").DetectTypesToRegisterAndMatchOnName(externalModelsAssemblyTypes.Keys);

        foreach (var externalModelsAssemblyType in externalModelsAssemblyTypes)
        {
            TypeAdapterConfig.GlobalSettings.ForType(externalModelsAssemblyType.Key, externalModelsAssemblyType.Value).PreserveReference(true);
            TypeAdapterConfig.GlobalSettings.ForType(externalModelsAssemblyType.Value, externalModelsAssemblyType.Key).PreserveReference(true);
        }

        foreach (var externalSharpModelsAssemblyType in externalSharpModelsAssemblyTypes)
        {
            TypeAdapterConfig.GlobalSettings.ForType(externalSharpModelsAssemblyType.Value, externalSharpModelsAssemblyType.Key).PreserveReference(true);
            TypeAdapterConfig.GlobalSettings.ForType(externalSharpModelsAssemblyType.Key, externalSharpModelsAssemblyType.Value).PreserveReference(true);
        }

        TypeAdapterConfig<ExternalSharp.Customer, Customer>.NewConfig().Map(x => x.ExternalObjectId, x => x.Id).Ignore(destinationMember => destinationMember.Id).TwoWays();
        TypeAdapterConfig<ExternalSharp.Order, Order>.NewConfig().Map(x => x.ExternalObjectId, x => x.Id).Ignore(destinationMember => destinationMember.Id).TwoWays();
        TypeAdapterConfig<ExternalSharp.Product, Product>.NewConfig().Map(x => x.ExternalObjectId, x => x.Id).Ignore(destinationMember => destinationMember.Id).TwoWays();
        TypeAdapterConfig<ExternalSharp.Address, IAddress>.NewConfig().Map(x => x.ExternalObjectId, x => x.Id).TwoWays();
    }
`

**Comment by andrerav** [comment]
@aicukltd It seems your example uses dynamic assembly loading, and so it is difficult to tell if the problem you are seeing is related to that or to a potential bug in Mapster. Can you try making a simple reproducible example without dynamic assembly loading?

**Comment by satano** [comment]
Well I managed to make this work. I need to specify explicit mapping configuration between that target interface type and used source type:

``` c#
TypeAdapterConfig<string, IValueData>.NewConfig()
    .MapWith(src => new ValueData { Value = src });
```

But it would be nice to have `MapWith` method for specific destination properties, not for all properties of some type. Something like:

``` c#
TypeAdapterConfig<SourceDto, TargetDto>.NewConfig()
    .MapWith(dest => dest.InterfaceProp, src => OurCustomLogicToCreateInstance(src));
```

**Comment by andrerav** [comment]
@satano Sorry for the late reply. Unfortunately we can't support this scenario due to code generation limitations. Glad you figured it out :)

**Comment by mehrdades** [comment]
you can also ignore the mapping and use AfterMapping to overcome this problem.
`TypeAdapterConfig<SourceDto, TargetDto>.NewConfig()
        .Ignore(dest => dest.InterfaceProp);
        .AfterMapping((src, dest) => dest.InterfaceProp, src => new ValueData { Value = src.DataProp });`
