### ISSUE TITLE
希望对.net 4.5支持（Want：The lowest version supports NET 4.5）

### ISSUE THREAD

**Issue by ping9719** [MapsterMapper/Mapster#412]
我们的用户使用win7系统非常多，所以我们需要对低版本net的一个支持（There are many users of Windows 7，So we need to support lower versions of NET）

辛苦作者，谢谢。（thank）

希望5735没什么事。

**Comment by andrerav** [comment]
I am sorry to hear that. If you are required to use .NET 4.5 then please use Mapster v7.2.0. Thank you.

**Comment by ping9719** [comment]
我知道，支持低版本的话时间成本和性能确实难以解决。（I know，If lower versions are supported，Time cost and performance are really difficult to solve.）

如果是服务器端我肯定使用最新版本，但是是客户端我们开发者就需要考虑非常多的问题。（If it is B/S, I will use the latest version。But for C/S, We developers need to consider a lot of problems）

那我就使用7.2.0吧。其实也没有多大的问题，我也是执着想用最新的而已。（I use version 7.2.0 . Have nothing wrong with，ideologism new version..... ） ┐(￣ー￣)┌

谢谢（thank）
