### ISSUE TITLE
Multi-tier mapping failed

### ISSUE THREAD

**Issue by ArchitectAllenGitHub** [MapsterMapper/Mapster#420]
I thought this project was very good, so I tried to use it and planned to replace Autofac, but I found a problem in the process of testing. Hope that helps
![image](https://user-images.githubusercontent.com/66348603/161437584-2f4b3245-c082-4444-a919-041ac40a92fe.png)
This is a two-level mapping and I only assigned the value of the property Name. But what is returned is not the desired result.
This is my Demo source code: https://github.com/ArchitectAllenGitHub/MapsterDemo.git

**Comment by andrerav** [comment]
Hi @ArchitectAllenGitHub, in your case you need to configure `AvoidInlineMapping = true`. Alternatively you can change the type on line 101 in Class1.cs from `IEnumerable<SchoolEntity>` to `List<SchoolEntity>`.
