### ISSUE TITLE
EntityState changed to Deleted after mapping

### ISSUE THREAD

**Issue by nicholasyin** [MapsterMapper/Mapster#423]
In an update scenario, I use the below code to save work needed to update the properties of database entity:
```
requestedItem.Adapt<T, T>(dbItem, config);
```
However, after this line of code gets executed, the dbItem's EntityState shows Deleted somehow. Don't know why.

**Comment by andrerav** [comment]
Hi @nicholasyin,
Is this EF or EF Core? Which version? Does it happen for all entities, or just one or a few specific ones?

**Comment by nicholasyin** [comment]
@andrerav thanks for the attention. Unfortunately I already managed to work around this issue the other day in my code and now can't repro it anyway. Later if I encounter it again I'll provide a reproduceable set of code.
