### ISSUE TITLE
Why version 7.3.0 don't support framework 4.6.1 

### ISSUE THREAD

**Issue by zhangboyanzhangboyan** [MapsterMapper/Mapster#425]

**Comment by Duranom** [comment]
Version 7.3.0 targets .net standard 1.3 and .net standard 2.0
.NET Standard 1.3 allows targeting .NET Framework 4.6.1, .NET Standard 2.0 also allows it but has some issue's.
.NET Framework 4.6.1 will target the highest available .NET Standard, however .NET Framework 4.6.1 has some issue's when there is a .NET standard 2.0 targeting framework available and it will always use that. If you experience that then two options are possible:
1. Put the associated code in a separate library that targets .net standard 1.3
2. Upgrade to .NET Framework 4.6.2 or higher.
Issue information: https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

It is recommended to upgrade your project to at least 4.6.2, this also keep in the .NET Framework support cycle and it fixes the reference issues. However, if possible it is highly recommend to even go to .NET Framework 4.8 or at least 4.7.2.
The first option can be done but you have the possibility to introduce another issue.
