### ISSUE TITLE
[Question] How to get specific member configuration?

### ISSUE THREAD

**Issue by devbased** [MapsterMapper/Mapster#432]
I need to find source member (and its value) by destination name.
As a workaround i could create temporary model object but obviously this is undesirable approach :sweat_smile:

Example using AutoMapper
```csharp
// validation omitted for brevity
var map = this._mapper.ConfigurationProvider.FindTypeMapFor<TDto, TModel>();

var dtoPrimaryKey = modelPrimaryKey.Properties
    .Select(x => map.GetPropertyMapByDestinationProperty(x.Name))
    .Select(x => x.SourceMembers.First().GetMemberValue(dto))
    .ToArray();
```

**Comment by JMPSequeira** [comment]
@devbased How did you end up solving this?

**Comment by devbased** [comment]
@JMPSequeira Needed functionality already exists in Mapster.EFCore

Member configuration could be accessed via ValueAccessingStrategies, see:
https://github.com/MapsterMapper/Mapster/blob/06dddf7e7e470e77b5d01a6c490e046686146b4a/src/Mapster.EFCore/TypeAdapterBuilderExtensions.cs#L58-L65
