### ISSUE TITLE
Unable to configure the custom mapping using "ConstructUsing"

### ISSUE THREAD

**Issue by Gopichandar** [MapsterMapper/Mapster#461]
I'm not able to map the following custom mapping and this possible with automapper.  Any work around. 

```
 config.NewConfig<List<MyResult>, MyResultDto>()
            .ConstructUsing(x => 
            {
              //do some custom stuff
               return new PcrResultDto()
               {
                   
               }
            });
```

**Comment by goremykin** [comment]
Use MapWith

**Comment by Gopichandar** [comment]
Thanks, @goremykin, is this documented somewhere (or) are there any samples available that I can refer to?  I have a feeling that Mapster bit lack on documentation.

**Comment by goremykin** [comment]
@Gopichandar, [Wiki](https://github.com/MapsterMapper/Mapster/wiki/Custom-conversion-logic)

**Comment by Gopichandar** [comment]
Thanks alot @goremykin
