### ISSUE TITLE
[Question] How to use Mapster with codegen?

### ISSUE THREAD

**Issue by ComptonAlvaro** [MapsterMapper/Mapster#478]
I could see that the fastest way to map it is with codegen. So I check the example for codegen that I can find here: https://github.com/MapsterMapper/Mapster/tree/master/src/Sample.CodeGen

But in the .csproj file I don't see any configuration to enable CodeGen and in any other place. So if to use CodeGen is an option, how could I enable.

Thanks so much.

**Comment by vip32** [comment]
look at the csproj

**Comment by andrerav** [comment]
Please check the documentation and the sample. Also please use StackOverflow or similar resources for general questions like this.
