### ISSUE TITLE
Mapster.Tool not compatible with .NET 6

### ISSUE THREAD

**Issue by alegreenp** [MapsterMapper/Mapster#483]
Hi,
I'm developing an API with .NET 6.0 and I'm trying to install Mapster.Tool but i get these errors:

The combination of project-package for Mapster.Tool 8.4.0-pre03 is not valid. Project style DotnetToolReference can only contain references of DotnetTool type.
	
Package 'Mapster.Tool 8.4.0-pre03' contains a package 'DotnetTool' that is not supported by project 'MyProject'.
				
NU1202
Package Mapster.Tool 8.4.0-pre03 is not compatible with net6.0 (.NETCoreApp,Version=v6.0).
Package Mapster.Tool 8.4.0-pre03 supports:
  - net5.0 (.NETCoreApp,Version=v5.0)/any
  - net6.0 (.NETCoreApp,Version=v6.0)/any
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)/any

Anybody can help me?
I already tried with others versions but it doesn't work.

**Comment by borbiuk** [comment]
You are trying to install Mapster.Tool as nuget package but it should be installed other way.
(see [docs](![image](https://user-images.githubusercontent.com/41112208/191972704-c6a0bee9-4db7-4026-ba26-a081758138f7.png))).

1. `dotnet new tool-manifest`
2. `dotnet tool install Mapster.Tool`
3. `dotnet mapster [args]`
