### ISSUE TITLE
Mapster.EFCore does not support .net 7

### ISSUE THREAD

**Issue by cedwards-telis** [MapsterMapper/Mapster#495]
This is almost identical to

https://github.com/MapsterMapper/Mapster/issues/394 

And has happened for the same reason, mixed versions of ef core assemblies.  The assembly reference for efcore needs to be upped to 7.0 and at the same time version of the plug in should probably be updated to 7.0 as well.

**Comment by andrerav** [comment]
Preview NuGet packages are available now.
