### ISSUE TITLE
Queryable Extensions fails with async

### ISSUE THREAD

**Issue by cherchyk** [MapsterMapper/Mapster#509]
```
[HttpGet]

public async Task<ActionResult<IEnumerable<DTO_T>>> GetRecords()
{
var result_T = await _context.Set<T>().AsNoTracking().Where(o => o.TenantId == RequestTenantId).ProjectToType<DTO_T>();

return null;
}
```

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1703275/208581766-6fe57fd9-870b-4864-858f-60aa9dc06a25.png">

**Comment by felaray** [comment]
it's work for me
![image](https://user-images.githubusercontent.com/5403865/209268424-fedeeb3c-6fab-49d2-8d2b-d0ac7d0d6649.png)
