### ISSUE TITLE
Expression mapping

### ISSUE THREAD

**Issue by ryco72** [MapsterMapper/Mapster#517]
Can Mapster map expressions?
E.g., I'd like to use Mapster to do this:

entityFilterExpression = _mapper.MapExpression<Expression<Func<TEntity, bool>>(modelFilterExpression)

where modelFilterExpression is of type Expression<Func<TModel, bool>>

This is feasible with the library [AutoMapper.Extensions.ExpressionMapping](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping), but till now I didn't find a way to do the same with Mapster

**Comment by andrerav** [comment]
One of Mapsters major advantages compared to Automapper is code generation, and expression mapping would be complicated to implement (if even possible) given the way the code generation works now.  If the current feature set is not enough to cover your use cases then I think you're out of luck, unfortunately.
