### ISSUE TITLE
ProjectToType with single entitiy

### ISSUE THREAD

**Issue by heggi** [MapsterMapper/Mapster#522]
Standard code to get one entity from database if entity exists:

```csharp
var entity = context.Set<ExampleModel>()
    .Where(m => m.Id = id)
    .FirstOrDefault();
```
Here entity variable has a nullable type `ExampleModel?` and I can check it for `null` (if `null`, no entity found in db)

Now I want add ProjectToType

```csharp
var entity = context.Set<ExampleModel>()
    .Where(m => m.Id = id)
    .ProjectToType<ExampleDTO>()
    .FirstOrDefault();
```

Here entity variable has a not nullable type `ExampleDTO`
If entity in database is absent, we anyway got instance of `ExampleDTO`

Here we need a some method (for example `ProjectToTypeSingle`) which will return `IQueryable<TDestination?>`
Or has any workaround?

**Comment by andrerav** [comment]
Hehe @heggi you are destroying me with all these issues:D Does it work as expected if you add a ToList() like this?

```csharp
var entity = context.Set<ExampleModel>()
    .Where(m => m.Id = id)
    .ToList()
    .ProjectToType<ExampleDTO>()
    .FirstOrDefault();
```

**Comment by heggi** [comment]
I do more experiment. 
My mistake was in ExampleDTO (I create it as struct)

If ExampleDTO is struct, I got this problem. And if I replace `ProjectToType` via `Select(x => new ExampleDTO { ... })` got same problem. And problem here in FirstOrDefaultAsync, not ProjectToType :)
FirstOrDefaultAsync return default value, and default value for struct - is empty struct, not null :)

If change type of ExampleDTO to `class` or `record`, all works as expected, FirstOrDefaultAsync return null.

Sorry for disturbing.

**Comment by andrerav** [comment]
Ah okay, good to know :) Glad you figured it out!
