### ISSUE TITLE
[Bug?] serviceCollection.AddMapster(); is missing -- v. 7.3.0 

### ISSUE THREAD

**Issue by jeffward01** [MapsterMapper/Mapster#525]
Hello all!

I am unsure if this is a bug, or a caching issue.. As you can see, I have installed:

* Mapster: 7.3.0
* Mapster.DependencyInjection: 1.0.0

I try and perform `services.AddMapster();` and it is 'not found.  Please look at my using statements and set-up.

![image](https://user-images.githubusercontent.com/12589359/212457578-f04d6892-2817-4197-b160-9922a406056b.png)

I have restarted Rider a few times in attempt to clear the package cache, incase it is a cache issue, and the issue persists.

Strangely - I can add the dependency manually like: `services.AddTransient<IMapper, Mapper>();` and it works fine.

See here:

![image](https://user-images.githubusercontent.com/12589359/212457610-4b4cc769-21c3-47ac-b488-924604b2eaaa.png)

Here is my `.csproj` file:
![image](https://user-images.githubusercontent.com/12589359/212457637-f9a3d4cc-eee6-48d2-b20f-9076745f13fa.png)

Note: `Riok.Mapperly` and `MapTo` are other mapping libraries I was testing out.

I then proceeded to debug by installing the 'pre-release' versions of `Mapster`, the issue still persisted:

![image](https://user-images.githubusercontent.com/12589359/212457704-69d02150-12c3-4735-bcad-1f2230782a65.png)

-----

Is this a bug? How can I help you debug this.

Thanks all

**Comment by andrerav** [comment]
AddMapster() is scheduled for the upcoming v7.4.0. I think it should be available in the latest prerelease package though.

**Comment by jeffward01** [comment]
Sounds good thanks!

**Comment by DumboJetEngine** [comment]
I might be missing something, but v.7.4.0 doesn't seem to have it either now. :\

**Comment by iMuhammadMustafa** [comment]
> I might be missing something, but v.7.4.0 doesn't seem to have it either now. :\

I can't use it too
