### ISSUE TITLE
Ignore properties

### ISSUE THREAD

**Issue by urza** [MapsterMapper/Mapster#560]
Hi, I like the simplicity and minimalist approach of Mapster.

Is it possible to ignore some properties without creating config? 

I would imagine something like this:

`sourceObject.Adapt(destObject).Ignore("PropertyToIgnore", "AnotherPropertyToIgnore");`

**Comment by andrerav** [comment]
The Adapt() method is always supposed to return the mapped destination object. This proposal would break that API. It should probably look something like this instead:

```csharp
sourceObject
    .WithIgnore(...)
        .Adapt(destObject);
```

You can probably write that extension method yourself. It just needs to wrap TypeAdapterConfig.NewConfig().Ignore(...) and return the sourceObject afterwards.

**Comment by urza** [comment]
@andrerav Thanks, I will try to do that.
