### ISSUE TITLE
Mapster giving issue with c# record no default contractor for type

### ISSUE THREAD

**Issue by yyogesh** [MapsterMapper/Mapster#576]
Mapster giving issue with c# record no default contractor for type "Class_Name", Please use ConttructUsing or MapWith

public record User(int Id, string FirstName, string LastName);

public record UserResponse(int Id, string FirstName, string LastName);

 var user = new User(1, "abc", "xyz");
 
 var userResponse = user.Adapt<UserResponse>();

**Comment by stagep** [comment]
Your code example did not compile. The following change to the last line did compile and mapped as expected.

var userResponse = user.Adapt<UserResponse>();
