### ISSUE TITLE
Looping or stackoverflow with Linq-to-Sql entities

### ISSUE THREAD

**Issue by shakir-timur** [MapsterMapper/Mapster#584]
I've encounterd this issue while trying to map some linq2sql class to a model using Adapt extension method. Original issue was infinite looping at the mapping moment. While I cannot reproduce looping, I have other example that causes stackoverflow. 

Demo attached.
[MapsterInfiniteLoop.zip](https://github.com/MapsterMapper/Mapster/files/11301676/MapsterInfiniteLoop.zip)

**Comment by andrerav** [comment]
Please take a look at the documentation here: https://github.com/MapsterMapper/Mapster/wiki/Object-references
