### ISSUE TITLE
没有包含任何属性的class映射失败

### ISSUE THREAD

**Issue by liuqing19851022** [MapsterMapper/Mapster#585]
``` c#
public class TestEmpty
{
}

public class SubEntity : TestEmpty
{ }

TestEmpty testEmpty = new TestEmpty();
SubEntity subEntity = testEmpty.Adapt<SubEntity>();
```

System.InvalidCastException: Unable to cast object of type 'Sample.AspNetCore.Models.TestEmpty' to type 'Sample.AspNetCore.Models.SubEntity'.
 at lambda_method12(Closure , Object )

**Comment by stagep** [comment]
You can not cast from a base type to a derived type. There is no guarantee that TestEmpty is of type SubEntity. You can however cast to the base class as follows:

`SubEntity subEntity = new SubEntity();
 TestEmpty testEmpty = subEntity.Adapt<TestEmpty>();`
