### ISSUE TITLE
ProjectToType not working well with inheritance

### ISSUE THREAD

**Issue by AzGhort** [MapsterMapper/Mapster#589]
Hello, 

I have a problem using `ProjectToType` with base-derived class inheritance. 
I have a config as follows:

```
            config
                .ForType<IPCamera, IpCameraDto>()
                .Map(m => m.Image, d => d.AvatarImage)
                .Map(m => m.IpAddress, d => d.IPAddress.ToString())
                .Include<AxisIPCamera, AxisIpCameraDto>()
                .Include<BaslerIPCamera, BaslerIpCameraDto>()
                .Include<BaslerGrabberIPCamera, BaslerGrabberIpCameraDto>()
                .Include<VirtualIpCamera, VirtualIpCameraDto>();
```
and I am mapping as follows:
```
IQueryable<IPCamera> queryable = ...;
queryable.ProjectToType<IPCameraDto>()
```

The result of map only contains instances of base class dto (`IPCameraDto`) rather than respective derived types.
When mapping in-memory as follows:
```
List<IPCamera> cameras = new { .... };
var dtos = _mapper.Map<IPCameraDto>()
```
The resulting list correctly contains only derived types (`AxisIpCameraDto, BaslerIpCameraDto, ...`).

Am I doing something wrong? Is this desired behavior? Or is there a bug in `ProjectToType` method? 

Thanks in advance

**Comment by flobiber** [comment]
I also have this behaviour and had expected it differently

**Comment by andrerav** [comment]
@AzGhort Try materializing your queryable before calling ProjectToType(). Let me know if the problem is still there :)

**Comment by AzGhort** [comment]
Ok thanks for the replies!
