### ISSUE TITLE
Mapster tool 8.4.0-pre06, how to find a corresponding commit?

### ISSUE THREAD

**Issue by wondertalik** [MapsterMapper/Mapster#616]
Hello, i trying to figure out what version is published on nuget. Can somebody help me?

**Comment by andrerav** [comment]
Pre-release versions are not tagged, but are usually released from the _development_ branch. The csproj files will have their version numbers updated when the packages are created and published, so you should be able to track find the latest commit for example by looking at the history of [Mapster.csproj in the development branch](https://github.com/MapsterMapper/Mapster/commits/development/src/Mapster/Mapster.csproj).
