### ISSUE TITLE
MapsterMapper mapping base class

### ISSUE THREAD

**Issue by 1210108** [MapsterMapper/Mapster#618]
I am using Mapster for mapping my objects.

I have the the following code:

```
public sealed class User : AggregateRoot<UserId>
{
	public string FirstName { get; }
	public string LastName { get; }
	public string Email { get; }
	public string Password { get; }
	public DateTime CreatedDateTime { get; }
	public DateTime UpdatedDateTime { get; }

	private User(UserId userId, string firstName, string lastName, string email, string password)
		: base(userId)
	{
		FirstName = firstName;
		LastName = lastName;
		Email = email;
		Password = password;
		CreatedDateTime = DateTime.UtcNow;
	}
}
```

```
public sealed class UserId : ValueObject
{
	public Guid Value { get; }

	private UserId(Guid value)
	{
		Value = value;
	}
}
```

```
public record AuthenticationResult(
	User User,
	string Token
);
```

```
public record AuthenticationResponse(
	Guid Id,
	string FirstName,
	string LastName,
	string Email,
	string Token
);
```

I am trying to map the AuthenticationResult to the AuthenticationResponse but i get this error

---> Mapster.CompileException: Error while compiling source=FinanceManager.Domain.User.ValueObjects.UserId destination=System.Guid type=Map ---> System.InvalidOperationException: Cannot convert immutable type, please consider using 'MapWith' method to create mapping

can anyone help me pls?

**Comment by andrerav** [comment]
Please use StackOverflow for these kinds of questions. Feel free to open an issue if you find a bug :) Thanks for using Mapster!
