### ISSUE TITLE
The given key 'EmptyProjectionMember' was not present in the dictionary

### ISSUE THREAD

**Issue by ms-webimo** [MapsterMapper/Mapster#624]
When using GroupBy/Select and after that calls ProjectToType<T>() an error occurs:

An unhandled exception has occurred while executing the request. System.Collections.Generic.KeyNotFoundException: The given key 'EmptyProjectionMember' was not present in the dictionary.

**Comment by SoranRad** [comment]
please share your code here

**Comment by webimo-dev** [comment]
```
public class Document
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }

    public string? LanguageId { get; set; }
    public string? Slug { get; set; }
    public string? Name { get; set; }
}

public class DocumentDto
{
    public Guid Id { get; set; }

    public string? LanguageId { get; set; }
    public string? Slug { get; set; }
    public string? Name { get; set; }
}

public async Task<IList<T>> GetDocuments<T>(string? slug, string? languageId)
{
    var iq = _dataContext.Documents
        .Where(x => slug == null || (slug != null && x.Slug == slug))
            .Select(x => x
                .OrderByDescending(y => y.LanguageId == languageId)
                .ThenByDescending(y => y.LanguageId == "da")
                .ThenBy(y => y.Name)
                .First())
            .AsNoTracking().ProjectToType<T>().ToListAsync();
}

var documents = await GetDocuments<DocumentDto>(null, "en");
```

**Comment by SoranRad** [comment]
And What about your mapster config ? how did you do that?
please try these two
1. IgnoreNullValue in mapster config ([https://github.com/MapsterMapper/Mapster/wiki/Shallow-merge]( https://github.com/MapsterMapper/Mapster/wiki/Shallow-merge))
3. change your method to this one :
```C#
public async Task<IList<T>> GetDocuments<T>(string? slug, string? languageId)
{
    return await _dataContext.Documents
        .Where(x => slug == null || (slug != null && x.Slug == slug))
            .Select(x => x
                .OrderByDescending(y => y.LanguageId == languageId)
                .ThenByDescending(y => y.LanguageId == "da")
                .ThenBy(y => y.Name)
                .First())
           .Where(x=>x != null)
            .AsNoTracking().ProjectToType<T>().ToListAsync();
}
```

**Comment by webimo-dev** [comment]
In this case I only have the global config:

`public static class MapsterConfiguration
{
	public static void AddMapster(this IServiceCollection services)
	{
		TypeAdapterConfig.GlobalSettings.Default
			.IgnoreNullValues(true)
			.PreserveReference(true)
			.AddDestinationTransform((string x) => x.Trim()); // Does not seem to work
        }
}`

So there should be taken care of null's?

**Comment by SoranRad** [comment]
use this code 
`C#

   TypeAdapterConfig.GlobalSettings.Default.AddDestinationTransform((string x) => (string.IsNullOrEmpty(x) ? null : x.Trim()));

`

**Comment by webimo-dev** [comment]
Thanks, I'll try that.

What do you think about the GroupBy problem?

**Comment by SoranRad** [comment]
I mapped Groupby result by mapster but you didnt groupby anything in your code 
if you would like i can connect to you via anydesk and resolve your problem.

**Comment by andrerav** [comment]
This issue comes up a lot -- the simple answer is that you should materialize your query before calling ProjectToType when using Entity Framework. Due to the way Mapster is designed, it's not possible to make this work perfectly in all use cases. If you absolutely need to do this, you should switch to Automapper instead which has more robust support for this use case.
