### ISSUE TITLE
.NET 8 support

### ISSUE THREAD

**Issue by agriffard** [MapsterMapper/Mapster#652]
Do you plan to support .NET 8 when it is released Mid-November?

While it is already available in RC2, have you tried to add it in your TargetFrameworks to check that there won't be any issue migrating to it?

Thank you in advance for your answer.

**Comment by andrerav** [comment]
Hi @agriffard, .NET 8 support has already been added and published as a pre-release package: https://www.nuget.org/packages/Mapster/7.4.1-pre01

I'm planning to do a full release more or less coordinated with .NET itself.
