### ISSUE TITLE
The tool doesn't seem to work on net8.0

### ISSUE THREAD

**Issue by Gaven-F** [MapsterMapper/Mapster#674]
I have just used Mapster, and I think it is very powerful, but I seem to have discovered a problem, that is: using the mapster tool to generate dto in net8.0, this operation does not work, you need to adjust the target framework to 7.0 or 6.0. Can.

In addition, I am from China. When using mapster tool, the prompt information it outputs will be garbled (as far as I know, it should be the reason why gbk is converted to utf-8). I have not found a solution so far. I hope it can output correct Chinese or It's okay to output English as long as it's not garbled. 😢

I will attach some screenshots below.

**Comment by Gaven-F** [comment]
> This part is a garbled screenshot.
> ![image](https://github.com/MapsterMapper/Mapster/assets/133743603/37f6866b-62ac-429c-bb3e-0277a6ca5fbf)

---

> This is a screenshot of my configuration.
> ![image](https://github.com/MapsterMapper/Mapster/assets/133743603/fb1069ad-ee5a-4486-bb53-da547b955fc4)
> ![image](https://github.com/MapsterMapper/Mapster/assets/133743603/4177a026-b2d1-48ca-9f3b-e4471111077e)

**Comment by stagep** [comment]
You need to use the pre-release versions of Mapster for .Net 8. If you are using Visual Studio then select "Include prerelease" when managing your Nuget packages. For Mapster.Tool at the Developer command prompt, first uninstall the current version with

dotnet tool uninstall Mapster.Tool

and then install the pre-release version with

dotnet tool install Mapster.Tool --version 8.4.1-pre01

**Comment by Gaven-F** [comment]
Okay, I get it, I'll go take a look

**Comment by HEBOS** [comment]
This doesn't work for me.

**Comment by stagep** [comment]
Open a new issue and provide some details of the exceptions you are getting. Include the Mapster version from your .csproj and the version in .config/dotnet-tools.json.
