### ISSUE TITLE
Adapting linq context object to model wipes value of a DateTime property

### ISSUE THREAD

**Issue by petrosmm** [MapsterMapper/Mapster#97]
I am sure that this is not a bug. However, in a recent attempt I was working on adapting a linq results with acceptable column names to a model as such:

`model = results.FirstOrDefault().Adapt<Model>();`

`results` is my linq object with the correctly named properties that bind to `Model`. All of them bind nicely except my property AddedDateTime (DateTime) on my object model gets set to {1/1/0001 12:00:00 AM}. It's fine up until it get's adapted.

**Comment by chaowlert** [comment]
Could you please provide reproduction step?

**Comment by petersmax** [comment]
Hello again. `Model `comes into ActionResult with the value of `DateTime.Now` then I use a Linq statement `IQueryable` object to connect to another database. The Linq structure differs from the model except the matching fields that I purposely matched their names. The field that is important to me has no matching names in the Linq context. The name of the field is `AddedDateTime`. It is a DateTime? nullable property. As  soon as I hit the Linq statements and pull back results I called `model = results.FirstOrDefault().Adapt<Model>();` and it overwrites my `AddedDateTime` field to `1/1/0001 12:00:00 AM`

**Comment by chaowlert** [comment]
My test is working fine. 

```
    public class Source
    {
        public DateTime? AddedDateTime { get; set; }
    }
    public class Destination
    {
        public DateTime? AddedDateTime { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var result = new Source().Adapt<Destination>();
            Console.WriteLine(result.AddedDateTime == null); //true
        }
    }

```

**Comment by chaowlert** [comment]
Please check following:
1. Database return correct value.
2. Model type has correct declaration.

**Comment by petersmax** [comment]
Can you please elaborate on #2?

Max Peters

**Comment by petersmax** [comment]
I understand what it means but I do not understand its relevance.

Max Peters

**Comment by chaowlert** [comment]
If your source type or destination type mistakenly declare as `DateTime` instead of `Nullable<DateTIme>`, Mapster will return `{1/1/0001 12:00:00 AM}`.

**Comment by petersmax** [comment]
If I am not mistaken both are set as DateTime? (Nullable) any other thoughts?

Max Peters

**Comment by petersmax** [comment]
Also can you ignore certain fields when adapting?

Max Peters

**Comment by chaowlert** [comment]
Here is ignore function https://github.com/eswann/Mapster#Ignore

**Comment by petersmax** [comment]
`// POST: Sample/Basic
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Basic(Model model)
        {
            using (LegacyApplicationLinqDbContext lb = new LegacyApplicationLinqDbContext())
            {
                LegacyApplicationLinqDbContext.WebModel prospect = model.Adapt<LegacyApplicationLinqDbContext.WebModel>();
// [....] more code
}`
At the top during the debug, when we post in our ActionResult as soon as we enter the method, our model object shows the proper value. I have triple and double confirmed this. As soon as we adapt it on the first line inside the using statement it we find AddedDateTime gets overwritten or has a different behaviour with respect to what I posted before.

**Comment by chaowlert** [comment]
Close as not reproducible, will reopen when there is more info
